/**
 * ideas/arcade-2021q3.ts
 * Arcade Archives 2021年7〜9月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2021q3Ideas = [
  {
    id: 'arcade-163',
    title: '雷電',
    brand: 'セイブ開発',
    year: 1990,
    duration: 20,
    difficulty: 'hard',
    concept: '4方向から同時に敵の波が迫ってくる。スマートボムがゆっくり充電されており、4方向全てに敵がいる状態でタップすると画面全体を一掃できる。1〜3方向だけの状態でタップすると一部しか消えない。全方向が埋まる瞬間を見計らえ。3回全消しでクリア。',
    objects: [
      { shape: 'triangle', role: '自機（中央）', note: '' },
      { shape: 'face', role: '敵（4方向から侵入）', note: '各方向の敵数インジケーター付き' },
      { shape: 'bomb', role: 'スマートボム（充電中）', note: '4方向全て揃うと光る' },
    ],
    counters: [
      { id: 'clears', name: '全消し数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '4方向全てに敵がいる状態でタップ3回',
    failTrigger: '3方向以下でタップ3回で失敗',
  },
  {
    id: 'arcade-164',
    title: 'シーファイターポセイドン',
    brand: 'タイトー',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: '潜水艦が水平に魚雷を発射する。敵艦は水面の異なる深度で移動している。魚雷の到達深度を調整してからタップ——艦の喫水深度と魚雷深度が一致したときだけ命中する。5隻撃沈でクリア。',
    objects: [
      { shape: 'rect', role: '潜水艦（左端）', note: '' },
      { shape: 'diamond', role: '魚雷（水平飛行・深度調整可）', note: '' },
      { shape: 'rect', role: '敵艦（各自異なる深度）', note: '' },
      { shape: 'rect', role: '深度インジケーター', note: '上下ボタンで調整' },
    ],
    counters: [
      { id: 'sunk', name: '撃沈数', target: 5, note: '5隻でクリア' },
    ],
    winTrigger: '深度一致状態でタップ5回',
    failTrigger: '深度外れ3回で失敗',
  },
  {
    id: 'arcade-165',
    title: 'ダーウィン4078',
    brand: 'データイースト',
    year: 1986,
    duration: 25,
    difficulty: 'hard',
    concept: 'DNA結晶を3個集めると船が進化する。しかし3個を一気に集めると進化過多で崩壊する——「安定インジケーター」が緑の間だけ結晶を収集し、インジケーターが赤（不安定）になったらタップして収集を停止して安定を待て。緑→収集、赤→停止を繰り返して5回進化でクリア。',
    objects: [
      { shape: 'circle', role: 'DNA結晶（浮遊）', note: '' },
      { shape: 'triangle', role: '自機（進化段階で形状変化）', note: '' },
      { shape: 'rect', role: '安定インジケーター（緑/赤）', note: '' },
    ],
    counters: [
      { id: 'evolutions', name: '安定進化数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'インジケーター緑の間に3個収集×5回',
    failTrigger: '不安定中に収集3回で失敗',
  },
  {
    id: 'arcade-166',
    title: 'クライムファイターズ2',
    brand: 'KONAMI',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: '敵がガードポーズを取る時間がある。ガードを崩すには連打ではなく、ガードが終わって攻撃モーションに移る0.5秒の「隙間」にタップしなければならない。ガード中に叩いても弾かれ、隙間を過ぎると反撃される。5回隙間攻撃でクリア。',
    objects: [
      { shape: 'face', role: '敵（ガード→隙間→攻撃のサイクル）', note: 'ガード中は青、隙間は黄色、攻撃は赤' },
      { shape: 'face', role: '主人公（左側）', note: '' },
    ],
    counters: [
      { id: 'hits', name: '隙間攻撃数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '敵の隙間（黄色）でタップ5回',
    failTrigger: 'ガード中タップ3回で失敗',
  },
  {
    id: 'arcade-167',
    title: '宇宙戦艦ゴモラ',
    brand: 'UPL',
    year: 1990,
    duration: 20,
    difficulty: 'hard',
    concept: '生体宇宙船ゴモラは酸攻撃を受けると装甲が永続ダメージを受ける。酸弾が飛来するとき、0.5秒だけシールドをタップで展開できる。シールド展開中に酸弾が当たれば完全ブロック。3発の酸を全てブロックしてクリア。',
    objects: [
      { shape: 'ellipse', role: 'ゴモラ（左端）', note: '装甲HPゲージ付き' },
      { shape: 'circle', role: '酸弾（右から飛来）', note: '' },
      { shape: 'button', role: 'シールドボタン（タップで0.5秒展開）', note: '' },
    ],
    counters: [
      { id: 'blocked', name: 'ブロック数', target: 3, note: '3発でクリア' },
    ],
    winTrigger: '酸弾到達前0.5秒以内にタップ3回',
    failTrigger: '酸弾3発被弾で装甲崩壊失敗',
  },
  {
    id: 'arcade-168',
    title: '功里金団',
    brand: 'タイトー',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '武将が動物の乗り物に跨り戦場を進む。敵が上段（騎乗の武将の首元）と下段（乗り物の足元）から同時に攻撃してくる。上下両方の攻撃者が同時に射程内に入った瞬間にタップして分身斬り——片方だけの状態でタップすると片方しか倒せない。3回同時斬りでクリア。',
    objects: [
      { shape: 'face', role: '武将（乗り物の上）', note: '' },
      { shape: 'face', role: '乗り物（下段）', note: '' },
      { shape: 'face', role: '上段の敵（騎乗位置）', note: '' },
      { shape: 'face', role: '下段の敵（地上）', note: '' },
    ],
    counters: [
      { id: 'syncs', name: '同時斬り数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '上下同時射程内でタップ3回',
    failTrigger: '片方だけ倒した3回で失敗',
  },
  {
    id: 'arcade-169',
    title: 'バンダイク',
    brand: 'UPL',
    year: 1990,
    duration: 20,
    difficulty: 'normal',
    concept: 'メカが旋回して前方の射界コーンを変えながら移動している。複数の敵が画面上に散らばっており、射界コーン内に2体以上が同時に入った瞬間にタップして同時射撃。1体だけではタップしない。3回以上の複数同時撃墜でクリア。',
    objects: [
      { shape: 'triangle', role: 'バンダイク（中央・旋回）', note: '前方射界コーン表示' },
      { shape: 'face', role: '敵×複数（散らばっている）', note: 'コーン内では光る' },
    ],
    counters: [
      { id: 'multi', name: '複数同時撃墜数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'コーン内に2体以上入った瞬間タップ3回',
    failTrigger: 'コーン内1体だけでタップ3回で失敗',
  },
  {
    id: 'arcade-170',
    title: 'スペースクルーザー',
    brand: 'タイトー',
    year: 1981,
    duration: 20,
    difficulty: 'normal',
    concept: '宇宙巡洋艦の4門の砲台がそれぞれ独立して装填・射撃サイクルを持つ。敵が特定の方向から来たとき、その方向を担当する砲台が「装填完了」状態でなければ発射しても弾が出ない。装填ゲージを確認し、目標方向の砲台が満タンになった瞬間にタップして発射。5回有効射撃でクリア。',
    objects: [
      { shape: 'rect', role: 'スペースクルーザー（中央）', note: '4方向砲台付き' },
      { shape: 'rect', role: '装填ゲージ×4（各方向）', note: '満タンで発射可' },
      { shape: 'face', role: '敵（4方向のいずれかから出現）', note: '' },
    ],
    counters: [
      { id: 'hits', name: '有効射撃数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '目標方向砲台が満タン時にタップ5回',
    failTrigger: '装填不足射撃3回で失敗',
  },
  {
    id: 'arcade-171',
    title: 'USAAF ムスタング',
    brand: 'UPL',
    year: 1990,
    duration: 20,
    difficulty: 'normal',
    concept: '敵機編隊が密集して飛行している。1回のバースト射撃は一直線上にしか当たらない。3機以上が縦1列に並んだ瞬間にタップして一直線撃墜。2機以下の整列では効率が悪く残弾を浪費する。3機以上同時撃墜×3回でクリア。',
    objects: [
      { shape: 'triangle', role: 'P-51ムスタング（下部）', note: '' },
      { shape: 'triangle', role: '敵機×複数（編隊飛行）', note: '縦1列3機以上で光る' },
    ],
    counters: [
      { id: 'multi', name: '3機以上同時撃墜数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '縦1列3機以上整列時にタップ3回',
    failTrigger: '2機以下でタップ3回で失敗',
  },
  {
    id: 'arcade-172',
    title: 'ポップフレーマー',
    brand: 'ジャレコ',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: '炎を吐くキャラクターが移動している。フィールド上に燃料樽が2個配置されており、敵が2つの樽の間を通過した瞬間にタップして炎を噴射すると連鎖爆発で広範囲を一掃できる。敵が1つの樽の前を通る時だけでは連鎖しない。3回連鎖爆発でクリア。',
    objects: [
      { shape: 'face', role: '炎吐きキャラ（中央）', note: '' },
      { shape: 'bomb', role: '燃料樽×2（固定位置）', note: '炎が当たると爆発' },
      { shape: 'face', role: '敵（樽の間を通過）', note: '' },
    ],
    counters: [
      { id: 'chains', name: '連鎖爆発数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '敵が2樽の間にいる瞬間タップ3回',
    failTrigger: '1樽のみ連鎖で3回で失敗',
  },
  {
    id: 'arcade-173',
    title: 'ソルダム',
    brand: 'ジャレコ',
    year: 1992,
    duration: 25,
    difficulty: 'normal',
    concept: '果物のペアが落下してくる。同じ種類の果物が横4つ並ぶと消滅してスコアになる。落下中にタップすると左右が入れ替わる。底に溜まっている果物の列を読んで、落ちてくるペアを適切に回転させて横4つを完成させよ。3回消滅でクリア。',
    objects: [
      { shape: 'circle', role: '果物ペア（落下中）', note: 'タップで左右入替' },
      { shape: 'rect', role: '積み上がった果物（底部）', note: '' },
    ],
    counters: [
      { id: 'clears', name: '横4つ消滅数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'counter clears >= 3',
    failTrigger: '積み上がりが天井に到達したら失敗',
  },
  {
    id: 'arcade-174',
    title: 'パックマン',
    brand: 'ナムコ',
    year: 1980,
    duration: 20,
    difficulty: 'normal',
    concept: 'パックマンがパワーエサのそばで待機している。4体のゴーストが迷路内を動いており、4体全員がパワーエサの近くのエリアに集まった瞬間にタップして食べると、全員まとめて追い掛けられる。1〜3体しか集まっていない時に食べても効果が薄い。4体全員集合でクリア。',
    objects: [
      { shape: 'face', role: 'パックマン（パワーエサ横）', note: '' },
      { shape: 'face', role: 'ゴースト×4（各自移動）', note: 'エリア内で光る' },
      { shape: 'star', role: 'パワーエサ', note: '' },
    ],
    counters: [
      { id: 'quads', name: '4体同時追い掛け数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '4体全員集合の瞬間にタップ3回',
    failTrigger: '3体以下でタップ3回で失敗',
  },
  {
    id: 'arcade-175',
    title: 'ゼビウス',
    brand: 'ナムコ',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: 'ドモグラムが地上から飛翔して空中に移る「遷移アニメーション」の0.5秒間だけ、対空ザッパーと対地ブラスターの両方が同時に当たる。遷移中にタップすると2倍ダメージで即撃墜。地上・空中どちらかの状態では片方の武器しか当たらない。5体遷移撃墜でクリア。',
    objects: [
      { shape: 'face', role: 'ドモグラム（地上→遷移→空中）', note: '遷移中は全身点滅' },
      { shape: 'triangle', role: 'ソルバルウ（上部）', note: '' },
    ],
    counters: [
      { id: 'transit', name: '遷移撃墜数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '遷移アニメ中にタップ5回',
    failTrigger: '地上・空中のどちらかの状態でタップ3回で失敗',
  },
  {
    id: 'arcade-176',
    title: '女三四郎',
    brand: 'タイトー',
    year: 1985,
    duration: 20,
    difficulty: 'hard',
    concept: '柔道の試合。相手が技を仕掛けてくる前に「右腕を引く」か「左腕を引く」かの予備動作が0.4秒見える。予備動作の方向に合わせた返し技（左か右）をタップして切り返しを決めよ。予備動作が終わると本技に入るため間に合わなくなる。3回切り返しでクリア。',
    objects: [
      { shape: 'face', role: '三四郎（左側）', note: '' },
      { shape: 'face', role: '対戦相手（右側・予備動作が光る）', note: '' },
      { shape: 'button', role: '左返し技ボタン', note: '' },
      { shape: 'button', role: '右返し技ボタン', note: '' },
    ],
    counters: [
      { id: 'counters', name: '切り返し成功数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '予備動作の方向に合わせてタップ3回',
    failTrigger: '方向違いまたは遅すぎ3回で失敗',
  },
] as const;
