/**
 * ideas/arcade-2022q4.ts
 * Arcade Archives 2022年10〜12月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2022q4Ideas = [
  {
    id: 'arcade-227',
    title: 'トイポップ',
    brand: 'ナムコ',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: 'ザップガンで敵を撃つとプレゼントボックスに変わる。ボックスを開ける前に中身アイコンが0.8秒だけ表示される——おもちゃのアイコンが出た瞬間にタップして開ける。モンスターアイコンが出た瞬間は絶対に開けてはいけない。5個おもちゃを収集でクリア。',
    objects: [
      { shape: 'rect', role: 'プレゼントボックス（0.8秒間中身アイコン表示）', note: 'おもちゃ=光、モンスター=暗' },
      { shape: 'face', role: '主人公（左端）', note: '' },
    ],
    counters: [
      { id: 'toys', name: 'おもちゃ収集数', target: 5, note: '5個でクリア' },
    ],
    winTrigger: 'おもちゃアイコン中にタップ5回',
    failTrigger: 'モンスターアイコン中にタップ3回で失敗',
  },
  {
    id: 'arcade-228',
    title: '闘姫伝承 ANGEL EYES',
    brand: 'テクモ',
    year: 1996,
    duration: 20,
    difficulty: 'hard',
    concept: '相手が投げを仕掛けてくる前に腕の回転方向が見える——時計回りは右投げ、反時計回りは左投げ。0.3秒以内に逆方向をタップして投げ抜け。同方向にタップすると投げられる。素早く回転を読んで逃げ方向を選べ。5回投げ抜けでクリア。',
    objects: [
      { shape: 'face', role: '対戦相手（腕の回転方向アニメ）', note: '時計=右、反時計=左' },
      { shape: 'face', role: '自キャラ（左側）', note: '' },
      { shape: 'button', role: '左抜けボタン', note: '' },
      { shape: 'button', role: '右抜けボタン', note: '' },
    ],
    counters: [
      { id: 'escapes', name: '投げ抜け数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '回転方向と逆をタップ5回',
    failTrigger: '方向ミス投げ抜け3回で失敗',
  },
  {
    id: 'arcade-229',
    title: 'オーダイン',
    brand: 'ナムコ',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '空中ショップが飛行してくる。ショップには複数のアイテムが流れており、現在の武器の弱点を補う「最適アイテム」が1つだけある。最適アイテムが表示された瞬間にタップして購入——流れ過ぎると次のショップまで待つ羽目になる。3回最適購入でクリア。',
    objects: [
      { shape: 'rect', role: 'ショップ（飛行）', note: 'アイテムがスクロール表示' },
      { shape: 'star', role: '最適アイテム（光って強調）', note: '' },
      { shape: 'triangle', role: '自機（下部）', note: '現在武器の弱点表示' },
    ],
    counters: [
      { id: 'optimal', name: '最適購入数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '最適アイテムが表示された瞬間タップ3回',
    failTrigger: '最適以外を購入3回で失敗',
  },
  {
    id: 'arcade-230',
    title: '悪戯天使',
    brand: 'ニチブツ',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: '悪戯天使がフィールド上の物体をボールに変えて転がす。ボールは転がった先の敵に当たると撃退できる。3体以上の敵が物体の真下エリアに集まった瞬間に物体をタップしてボールに変換——そのまま転がって3体まとめて撃退。3体未満の時は変換しない。3回3体以上撃退でクリア。',
    objects: [
      { shape: 'rect', role: '変換対象物体（フィールド上）', note: 'タップでボールになる' },
      { shape: 'circle', role: 'ボール（転がる）', note: '' },
      { shape: 'face', role: '敵×複数（集まる）', note: '3体以上で光る' },
    ],
    counters: [
      { id: 'sweeps', name: '3体以上まとめ撃退数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '物体の下に3体以上の瞬間タップ3回',
    failTrigger: '2体以下でタップ3回で失敗',
  },
  {
    id: 'arcade-231',
    title: 'バラデューク',
    brand: 'ナムコ',
    year: 1985,
    duration: 20,
    difficulty: 'hard',
    concept: 'バルーク（プレイヤー）が宇宙空間を漂うエイリアン生命体に接近する。生命体は呼吸するように大きさが収縮と膨張を繰り返す——最も膨張した（最大サイズ）瞬間だけが点滅してタップ有効。収縮中に撃ってもエネルギーが霧散する。5体撃破でクリア。',
    objects: [
      { shape: 'ellipse', role: 'エイリアン生命体（呼吸で大小変化）', note: '最大時に点滅' },
      { shape: 'face', role: 'バルーク（中央）', note: '' },
      { shape: 'button', role: 'ショットボタン', note: '' },
    ],
    counters: [
      { id: 'hit', name: '撃破数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '最大サイズ点滅中にタップ5回',
    failTrigger: '収縮中タップ3回で失敗',
  },
  {
    id: 'arcade-232',
    title: 'メタルブラック',
    brand: 'タイトー',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: 'ニューアローン粒子が画面を流れている。粒子は単独か密集かでバラツキがある——密集ピーク（一か所に最も固まった瞬間）にタップして吸収するとビームが大きく充填される。疎らな状態で吸収しても効果が薄い。5回密集ピーク吸収でクリア。',
    objects: [
      { shape: 'circle', role: 'ニューアローン粒子（流れる）', note: '密集ピーク時に光る' },
      { shape: 'triangle', role: 'メタルブラック号（中央）', note: '' },
      { shape: 'rect', role: 'ビーム充填ゲージ', note: '' },
    ],
    counters: [
      { id: 'peak', name: '密集ピーク吸収数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '粒子密集ピークの瞬間タップ5回',
    failTrigger: '疎ら状態での吸収3回で失敗',
  },
  {
    id: 'arcade-233',
    title: 'ギャラクシアン',
    brand: 'ナムコ',
    year: 1979,
    duration: 20,
    difficulty: 'normal',
    concept: 'ギャラクシアンの旗艦が護衛2機を従えて急降下してくる。護衛を先に撃墜してから旗艦単独になった瞬間にタップして撃つ——旗艦が護衛付きの状態では撃っても護衛が弾を受けてしまう。護衛2機を各1タップで撃墜してから旗艦タップ。3回旗艦撃墜でクリア。',
    objects: [
      { shape: 'face', role: 'ギャラクシアン旗艦（中央）', note: '護衛なしになると光る' },
      { shape: 'triangle', role: '護衛機×2（旗艦の左右）', note: '' },
      { shape: 'triangle', role: '自機（下部）', note: '' },
    ],
    counters: [
      { id: 'flagships', name: '旗艦撃墜数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '護衛2機撃墜後→旗艦タップ×3回',
    failTrigger: '護衛付き旗艦をタップ3回で失敗',
  },
  {
    id: 'arcade-234',
    title: 'テトリス ザ・グランドマスター',
    brand: 'アリカ',
    year: 1998,
    duration: 20,
    difficulty: 'hard',
    concept: 'ピースが超高速で落下する前に0.5秒だけ「次のピース」が上部に表示される。その0.5秒でピースの回転方向を判断し、底の隙間と一致する向きにタップして回転させよ。落下が始まると修正の時間はない。5回ピッタリはめでクリア。',
    objects: [
      { shape: 'rect', role: 'テトロミノ（0.5秒のプレビュー後に超高速落下）', note: '' },
      { shape: 'rect', role: '積み上がりブロック（隙間の形が表示）', note: '' },
      { shape: 'button', role: '回転ボタン（左回転）', note: '' },
      { shape: 'button', role: '回転ボタン（右回転）', note: '' },
    ],
    counters: [
      { id: 'perfect', name: 'ピッタリはめ数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '正しい向きに回転してから落下5回',
    failTrigger: '向き間違いで落下3回で失敗',
  },
  {
    id: 'arcade-235',
    title: 'パックマニア',
    brand: 'ナムコ',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: 'パックマニアはゴーストをジャンプで飛び越えられる。パワーエサへの直線上に1体のゴーストが塞いでいる。そのゴーストが真下に来た瞬間にタップしてジャンプし、ゴーストを飛び越えてパワーエサへ直行せよ。2体以上が並んでいるときはジャンプしてはいけない。5回ジャンプ突破でクリア。',
    objects: [
      { shape: 'face', role: 'パックマニア（ジャンプ可能）', note: '' },
      { shape: 'face', role: 'ゴースト（1体が直線上）', note: '1体のみ時に光る' },
      { shape: 'star', role: 'パワーエサ（直線の先）', note: '' },
    ],
    counters: [
      { id: 'jumps', name: 'ジャンプ突破数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '1体だけ直線上の瞬間タップ5回',
    failTrigger: '2体以上でジャンプ3回で失敗',
  },
  {
    id: 'arcade-236',
    title: 'マーベルランド',
    brand: 'ナムコ',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: 'ジェットコースターがループ手前を走っている。ループを安全に回るには手前のブースト台でタップしてスピードを上げる必要がある。ブースト台を通り過ぎてからタップしても間に合わない——台の真上を通過した瞬間にタップしてブースト発動。3回ループ完走でクリア。',
    objects: [
      { shape: 'rect', role: 'ジェットコースター（走行）', note: '' },
      { shape: 'diamond', role: 'ブースト台（コース上）', note: '真上通過時に光る' },
      { shape: 'circle', role: 'ループ（前方）', note: '' },
    ],
    counters: [
      { id: 'loops', name: 'ループ完走数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'ブースト台真上通過時タップ→ループ完走×3回',
    failTrigger: 'ブースト台を通り過ぎてタップ3回で失敗',
  },
  {
    id: 'arcade-237',
    title: 'メタルホーク',
    brand: 'ナムコ',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: 'ヘリコプターの照準が戦場上を移動している。ミサイルは最大3目標同時にロックオンでき、照準が3つの目標の上を通過するたびにロックがかかる。3目標全てにロックした状態でタップして一斉発射——2目標以下での発射は弾を無駄遣いする。3回3目標同時発射でクリア。',
    objects: [
      { shape: 'circle', role: '照準（戦場上を移動）', note: 'ロック済み目標に印' },
      { shape: 'rect', role: '地上目標×複数', note: '照準が乗るとロック' },
      { shape: 'triangle', role: 'メタルホーク（上部）', note: '' },
    ],
    counters: [
      { id: 'salvos', name: '3目標同時発射数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3目標ロック完了後タップ3回',
    failTrigger: '2目標以下で発射3回で失敗',
  },
] as const;
