/**
 * ideas/arcade-2024q2.ts
 * Arcade Archives 2024年4〜6月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2024q2Ideas = [
  {
    id: 'arcade-302',
    title: 'エクスバニア',
    brand: 'ナムコ',
    year: 1992,
    duration: 20,
    difficulty: 'normal',
    concept: '敵群がV字フォーメーションで飛来する。フォーメーションが縦長から横長へ変形する瞬間だけ、旗艦が中央に露出して点滅する。変形完了と同時に旗艦が再び護衛に守られる——変形中の点滅タイミング（変形50%完了時）にタップして旗艦を撃墜。5回撃墜でクリア。',
    objects: [
      { shape: 'star', role: 'V字フォーメーション旗艦（中央）', note: '変形中に点滅' },
      { shape: 'triangle', role: '護衛機×複数', note: '' },
      { shape: 'triangle', role: '自機（下部）', note: '' },
    ],
    counters: [
      { id: 'flagships', name: '旗艦撃墜数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'フォーメーション変形中点滅タイミングにタップ5回',
    failTrigger: '変形前後の非露出時にタップ3回で失敗',
  },
  {
    id: 'arcade-303',
    title: 'VS.スーパーゼビウス ガンプの謎',
    brand: 'ナムコ',
    year: 1986,
    duration: 20,
    difficulty: 'hard',
    concept: 'ガンプ（地上要塞）の表面に5つの発振器が並んでいる。発振器は個別に点滅しているが、5つ全てが同時に停止する瞬間が0.4秒だけある——その全停止の瞬間にブラスターをタップするとガンプが内部崩壊する。1つでも動いている間はエネルギーを跳ね返される。3回撃破でクリア。',
    objects: [
      { shape: 'rect', role: 'ガンプ（地上要塞）', note: '' },
      { shape: 'circle', role: '発振器×5（表面に並ぶ）', note: '全停止時に暗くなる' },
      { shape: 'triangle', role: 'ソルバルウ（上部）', note: '' },
    ],
    counters: [
      { id: 'destructions', name: 'ガンプ破壊数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '5発振器全停止の瞬間タップ3回',
    failTrigger: '1つでも動いている間タップ3回で失敗',
  },
  {
    id: 'arcade-304',
    title: 'エメラルディア',
    brand: 'ナムコ',
    year: 1993,
    duration: 20,
    difficulty: 'normal',
    concept: 'エメラルドの宝石が積み上がっている。3個の同色宝石がまさに揃おうとしている——「揃う0.3秒前」のタイミングでタップ予約すると「先読み消去」が発動し、揃った瞬間に特殊エフェクトで高得点消去が発生する。タイミングが遅れると通常消去になる。5回先読み消去でクリア。',
    objects: [
      { shape: 'diamond', role: '宝石ブロック（積み上がる）', note: '揃う直前に輝く' },
      { shape: 'rect', role: '積み上がりフィールド', note: '' },
    ],
    counters: [
      { id: 'predictions', name: '先読み消去数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '揃う0.3秒前にタップ5回',
    failTrigger: '遅れて通常消去3回で失敗',
  },
  {
    id: 'arcade-305',
    title: 'ニューマンアスレチックス',
    brand: 'ナムコ',
    year: 1993,
    duration: 20,
    difficulty: 'normal',
    concept: '走り幅跳びの選手が踏切板に向かって走ってくる。踏切板の前後5cm相当の「最適踏切ゾーン」が光っている——選手が最適踏切ゾーン内を通過した瞬間にタップしてジャンプ命令。ゾーンを外れると跳躍距離が大幅に短くなる。5回最適踏切でクリア。',
    objects: [
      { shape: 'face', role: '走者（走ってくる）', note: '' },
      { shape: 'rect', role: '踏切板（光る最適ゾーン付き）', note: 'ゾーン内で選手が光る' },
    ],
    counters: [
      { id: 'jumps', name: '最適踏切数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '最適踏切ゾーン内タップ5回',
    failTrigger: 'ゾーン外タップ3回で失敗',
  },
  {
    id: 'arcade-306',
    title: 'ラスタンサーガ',
    brand: 'タイトー',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '魔法の剣のエネルギーゲージが時間とともに充填される。ゲージが90〜100%の「充填ピーク帯」に入った瞬間に剣を振り下ろすと魔力全解放の強力斬りが発動——それ以外の充填率では普通の攻撃になる。ピーク帯は上昇後すぐに100%を超えて下降するので素早い判断が必要。5回魔力全解放斬りでクリア。',
    objects: [
      { shape: 'rect', role: '剣エネルギーゲージ（充填中）', note: '90〜100%帯が金色' },
      { shape: 'face', role: 'ラスタン（中央）', note: '' },
      { shape: 'face', role: '魔物（前方）', note: '' },
    ],
    counters: [
      { id: 'slashes', name: '魔力全解放斬り数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'ゲージ90〜100%の瞬間タップ5回',
    failTrigger: 'ピーク外で振り下ろし3回で失敗',
  },
  {
    id: 'arcade-307',
    title: 'ツタンカーム',
    brand: 'KONAMI',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: '部屋の扉が開くタイミングが迫っている。扉が完全に開いた状態（最大開口）から1秒以内に突入しないと再び閉まる。扉が開き始めた瞬間にタップして走り出し——「開き始め」から「完全開口」の間にある最速突入チャンスを使う。5回脱出でクリア。',
    objects: [
      { shape: 'rect', role: '扉（開閉する）', note: '最大開口時に光る' },
      { shape: 'face', role: 'ツタンカーム（部屋の奥）', note: '' },
    ],
    counters: [
      { id: 'escapes', name: '脱出数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '扉が最大開口になってから1秒以内にタップ5回',
    failTrigger: '開き始め前にタップ3回で失敗',
  },
  {
    id: 'arcade-308',
    title: 'F/A',
    brand: 'ナムコ',
    year: 1992,
    duration: 20,
    difficulty: 'normal',
    concept: 'F/Aは超低空飛行中に地面誘導ミサイルを発射できる。高度インジケーターが「スキミングゾーン（最低高度帯）」を示している間だけミサイルが地面を這って有効になる——高度が上がると誘導機能が失われる。スキミングゾーン中にタップして発射。5回誘導ミサイル命中でクリア。',
    objects: [
      { shape: 'triangle', role: 'F/A機（低空飛行）', note: '' },
      { shape: 'rect', role: '高度インジケーター', note: 'スキミングゾーンが青色' },
      { shape: 'rect', role: '地上目標', note: '' },
    ],
    counters: [
      { id: 'hits', name: '誘導ミサイル命中数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'スキミングゾーン中タップ5回',
    failTrigger: 'ゾーン外発射3回で失敗',
  },
  {
    id: 'arcade-309',
    title: '超時迷宮レジオン',
    brand: 'ニチブツ',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '時空裂け目が画面上を移動している。裂け目が「開いている」間（白く光る）に弾を通過させると弾が3方向に増幅する——裂け目が自機と敵の中間に来た瞬間（弾の軌道上）にタップして発射。裂け目が閉じると増幅なしの単発弾になる。5回増幅発射でクリア。',
    objects: [
      { shape: 'ellipse', role: '時空裂け目（画面上を移動）', note: '開いている間は白く光る' },
      { shape: 'face', role: '敵機（上部）', note: '' },
      { shape: 'triangle', role: 'レジオン自機（下部）', note: '' },
    ],
    counters: [
      { id: 'amplified', name: '増幅発射数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '裂け目が軌道上かつ開いている瞬間タップ5回',
    failTrigger: '裂け目閉鎖時に発射3回で失敗',
  },
  {
    id: 'arcade-310',
    title: 'キューブリック',
    brand: 'KONAMI',
    year: 1989,
    duration: 20,
    difficulty: 'hard',
    concept: '転がるキューブが坂道で重力加速する。速度インジケーターが「ピーク値」に達した瞬間に急ブレーキをタップして方向転換——ピーク前にブレーキするとスピードが足りず曲がりきれない。ピーク後は壁に激突する。ピークの0.3秒のウィンドウを正確にとらえる。5回ピークブレーキでクリア。',
    objects: [
      { shape: 'rect', role: 'キューブ（転がる）', note: '' },
      { shape: 'rect', role: '速度インジケーター', note: 'ピーク時に金色フラッシュ' },
      { shape: 'rect', role: '坂道・壁', note: '' },
    ],
    counters: [
      { id: 'brakes', name: 'ピークブレーキ数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '速度ピークの瞬間タップ5回',
    failTrigger: 'ピーク外ブレーキ3回で失敗',
  },
  {
    id: 'arcade-311',
    title: 'ワイピング',
    brand: 'ニチブツ',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: 'モップが往復しながら床の汚れを拭いている。モップが往路の端（折り返し点）に達した瞬間にタップすると「重ね拭き」が発動——往路の最後の0.2秒で汚れ除去率が倍になる特殊拭きができる。折り返し後にタップすると復路の普通拭きになってしまう。5回重ね拭きでクリア。',
    objects: [
      { shape: 'rect', role: 'モップ（往復する）', note: '往路端到達時に光る' },
      { shape: 'rect', role: '床の汚れ（徐々に消える）', note: '' },
    ],
    counters: [
      { id: 'doublewipes', name: '重ね拭き数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'モップ往路端到達の瞬間タップ5回',
    failTrigger: '折り返し後タップ3回で失敗',
  },
  {
    id: 'arcade-312',
    title: 'VS.スターラスター',
    brand: 'ナムコ',
    year: 1985,
    duration: 20,
    difficulty: 'hard',
    concept: '敵艦隊が星間の「トンネルゾーン（狭い航路）」を一列縦隊で通過してくる。先頭艦を撃墜すると後続が玉突き衝突して連鎖破壊が起きる——先頭艦がトンネルに完全に入り込んだ瞬間（後退不可能になった瞬間）にタップして撃墜。入口前に撃つと先頭が分岐して逃げる。3回連鎖破壊でクリア。',
    objects: [
      { shape: 'triangle', role: '先頭艦（先頭を走る）', note: 'トンネル内で光る' },
      { shape: 'triangle', role: '後続艦×複数（一列縦隊）', note: '' },
      { shape: 'rect', role: 'トンネルゾーン（狭い航路）', note: '' },
    ],
    counters: [
      { id: 'chains', name: '連鎖破壊数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '先頭がトンネル内に入り込んだ瞬間タップ3回',
    failTrigger: 'トンネル外で撃墜3回で失敗',
  },
  {
    id: 'arcade-313',
    title: 'ラスタンサーガII',
    brand: 'タイトー',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '鍛冶神殿の炉が温度を上昇させている。炎の色が青→赤→白と変化し、白炎（最高温）の時にタップして剣を浸けると完全修復できる——青炎や赤炎では不完全修復で耐久度が半分しか回復しない。白炎は1秒しか続かない。3回完全修復でクリア。',
    objects: [
      { shape: 'triangle', role: '炎（青→赤→白に変化）', note: '白炎時が最高温' },
      { shape: 'rect', role: '炉（神殿内）', note: '' },
      { shape: 'diamond', role: '剣（修復待ち）', note: '完全修復後に光る' },
    ],
    counters: [
      { id: 'repairs', name: '完全修復数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '白炎の瞬間タップ3回',
    failTrigger: '青炎・赤炎でタップ3回で失敗',
  },
  {
    id: 'arcade-314',
    title: '特殊部隊ジャッカル',
    brand: 'KONAMI',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: '収容所の外壁に複数の「弱点マーカー」が点在し、0.5秒周期で別の場所に移動する。弱点マーカーが「脱出路直上」の位置に来た瞬間にタップして爆破——脱出路が開通して捕虜を解放できる。他の位置でも爆破はできるが脱出路が残ったままになる。3回収容所解放でクリア。',
    objects: [
      { shape: 'star', role: '弱点マーカー（外壁上を移動）', note: '脱出路真上に来ると光る' },
      { shape: 'rect', role: '外壁（収容所）', note: '' },
      { shape: 'rect', role: 'ジープ・ジャッカル（下部）', note: '' },
    ],
    counters: [
      { id: 'rescues', name: '収容所解放数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '弱点が脱出路直上に来た瞬間タップ3回',
    failTrigger: '弱点ズレ位置で爆破3回で失敗',
  },
] as const;
