/**
 * ideas/arcade-2022q3.ts
 * Arcade Archives 2022年7〜9月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2022q3Ideas = [
  {
    id: 'arcade-214',
    title: 'ラビオレプス',
    brand: 'ビデオシステム',
    year: 1987,
    duration: 20,
    difficulty: 'hard',
    concept: 'ラビオ（ウサギ船）は前方から来る弾を「丸飲み」できる。弾がラビオの口の直前（0.2秒以内）に来た瞬間にタップして食らいつく。早すぎると口が開いたまま別の弾に無防備、遅すぎると被弾。絶妙なタイミングで5弾を食べてクリア。',
    objects: [
      { shape: 'face', role: 'ラビオ（ウサギ船・中央）', note: '口が開閉' },
      { shape: 'diamond', role: '敵弾（前方から飛来）', note: '' },
    ],
    counters: [
      { id: 'eaten', name: '弾を食べた数', target: 5, note: '5弾でクリア' },
    ],
    winTrigger: '弾が口の直前0.2秒でタップ5回',
    failTrigger: '被弾3回で失敗',
  },
  {
    id: 'arcade-215',
    title: 'ドラゴンセイバー',
    brand: 'ナムコ',
    year: 1990,
    duration: 20,
    difficulty: 'normal',
    concept: '2頭のドラゴン（プレイヤーとNPC）が並走している。NPCドラゴンがブレスを吐いた瞬間から0.3秒以内に自分もブレスをタップすると「合体ブレス」になり威力2倍。0.3秒を過ぎると別々のブレスになって効果が薄い。NPCの吐き出しを見てすぐ反応せよ。5回合体ブレスでクリア。',
    objects: [
      { shape: 'face', role: 'プレイヤードラゴン（左）', note: '' },
      { shape: 'face', role: 'NPCドラゴン（右・ブレス先行）', note: 'ブレスで光る' },
      { shape: 'button', role: 'ブレスボタン', note: '0.3秒以内で合体' },
    ],
    counters: [
      { id: 'combined', name: '合体ブレス数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'NPCブレスから0.3秒以内タップ5回',
    failTrigger: '0.3秒過ぎてタップ3回で失敗',
  },
  {
    id: 'arcade-216',
    title: 'ちゃっくんぽっぷ',
    brand: 'タイトー',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: 'チャックが爆弾を廊下に仕掛ける。2秒後に爆発する爆弾の爆風が届くのは設置した廊下区画だけ。ミータ（敵）が目標区画に入った瞬間にタップして爆弾を仕掛け、2秒後の爆発でミータが区画内にいれば撃破。区画を通り過ぎた後に仕掛けても間に合わない。5体撃破でクリア。',
    objects: [
      { shape: 'face', role: 'チャック（左端）', note: '' },
      { shape: 'bomb', role: '爆弾（2秒後に爆発）', note: '' },
      { shape: 'face', role: 'ミータ（廊下を歩く）', note: '区画内で光る' },
      { shape: 'rect', role: '廊下区画（爆風範囲）', note: '' },
    ],
    counters: [
      { id: 'blasted', name: '爆弾撃破数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'ミータが区画内の瞬間タップ5回',
    failTrigger: 'ミータ不在区画に仕掛け3回で失敗',
  },
  {
    id: 'arcade-217',
    title: 'ローラージャマー',
    brand: 'ニチブツ',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: 'ローラースケーターが複数の選手の中を縫って走る。2人の選手の間隔が広がった「すり抜けギャップ」の瞬間にタップしてスプリント突破。ギャップが開いてから1秒以内にタップしないとまた狭まる。5回突破でクリア。',
    objects: [
      { shape: 'face', role: '自選手（後方）', note: '' },
      { shape: 'face', role: '前方選手×2（間隔が変化）', note: 'ギャップ最大時に光る' },
      { shape: 'button', role: 'スプリントボタン', note: '' },
    ],
    counters: [
      { id: 'passes', name: 'すり抜け突破数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'ギャップ最大の瞬間タップ5回',
    failTrigger: 'ギャップ不十分でタップ3回で失敗',
  },
  {
    id: 'arcade-218',
    title: 'ディグダグ',
    brand: 'ナムコ',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: '大岩がプーカやフライガーの真上にある。岩の真下に敵が来た瞬間にタップして岩を落下させれば圧殺できる。敵が複数いるとき、2体同時に岩の下に収まる瞬間を狙ってタップすれば一石二鳥。2体同時圧殺×3回でクリア。',
    objects: [
      { shape: 'circle', role: '大岩（天井付近）', note: 'タップで落下' },
      { shape: 'face', role: 'プーカ（移動）', note: '' },
      { shape: 'triangle', role: 'フライガー（移動）', note: '' },
    ],
    counters: [
      { id: 'doubles', name: '2体同時圧殺数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '岩の下に2体同時の瞬間タップ3回',
    failTrigger: '1体だけ圧殺3回で失敗',
  },
  {
    id: 'arcade-219',
    title: 'ガンフロンティア',
    brand: 'タイトー',
    year: 1990,
    duration: 20,
    difficulty: 'hard',
    concept: '無法者を近距離で撃つと金貨が飛び散って自機の周囲に落ちる。通常距離では金貨が遠くに散って回収できない。金貨を収集するには「至近距離ゾーン」に入ってから撃つ必要がある。危険を冒して至近距離に踏み込み、そこでタップ。5回至近距離撃墜でクリア。',
    objects: [
      { shape: 'triangle', role: '自機（中央）', note: '' },
      { shape: 'face', role: '無法者（右側）', note: '' },
      { shape: 'rect', role: '至近距離ゾーン（自機周囲）', note: 'ゾーン内で光る' },
      { shape: 'coin', role: '金貨（至近撃墜で散布）', note: '' },
    ],
    counters: [
      { id: 'close', name: '至近距離撃墜数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'ゾーン内でタップ5回',
    failTrigger: '至近距離ゾーン外で撃墜3回で失敗',
  },
  {
    id: 'arcade-220',
    title: 'メトロクロス',
    brand: 'ナムコ',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: 'スケートボーダーが走路を疾走している。スピードブースト缶を蹴ると加速するが、直後にある穴を飛び越えなければならない。缶をタップで蹴り→飛び越え、の2段階タイミングを連続で決めよ。缶をけったのに穴でジャンプし損ねると落下。5セット成功でクリア。',
    objects: [
      { shape: 'circle', role: '缶（走路上）', note: 'タップで蹴って加速' },
      { shape: 'rect', role: '穴（缶の直後）', note: '加速後にジャンプ必要' },
      { shape: 'face', role: 'スケートボーダー（走行）', note: '' },
    ],
    counters: [
      { id: 'sets', name: '缶蹴り+飛び越えセット数', target: 5, note: '5セットでクリア' },
    ],
    winTrigger: '缶タップ→穴タップを5セット完遂',
    failTrigger: '缶後の穴で落下3回で失敗',
  },
  {
    id: 'arcade-221',
    title: 'スーパーバレーボール',
    brand: 'ビデオシステム',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: 'セッターがトスを上げる。トスの弧は毎回速度が異なる（クイック・スロー）。スパイカーはトスの頂点でジャンプして叩かなければならない——頂点の位置にボールが来た瞬間にタップしてスパイク。早いとまだ上昇中、遅いと落ち始めているため空振り。3本スパイクでクリア。',
    objects: [
      { shape: 'circle', role: 'バレーボール（トス弧）', note: '頂点で光る' },
      { shape: 'face', role: 'スパイカー（助走中）', note: '' },
      { shape: 'rect', role: 'ネット', note: '' },
    ],
    counters: [
      { id: 'spikes', name: 'スパイク成功数', target: 3, note: '3本でクリア' },
    ],
    winTrigger: 'ボールが頂点の瞬間タップ3回',
    failTrigger: '空振り3回で失敗',
  },
  {
    id: 'arcade-222',
    title: 'パック&パル',
    brand: 'ナムコ',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: 'パックの友達ミルが迷路内でアイテムを集めてパックに届けに来る。ゴーストがミルの経路上を移動している。ミルの進路とゴーストが重ならない「安全タイミング」を見計らってタップしてミルを動かせ。ゴーストが経路を塞いでいる間は待機。3回安全届け出でクリア。',
    objects: [
      { shape: 'face', role: 'ミル（パックの友達）', note: '' },
      { shape: 'face', role: 'パックマン（右端待機）', note: '' },
      { shape: 'face', role: 'ゴースト（経路上を巡回）', note: '経路塞ぎ時に赤' },
      { shape: 'star', role: 'アイテム（ミルが持つ）', note: '' },
    ],
    counters: [
      { id: 'deliveries', name: '安全届け出数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'ゴーストが経路から外れた瞬間タップ3回',
    failTrigger: 'ゴーストと衝突3回で失敗',
  },
  {
    id: 'arcade-223',
    title: 'チャンピオンレスラー',
    brand: 'タイトー',
    year: 1989,
    duration: 20,
    difficulty: 'hard',
    concept: '投げられて空中に浮いた瞬間、着地前の0.5秒間だけカウンターフォールが発動できる。カウンターを成功させると体勢を立て直して相手を即座に掴み返せる。投げられた瞬間は反応できないが、頂点を過ぎて下降し始めた瞬間にタップがベストタイミング。3回カウンターでクリア。',
    objects: [
      { shape: 'face', role: 'レスラー（空中飛行中）', note: '下降開始時に光る' },
      { shape: 'face', role: '対戦相手（リング上）', note: '' },
      { shape: 'button', role: 'カウンターボタン', note: '下降中のみ有効' },
    ],
    counters: [
      { id: 'counters', name: 'カウンター成功数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '下降開始後0.5秒以内タップ3回',
    failTrigger: '上昇中または着地後タップ3回で失敗',
  },
  {
    id: 'arcade-224',
    title: 'ロンパーズ',
    brand: 'ナムコ',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: 'キャラクターが箱を押して敵を壁に追い込む。箱は押した方向にしか動かない——敵が箱と壁の間に挟まる位置関係のときだけ有効。「箱→敵→壁」が一直線に並んだ瞬間にタップして押す。箱と壁の間に敵がいない状態で押しても無駄。5体封殺でクリア。',
    objects: [
      { shape: 'rect', role: '箱（押せる）', note: '' },
      { shape: 'face', role: '敵（移動）', note: '挟まれる位置で光る' },
      { shape: 'rect', role: '壁（固定）', note: '' },
      { shape: 'face', role: 'キャラクター（主人公）', note: '' },
    ],
    counters: [
      { id: 'pinned', name: '封殺数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '箱→敵→壁一直線の瞬間タップ5回',
    failTrigger: '敵がいない方向に押す3回で失敗',
  },
  {
    id: 'arcade-225',
    title: 'イシターの復活',
    brand: 'ナムコ',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: 'キが魔法陣を展開し始めると鬼神が2秒間弱体化する。弱体化の瞬間だけギルガメスの剣が通る。キが魔法陣を起動し始めたらタップしてギルガメスを動かせ——キの魔法が完成する前に攻撃すると弱体化していないため弾かれる。5体コンビ撃破でクリア。',
    objects: [
      { shape: 'face', role: 'キ（魔法陣展開中）', note: '展開完了で魔法陣が光る' },
      { shape: 'face', role: 'ギルガメス（右側）', note: '' },
      { shape: 'face', role: '鬼神（弱体化中に点滅）', note: '' },
    ],
    counters: [
      { id: 'combos', name: 'コンビ撃破数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'キ魔法完成後にタップ5回',
    failTrigger: '魔法完成前タップ（弾かれ）3回で失敗',
  },
  {
    id: 'arcade-226',
    title: 'アサルト',
    brand: 'ナムコ',
    year: 1988,
    duration: 20,
    difficulty: 'hard',
    concept: '戦車の砲塔が敵を追いながらゆっくり旋回している。複数の敵が散らばっているが、時々3体が砲塔の射線上に縦一列に並ぶ瞬間がある。その瞬間にタップして貫通弾を発射し一列全滅。2体以下では貫通が活きない。3回一列全滅でクリア。',
    objects: [
      { shape: 'rect', role: '戦車（砲塔旋回）', note: '' },
      { shape: 'face', role: '敵×複数（散らばり移動）', note: '3体縦一列時に光る' },
      { shape: 'button', role: '貫通弾ボタン', note: '' },
    ],
    counters: [
      { id: 'lines', name: '縦一列全滅数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3体縦一列の瞬間タップ3回',
    failTrigger: '2体以下で貫通弾3回で失敗',
  },
] as const;
