/**
 * ideas/arcade-2022q1.ts
 * Arcade Archives 2022年1〜3月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2022q1Ideas = [
  {
    id: 'arcade-189',
    title: 'スーパーパックマン',
    brand: 'ナムコ',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: 'スーパーフルーツを食べるとパックマンが巨大化し、鍵のかかったドアを突き破れる状態が3秒続く。3秒間に連続する3枚のドアをタップして全て突破せよ。4枚目以降や巨大化が切れた後にタップしても壁に弾かれる。3回の連続3ドア突破でクリア。',
    objects: [
      { shape: 'face', role: 'スーパーパックマン（巨大化中）', note: '3秒タイマー表示' },
      { shape: 'rect', role: '鍵付きドア×3（連続）', note: 'タップで突破' },
      { shape: 'star', role: 'スーパーフルーツ', note: '食べると巨大化' },
    ],
    counters: [
      { id: 'breakthroughs', name: '連続3ドア突破数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '巨大化中に3ドア連続突破×3回',
    failTrigger: '巨大化切れ後にタップ3回で失敗',
  },
  {
    id: 'arcade-190',
    title: 'ガンネイル',
    brand: 'NMK',
    year: 1993,
    duration: 20,
    difficulty: 'hard',
    concept: 'ガンネイルはネイル（釘）を拡散発射する。敵シールドは3本のネイルが同一点に集中したときだけ貫通できる。散弾の拡散角度を最小（集中）に絞り、シールドの中心に重なった瞬間にタップして貫通射撃。拡散角が広いと分散してしまい弾かれる。3機貫通でクリア。',
    objects: [
      { shape: 'triangle', role: 'ガンネイル（下部）', note: '拡散角インジケーター付き' },
      { shape: 'diamond', role: 'ネイル×3（扇状拡散）', note: '集中時に1点で光る' },
      { shape: 'rect', role: '敵シールド（中心に貫通点）', note: '' },
    ],
    counters: [
      { id: 'pierced', name: 'シールド貫通数', target: 3, note: '3機でクリア' },
    ],
    winTrigger: '拡散角最小+シールド中心でタップ3回',
    failTrigger: '拡散状態で貫通試み3回で失敗',
  },
  {
    id: 'arcade-191',
    title: 'ホッピングマッピー',
    brand: 'ナムコ',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: 'マッピーがポゴスティックで縦に跳ね続けている。各フロアのニャームコは左右に移動しており、マッピーの跳躍頂点がちょうどそのニャームコの真上に来た瞬間にタップして踏みつぶせ。フロアが変わるたびにニャームコの位置も変わる。5体踏み潰しでクリア。',
    objects: [
      { shape: 'face', role: 'マッピー（ポゴスティックで上下）', note: '頂点で光る' },
      { shape: 'face', role: 'ニャームコ（各フロアを移動）', note: '' },
    ],
    counters: [
      { id: 'stomped', name: '踏み潰し数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '頂点でニャームコ真上のときにタップ5回',
    failTrigger: '空振り3回で失敗',
  },
  {
    id: 'arcade-192',
    title: 'ピストル大名の冒険',
    brand: 'ナムコ',
    year: 1990,
    duration: 20,
    difficulty: 'normal',
    concept: '大名が頭から大砲弾を発射する。弾は壁で1回跳ね返る。敵が直射の届かない壁の陰に隠れている——壁の跳ね返り後の軌道（点線）が敵と重なるタイミングでタップして発射。跳ね返りの角度は壁の位置で変わるため、毎回跳ね返り先を計算せよ。5体撃破でクリア。',
    objects: [
      { shape: 'face', role: '大名（左端）', note: '' },
      { shape: 'circle', role: '大砲弾（壁で跳ね返る）', note: '' },
      { shape: 'diamond', role: '跳ね返り後軌道（点線）', note: '敵に重なると光る' },
      { shape: 'face', role: '敵（壁の陰）', note: '' },
    ],
    counters: [
      { id: 'rico', name: 'リコシェット撃破数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'counter rico >= 5',
    failTrigger: '弾が外れ3回で失敗',
  },
  {
    id: 'arcade-193',
    title: 'ニューラリーX',
    brand: 'ナムコ',
    year: 1981,
    duration: 20,
    difficulty: 'normal',
    concept: 'ラッキーフラッグを5本連続収集するとボーナスシグナルが点灯する。シグナルが点灯した直後の0.5秒以内にタップすると得点倍率が2倍になる。5本目のフラッグを取ったときに指を離さず素早く反応せよ。点灯を見逃すと倍率が消える。3回ボーナス倍率でクリア。',
    objects: [
      { shape: 'star', role: 'ラッキーフラッグ×5（コース上）', note: '' },
      { shape: 'triangle', role: '自車（走行）', note: '' },
      { shape: 'rect', role: 'ボーナスシグナル（点灯0.5秒）', note: '' },
    ],
    counters: [
      { id: 'bonus', name: 'ボーナス倍率獲得数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'シグナル点灯0.5秒以内タップ3回',
    failTrigger: 'シグナル点灯後0.5秒逃し3回で失敗',
  },
  {
    id: 'arcade-194',
    title: 'サンダードラゴン2',
    brand: 'NMK',
    year: 1993,
    duration: 25,
    difficulty: 'hard',
    concept: 'ボスが4体の分身ドラゴンに分裂する。画面上部に撃破カラーシーケンス（赤→青→緑→黄など）が表示される。指定の順番通りに色ドラゴンをタップして撃破しないと撃破したドラゴンが復活する。順番を守りながら3シーケンス完遂でクリア。',
    objects: [
      { shape: 'face', role: '赤ドラゴン', note: '' },
      { shape: 'face', role: '青ドラゴン', note: '' },
      { shape: 'face', role: '緑ドラゴン', note: '' },
      { shape: 'face', role: '黄ドラゴン', note: '' },
      { shape: 'rect', role: 'カラーシーケンス表示（上部）', note: '正解順序' },
    ],
    counters: [
      { id: 'sequences', name: 'シーケンス完遂数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '正しい順番で4体全撃破×3回',
    failTrigger: '順番ミスで復活3回で失敗',
  },
  {
    id: 'arcade-195',
    title: 'デンジャラスシード',
    brand: 'ナムコ',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: '3機の艦隊が合体して前衛・中衛・後衛の3つの陣形（ATTACK/WIDE/DEFENSE）に切り替えられる。敵の攻撃パターンが1秒表示されたら、それに最適な陣形ボタンをタップ。ATTACK=前面集中、WIDE=拡散、DEFENSE=後方防御。5回正解でクリア。',
    objects: [
      { shape: 'triangle', role: '3機艦隊（陣形変更）', note: '' },
      { shape: 'rect', role: '敵攻撃パターン表示（1秒）', note: '' },
      { shape: 'button', role: 'ATTACKボタン', note: '' },
      { shape: 'button', role: 'WIDEボタン', note: '' },
      { shape: 'button', role: 'DEFENSEボタン', note: '' },
    ],
    counters: [
      { id: 'correct', name: '正陣形選択数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'counter correct >= 5',
    failTrigger: '陣形ミス3回で失敗',
  },
  {
    id: 'arcade-196',
    title: 'ハイウェイレース',
    brand: 'タイトー',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: '高速道路で対向車が押し寄せてくる。ほとんどは避けるべき一般車だが、1台だけ「ターゲットレーサー」が旗付きで混ざっている。ターゲットだけに正面衝突（タップ）して排除。一般車にタップすると失点。ターゲットを見極めて3台排除でクリア。',
    objects: [
      { shape: 'rect', role: '一般対向車（複数・回避対象）', note: '' },
      { shape: 'rect', role: 'ターゲットレーサー（旗付き1台）', note: 'タップで排除' },
      { shape: 'triangle', role: '自車（手前）', note: '' },
    ],
    counters: [
      { id: 'targets', name: 'ターゲット排除数', target: 3, note: '3台でクリア' },
    ],
    winTrigger: 'counter targets >= 3',
    failTrigger: '一般車にタップ3回で失敗',
  },
  {
    id: 'arcade-197',
    title: 'ドラゴンスピリット',
    brand: 'ナムコ',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: 'ドラゴンが進化して頭が複数になる。各頭が独立したリズムでブレスを吐く。全ての頭が同時に吐くタイミングは「同期ゲージ」が全頭同時に満杯になった瞬間に表示される。その瞬間にタップして全頭同時ブレスを発動。3回の全頭同期でクリア。',
    objects: [
      { shape: 'face', role: 'ドラゴン（複数頭）', note: '各頭の同期ゲージ付き' },
      { shape: 'rect', role: '同期ゲージ×3（各頭独立で充填）', note: '全満杯の瞬間が同期点' },
    ],
    counters: [
      { id: 'syncs', name: '全頭同期ブレス数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '全ゲージ満杯同時の瞬間タップ3回',
    failTrigger: '非同期ブレス3回で失敗',
  },
  {
    id: 'arcade-198',
    title: 'QIX',
    brand: 'タイトー',
    year: 1981,
    duration: 25,
    difficulty: 'hard',
    concept: 'QIX（幾何学的な発光体）が画面を跳ね回っている。フィールドの一辺から別の辺へ線を引いて領域を切り取るのが目標。線を引き始めた後、QIXが線に触れると失敗——QIXが画面の反対端に移動した瞬間を狙ってタップして線引きを開始せよ。3回30%以上切り取りでクリア。',
    objects: [
      { shape: 'diamond', role: 'QIX（跳ね回る発光体）', note: '' },
      { shape: 'rect', role: 'フィールド（線引きで領域分割）', note: '' },
      { shape: 'rect', role: '領域占有率インジケーター', note: '' },
    ],
    counters: [
      { id: 'cuts', name: '30%以上切り取り数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'QIXが反対端にいる間に線引き完了×3回',
    failTrigger: 'QIXに線を触れられ3回で失敗',
  },
  {
    id: 'arcade-199',
    title: 'ローリングサンダー',
    brand: 'ナムコ',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: 'エージェントが廊下を進むと敵が3体以上まとまって一列を占領する地点がある。その瞬間にドアに飛び込んでドア越しに一列射撃すれば3体以上を一斉排除できる。敵が散らばっているうちに撃っても効果が薄い。3体以上集まった瞬間を待ってタップ。3回一斉排除でクリア。',
    objects: [
      { shape: 'face', role: 'エージェント（左端）', note: '' },
      { shape: 'rect', role: 'ドア（飛び込みポイント）', note: '' },
      { shape: 'face', role: '敵×複数（一列に集まる）', note: '3体以上で光る' },
    ],
    counters: [
      { id: 'sweeps', name: '3体以上一斉排除数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3体以上集合時にタップ3回',
    failTrigger: '2体以下でタップ3回で失敗',
  },
  {
    id: 'arcade-200',
    title: 'エンパイア シティ:1931',
    brand: 'セイブ開発',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: 'ギャングたちが車や柱の陰に隠れながら顔を出してくる。各ギャングが顔を出すタイミングはバラバラだが、3人以上が同時に顔を出す瞬間がある。その瞬間にタップしてトミーガンをひと掃射——3人未満の時に撃つと弾が無駄になる。3回3人以上一斉射撃でクリア。',
    objects: [
      { shape: 'face', role: 'ギャング×5（遮蔽物から顔を出す）', note: '3人以上同時露出で光る' },
      { shape: 'rect', role: '遮蔽物（車・柱）', note: '' },
      { shape: 'button', role: 'トミーガンボタン', note: '' },
    ],
    counters: [
      { id: 'sweeps', name: '3人以上一斉射撃数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3人以上同時露出でタップ3回',
    failTrigger: '2人以下でタップ3回で失敗',
  },
  {
    id: 'arcade-201',
    title: 'ワンダーモモ',
    brand: 'ナムコ',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: 'ももがフープを拾うとワンダーモモに変身して竜巻攻撃が使える。変身は5秒間限定——フープを拾う前に舞台上の敵が5体以上集まった瞬間を見計らいタップして変身し、竜巻で一掃。5体未満のうちに変身すると効果が薄い。3回5体以上一掃でクリア。',
    objects: [
      { shape: 'face', role: 'もも→ワンダーモモ（変身）', note: '' },
      { shape: 'circle', role: 'フープ（舞台上）', note: 'タップで拾って変身' },
      { shape: 'face', role: '敵×複数（増えていく）', note: '5体以上で光る' },
    ],
    counters: [
      { id: 'wipes', name: '5体以上一掃数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '5体以上いる状態でフープタップ3回',
    failTrigger: '4体以下でタップ3回で失敗',
  },
] as const;
