/**
 * ideas/arcade-2020q1.ts
 * Arcade Archives 2020年1〜3月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2020q1Ideas = [
  {
    id: 'arcade-101',
    title: 'ぺんぎんくんWARS',
    brand: 'UPL',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: 'ペンギンが雪玉を放物線で投げる。相手ペンギンは左右に動いており、雪玉の飛行時間がある——今いる位置ではなく着弾時にいる位置を狙え。5つの投擲角候補から予測位置と重なる1つをタップ。3回命中でクリア。',
    objects: [
      { shape: 'face', role: '自キャラペンギン（左端）', note: '' },
      { shape: 'face', role: '相手ペンギン（左右移動）', note: '' },
      { shape: 'circle', role: '雪玉（放物線飛行）', note: '' },
      { shape: 'diamond', role: '投擲角候補×5（扇状）', note: '1つ選択' },
    ],
    counters: [
      { id: 'hits', name: '命中数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'counter hits >= 3',
    failTrigger: '外れ選択3回で失敗',
  },
  {
    id: 'arcade-102',
    title: '出たな!!ツインビー',
    brand: 'KONAMI',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: '雲を撃つとベルが落ちてくる。ベルは着地前に色が自動的に黄→青→赤→白とサイクルする。黄か青の瞬間にタップしてキャッチするとパワーアップ、赤でキャッチするとダメージ。素早く色を読んで5回パワーアップでクリア。',
    objects: [
      { shape: 'balloon', role: 'ベル（落下しながら色変化）', note: '黄・青・赤・白でサイクル' },
      { shape: 'rect', role: '雲（タップで消えてベルを落とす）', note: '' },
      { shape: 'triangle', role: 'ツインビー（下部）', note: '' },
    ],
    counters: [
      { id: 'powerups', name: 'パワーアップ数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'counter powerups >= 5',
    failTrigger: '赤ベルをキャッチ3回で失敗',
  },
  {
    id: 'arcade-103',
    title: 'XX MISSION',
    brand: 'UPL',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: '深海で視界がほぼゼロ。ソナーパルスが定期的に放射され、その瞬間だけ敵の位置が一瞬光って見える。光っている間にタップして魚雷発射。光が消えた後にタップしても届かない。5体撃破でクリア。',
    objects: [
      { shape: 'triangle', role: '潜水艦（中央）', note: '' },
      { shape: 'circle', role: 'ソナーパルス（放射状に広がる）', note: '当たった敵が光る' },
      { shape: 'face', role: '深海敵（暗闇の中）', note: 'ソナー当たり時のみ表示' },
    ],
    counters: [
      { id: 'destroyed', name: '撃破数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'counter destroyed >= 5',
    failTrigger: 'ソナー消灯後タップ3回で失敗',
  },
  {
    id: 'arcade-104',
    title: 'テクモボウル',
    brand: 'テクモ',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: 'パスプレイ：QBがボールを持ち、3人のレシーバーが走り込んでいる。各レシーバーにはディフェンスのカバー状況が表示され、1人だけ「オープン（フリー）」になる瞬間がある。その瞬間にオープンなレシーバーをタップしてパス。タイミングが遅れるとカバーされる。3回成功でクリア。',
    objects: [
      { shape: 'face', role: 'QB（中央）', note: '' },
      { shape: 'face', role: 'レシーバー×3（走り込み）', note: 'オープン時に光る' },
      { shape: 'face', role: 'ディフェンス（カバー移動）', note: '' },
    ],
    counters: [
      { id: 'completions', name: 'パス成功数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'counter completions >= 3',
    failTrigger: 'カバーされた状態でパス3回で失敗',
  },
  {
    id: 'arcade-105',
    title: '天聖龍',
    brand: 'ジャレコ',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: 'ドラゴンボスの体節が光の輪を伝うように順番に点灯していく。光っている節（弱点）は0.5秒で次の節へ移動する。弱点が自機の正面を通過した瞬間にタップして撃ち抜け。5節連続命中でクリア。',
    objects: [
      { shape: 'ellipse', role: 'ドラゴンの体節×7（連結）', note: '1節ずつ順番に光る' },
      { shape: 'triangle', role: '自機（下部中央）', note: '' },
      { shape: 'button', role: '射撃ボタン', note: '' },
    ],
    counters: [
      { id: 'hits', name: '弱点命中数', target: 5, note: '5節でクリア' },
    ],
    winTrigger: 'counter hits >= 5',
    failTrigger: '弱点以外に撃った回数3回で失敗',
  },
  {
    id: 'arcade-106',
    title: 'サスケ VS コマンダ',
    brand: '新日本企画',
    year: 1980,
    duration: 20,
    difficulty: 'normal',
    concept: '敵が盾の陣形の陰に隠れながら横移動してくる。盾の列には隙間があり、左右にゆっくり流れている。サスケの手裏剣の射線（縦一直線）と盾の隙間が重なった瞬間にタップして貫通させよ。5体撃破でクリア。',
    objects: [
      { shape: 'face', role: 'サスケ（左端固定）', note: '' },
      { shape: 'diamond', role: '手裏剣（縦射線）', note: '' },
      { shape: 'rect', role: '盾の陣形（横移動・隙間あり）', note: '' },
      { shape: 'face', role: '敵コマンダ（盾の陰）', note: '' },
    ],
    counters: [
      { id: 'pierced', name: '貫通命中数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'counter pierced >= 5',
    failTrigger: '盾に当たって跳ね返り3回で失敗',
  },
  {
    id: 'arcade-107',
    title: 'VS.麻雀',
    brand: '任天堂',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: '3枚の手牌が表示され、あと1枚で完成する形になっている。4枚の牌がベルトコンベア状に流れていく——その中に1枚だけ上がり牌が混じっている。1秒以内にその牌をタップ。間違えると失点。5回正解でクリア。',
    objects: [
      { shape: 'rect', role: '手牌×3（表示固定）', note: 'あと1枚で上がり' },
      { shape: 'rect', role: '流れる牌×4（コンベア移動）', note: '1枚だけ上がり牌' },
    ],
    counters: [
      { id: 'agari', name: '上がり牌取得数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'counter agari >= 5',
    failTrigger: '間違い牌タップ3回で失敗',
  },
  {
    id: 'arcade-108',
    title: '脱獄',
    brand: 'SNK',
    year: 1988,
    duration: 20,
    difficulty: 'hard',
    concept: '刑務所の廊下を脱獄する。複数の警備員が一定ルートを巡回しており、全員が同時に背を向けた瞬間だけ1マス前進できる。全員の背中が揃うウィンドウは1秒未満——見逃すと次のチャンスまで待つ羽目になる。5マス進めばクリア。',
    objects: [
      { shape: 'face', role: '脱獄囚（左端）', note: '' },
      { shape: 'face', role: '警備員×2（巡回）', note: '背中を向けているとき緑、こちらを向くと赤' },
      { shape: 'rect', role: '廊下（5マス）', note: '' },
    ],
    counters: [
      { id: 'advances', name: '前進数', target: 5, note: '5マスでクリア' },
    ],
    winTrigger: 'counter advances >= 5',
    failTrigger: '警備員に見つかったら失敗',
  },
  {
    id: 'arcade-109',
    title: 'フォーメーションZ',
    brand: 'ジャレコ',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: '戦闘機が飛行形態と歩行形態を切り替えられる。敵が画面に出現するたびにそのシルエットが「空」か「地上」かを示す。飛行形態ボタンか歩行形態ボタンのどちらかをタップして正しい形態で迎撃。形態が合っていない攻撃は当たらない。6体連続正解でクリア。',
    objects: [
      { shape: 'triangle', role: '自機（飛行/歩行の切替表示）', note: '' },
      { shape: 'triangle', role: '空の敵（上半分）', note: '' },
      { shape: 'rect', role: '地上の敵（下半分）', note: '' },
      { shape: 'button', role: '飛行形態ボタン', note: '' },
      { shape: 'button', role: '歩行形態ボタン', note: '' },
    ],
    counters: [
      { id: 'correct', name: '正形態迎撃数', target: 6, note: '6体でクリア' },
    ],
    winTrigger: 'counter correct >= 6',
    failTrigger: '形態ミス3回で失敗',
  },
  {
    id: 'arcade-110',
    title: '怒III',
    brand: 'SNK',
    year: 1989,
    duration: 20,
    difficulty: 'hard',
    concept: '敵兵の一列縦隊が画面を横切っている。その中の1人だけが人質を背負って歩いており、1〜2秒ごとに振り返った瞬間だけ人質の顔が確認できる。振り返りが終わって背中を向けた直後の0.5秒がタップチャンス——それ以外のタイミングは当たらない。3人救出でクリア。',
    objects: [
      { shape: 'face', role: '敵兵×5（横移動・1人が人質を背負う）', note: '' },
      { shape: 'face', role: '人質（振り返り時のみ顔が見える）', note: '' },
      { shape: 'button', role: '射撃ボタン', note: '' },
    ],
    counters: [
      { id: 'rescued', name: '救出数', target: 3, note: '3人でクリア' },
    ],
    winTrigger: 'counter rescued >= 3',
    failTrigger: '人質を背負った兵士以外を撃った3回で失敗',
  },
] as const;
