/**
 * ideas/arcade-2021q1.ts
 * Arcade Archives 2021年1〜3月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2021q1Ideas = [
  {
    id: 'arcade-142',
    title: '妖精物語ロッド・ランド',
    brand: 'ジャレコ',
    year: 1990,
    duration: 20,
    difficulty: 'normal',
    concept: '妖精タムが魔法の棒で足場の真下に梯子を出現させる。梯子に触れた敵は3秒間縛り付けられる。縛られている間にタップして棒でたたいて退治。梯子の出現位置が重要で、複数の敵のうち狙う1体の真下に出さなければならない。5体退治でクリア。',
    objects: [
      { shape: 'face', role: '妖精タム（下部）', note: '' },
      { shape: 'rect', role: '魔法の梯子（タップで出現）', note: '触れた敵を3秒縛る' },
      { shape: 'face', role: '敵×複数（移動中）', note: '縛られると光る' },
    ],
    counters: [
      { id: 'beaten', name: '退治数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '梯子で縛ってから棒でたたく×5',
    failTrigger: '縛り切れず素通り3回で失敗',
  },
  {
    id: 'arcade-143',
    title: 'クォース',
    brand: 'KONAMI',
    year: 1989,
    duration: 25,
    difficulty: 'normal',
    concept: 'ブロック塊が上から降ってくる。塊には欠けている部分がある——そこへ向けて下から四角いブロックを撃ち込んで穴を埋め、完全な長方形を完成させると消滅する。降下速度が速くなるにつれ、どこに撃てば完成するかを素早く判断してタップ。3個消滅でクリア。',
    objects: [
      { shape: 'rect', role: 'ブロック塊（欠けあり・降下）', note: '欠けた部分が光る' },
      { shape: 'rect', role: '補填ブロック（下から発射）', note: 'タップで発射' },
      { shape: 'triangle', role: '自機（下部）', note: '' },
    ],
    counters: [
      { id: 'cleared', name: '完成消滅数', target: 3, note: '3個でクリア' },
    ],
    winTrigger: 'counter cleared >= 3',
    failTrigger: '塊が底に到達3回で失敗',
  },
  {
    id: 'arcade-144',
    title: 'ハレーズコメット',
    brand: 'タイトー',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: 'ハレー彗星の尾から降り注ぐ破片が画面を埋め尽くす。銀色の破片は収集してボーナス、赤い破片は被弾してダメージ。破片密度が上がると赤と銀が混在する中を見極めなければならない。銀破片にだけタップして収集。5個収集でクリア。',
    objects: [
      { shape: 'diamond', role: '銀色破片（収集対象）', note: '' },
      { shape: 'diamond', role: '赤い破片（回避対象）', note: '' },
      { shape: 'triangle', role: '自機（中央）', note: '' },
    ],
    counters: [
      { id: 'silver', name: '銀破片収集数', target: 5, note: '5個でクリア' },
    ],
    winTrigger: 'counter silver >= 5',
    failTrigger: '赤い破片に当たった3回で失敗',
  },
  {
    id: 'arcade-145',
    title: '伊賀忍術伝 五神の書',
    brand: 'ジャレコ',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '手裏剣の有効射程が表示されている。敵が近すぎると手裏剣が当たらず、遠すぎても届かない。「有効距離ゾーン」に敵が入った瞬間にタップして撃墜。距離の判断が毎回変わる中で正確なタイミングを維持せよ。5体撃墜でクリア。',
    objects: [
      { shape: 'diamond', role: '手裏剣', note: '' },
      { shape: 'face', role: '伊賀忍者（左端）', note: '' },
      { shape: 'face', role: '敵（右から接近）', note: '' },
      { shape: 'rect', role: '有効距離ゾーン（ハイライト表示）', note: '' },
    ],
    counters: [
      { id: 'hit', name: '手裏剣命中数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '敵がゾーン内でタップ5回',
    failTrigger: 'ゾーン外タップ3回で失敗',
  },
  {
    id: 'arcade-146',
    title: 'サイバトラー',
    brand: 'ジャレコ',
    year: 1993,
    duration: 20,
    difficulty: 'normal',
    concept: '戦闘機が「ファイター（速・弱弾）」「タンク（遅・強弾）」「サブマリン（中・追尾弾）」の3形態に変形できる。敵が出現するたびに弱点形態のアイコンが1秒だけ光る。光っている間に正しい形態ボタンをタップして迎撃。6体連続正解でクリア。',
    objects: [
      { shape: 'triangle', role: '自機（変形表示付き）', note: '' },
      { shape: 'face', role: '敵（弱点アイコン付き）', note: '1秒だけ光る' },
      { shape: 'button', role: 'ファイター形態ボタン', note: '' },
      { shape: 'button', role: 'タンク形態ボタン', note: '' },
      { shape: 'button', role: 'サブマリン形態ボタン', note: '' },
    ],
    counters: [
      { id: 'correct', name: '正形態撃墜数', target: 6, note: '6体でクリア' },
    ],
    winTrigger: 'counter correct >= 6',
    failTrigger: '形態ミス3回で失敗',
  },
  {
    id: 'arcade-147',
    title: 'ゲバラ',
    brand: 'SNK',
    year: 1987,
    duration: 20,
    difficulty: 'hard',
    concept: '戦場に捕虜（明るい服）と敵兵（暗い服）が混在している。ヘリコプターが横から機銃掃射してくる——掃射ラインが捕虜を通る場合はタップして掃射コースを偏向させよ。掃射ラインに敵兵しかいない場合はタップしてはいけない（自軍の支援射撃になる）。3回偏向成功でクリア。',
    objects: [
      { shape: 'triangle', role: 'ヘリコプター（上部横移動）', note: '' },
      { shape: 'rect', role: '掃射ライン（縦線）', note: '捕虜に当たると赤く表示' },
      { shape: 'face', role: '捕虜（明るい服）', note: '' },
      { shape: 'face', role: '敵兵（暗い服）', note: '' },
    ],
    counters: [
      { id: 'deflects', name: '偏向成功数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '捕虜を守る偏向タップ3回',
    failTrigger: '捕虜に掃射が当たったら失敗',
  },
  {
    id: 'arcade-148',
    title: '魔魁伝説',
    brand: 'ジャレコ',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '敵は炎・氷・雷のいずれかの弱点を持つ。弱点は敵の頭上に0.7秒間だけアイコンが点滅して示される。武器を対応する属性に切り替えてからタップして攻撃。アイコンが消えると弱点が変わり、次のアイコンを待たなければならない。5体撃破でクリア。',
    objects: [
      { shape: 'face', role: '敵（弱点アイコン点滅）', note: '炎・氷・雷の3属性' },
      { shape: 'button', role: '炎属性ボタン', note: '' },
      { shape: 'button', role: '氷属性ボタン', note: '' },
      { shape: 'button', role: '雷属性ボタン', note: '' },
    ],
    counters: [
      { id: 'weakness', name: '弱点攻撃数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '属性一致攻撃5回',
    failTrigger: '属性ミス3回で失敗',
  },
  {
    id: 'arcade-149',
    title: 'サンダードラゴン',
    brand: 'NMK',
    year: 1991,
    duration: 20,
    difficulty: 'hard',
    concept: 'サンダードラゴンボスが口を開けてブレス攻撃を充電する。充電開始から0.5〜1.5秒の間だけ胸部弱点が露出している。2秒経過するとブレスが発射されて被弾。弱点露出ウィンドウを見極めてタップ——早すぎても遅すぎても通じない。3回命中でクリア。',
    objects: [
      { shape: 'face', role: 'サンダードラゴン（大型ボス）', note: '口が開いて充電' },
      { shape: 'star', role: '胸部弱点（露出時のみ光る）', note: '充電0.5〜1.5秒間だけ' },
      { shape: 'rect', role: '充電タイマーバー', note: '' },
    ],
    counters: [
      { id: 'hits', name: '弱点命中数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '充電0.5〜1.5秒以内にタップ3回',
    failTrigger: '2秒経過でブレス被弾3回で失敗',
  },
  {
    id: 'arcade-150',
    title: 'クライムファイターズ',
    brand: 'KONAMI',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: 'ボス敵にダメージを与えていくと、一定ダメージごとに「よろめきモーション」が出る。よろめき中の0.5秒だけ特殊フィニッシャーが発動できる。よろめきが終わると通常ガードに戻る——よろめきを見逃さずにタップせよ。3回フィニッシャーでクリア。',
    objects: [
      { shape: 'face', role: 'ボス敵（HPバー付き）', note: 'よろめき時に全身点滅' },
      { shape: 'face', role: '主人公（左側）', note: '' },
      { shape: 'button', role: 'フィニッシャーボタン', note: 'よろめき中のみ有効' },
    ],
    counters: [
      { id: 'finishers', name: 'フィニッシャー数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'よろめき中にタップ3回',
    failTrigger: 'よろめき終了後タップ3回で失敗',
  },
  {
    id: 'arcade-151',
    title: 'スイマー',
    brand: 'テーカン',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: '川を泳ぐ選手が障害物（流木・岩）を避けながら進む。各障害物には「潜れる高さ」と「泳いで越える高さ」がある。深度インジケーターを見て、障害物の高さに合わせた深度をタップ。浅すぎると激突、深すぎると底につかえる。5障害物クリアでクリア。',
    objects: [
      { shape: 'face', role: 'スイマー（前進）', note: '' },
      { shape: 'rect', role: '障害物（高さ表示付き）', note: '流木・岩' },
      { shape: 'rect', role: '深度インジケーター', note: '上下タップで調整' },
    ],
    counters: [
      { id: 'cleared', name: '障害物通過数', target: 5, note: '5個でクリア' },
    ],
    winTrigger: 'counter cleared >= 5',
    failTrigger: '衝突3回で失敗',
  },
] as const;
