/**
 * ideas/arcade-2019b.ts
 * Arcade Archives 2019年配信タイトル（後半）— Swizzleゲームネタ帳
 */

export const arcade2019bIdeas = [
  {
    id: 'arcade-086',
    title: 'Xマルチプライ',
    brand: 'アイレム',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: '自機の前方から機械アームが1秒かけてゆっくり伸びていく。アームが完全に伸びきった瞬間だけ攻撃力が最大になる。ゲージが「完全伸長」マーカーに達した瞬間にタップして敵を切断。早すぎると空振り、遅すぎると縮み始める。3体撃破でクリア。',
    objects: [
      { shape: 'triangle', role: '自機（左端）', note: '' },
      { shape: 'rect', role: '機械アーム（伸長中）', note: '伸長ゲージ付き' },
      { shape: 'face', role: '敵（右側）', note: '' },
      { shape: 'rect', role: '伸長ゲージ', note: '完全伸長マーカー付き' },
    ],
    counters: [
      { id: 'cuts', name: '切断数', target: 3, note: '3体でクリア' },
    ],
    winTrigger: 'アームが完全伸長の瞬間タップ3回',
    failTrigger: '伸長不足または縮小後タップ3回で失敗',
  },
  {
    id: 'arcade-087',
    title: 'VS.グラディウス',
    brand: 'KONAMI',
    year: 1984,
    duration: 25,
    difficulty: 'hard',
    concept: 'モアイ像が3体横一列に並んでいる。各モアイの口が独立したリズムで開閉している。自機が通り抜けるには3つ全ての口が同時に開いた瞬間をタップして飛び込まなければならない。全口が開く瞬間は短い——見逃すと口に激突。3回通過でクリア。',
    objects: [
      { shape: 'face', role: 'モアイ像×3（口が独立開閉）', note: '口の開閉は非同期' },
      { shape: 'triangle', role: '自機（左端待機）', note: '' },
      { shape: 'button', role: '突入ボタン', note: '' },
    ],
    counters: [
      { id: 'passed', name: '通過成功数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3口全開の瞬間タップ3回',
    failTrigger: '口が閉じている状態で突入3回で失敗',
  },
  {
    id: 'arcade-088',
    title: 'ウォータースキー',
    brand: 'データイースト',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: 'スキーヤーがスラロームコースを滑る。浮標（ブイ）が交互に左右から飛び出してくる。左側のブイは右に避け、右側のブイは左に避ける。ブイが画面中央に到達する前に正しい方向をタップ。5個連続回避でクリア。',
    objects: [
      { shape: 'triangle', role: 'スキーヤー（前進）', note: '' },
      { shape: 'circle', role: 'ブイ（左右交互に出現）', note: '' },
      { shape: 'button', role: '左ボタン', note: '' },
      { shape: 'button', role: '右ボタン', note: '' },
    ],
    counters: [
      { id: 'avoided', name: '回避成功数', target: 5, note: '5個でクリア' },
    ],
    winTrigger: 'counter avoided >= 5',
    failTrigger: 'ブイに当たったら失敗',
  },
  {
    id: 'arcade-089',
    title: 'ピンボール',
    brand: '任天堂',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: 'ボールがフリッパーへ向かって落下してくる。フリッパーの「スイートスポット」（中心付近）に差し掛かった0.5秒間だけタップが有効で、強いショットが打てる。端に当たると弱い球になり失点。5回スイートスポットで打てればクリア。',
    objects: [
      { shape: 'circle', role: 'ボール（落下）', note: '' },
      { shape: 'rect', role: 'フリッパー（スイートスポットが光る）', note: '' },
      { shape: 'button', role: 'フリッパーボタン', note: '' },
    ],
    counters: [
      { id: 'sweet', name: 'スイートショット数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'counter sweet >= 5',
    failTrigger: 'スイートスポット外打ち3回で失敗',
  },
  {
    id: 'arcade-090',
    title: 'ビジランテ',
    brand: 'アイレム',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: 'ギャングを倒すと吹っ飛んでいく。ステージ中央に人質が立っており、倒したギャングが人質の方向へ飛ぶと激突してしまう。ギャングを殴る前に人質から遠ざかる方向を選択してタップ——人質から見て反対側に吹き飛ばせ。3人の人質を守りながら5人倒せばクリア。',
    objects: [
      { shape: 'face', role: '主人公（操作）', note: '' },
      { shape: 'face', role: 'ギャング（接近）', note: '倒すと吹き飛ぶ方向を指定' },
      { shape: 'face', role: '人質（中央固定）', note: '' },
    ],
    counters: [
      { id: 'defeated', name: '安全に倒した数', target: 5, note: '5人でクリア' },
    ],
    winTrigger: 'counter defeated >= 5（人質に激突なし）',
    failTrigger: 'ギャングが人質に激突3回で失敗',
  },
  {
    id: 'arcade-091',
    title: 'TRACK & FIELD',
    brand: 'KONAMI',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: 'ハンマー投げの回転中、角度インジケーターが円弧上を往復している。45度の放出角度が最も遠くに飛ぶ。インジケーターが45度マーカーに重なった瞬間にタップして放出。マーカーから外れると距離が落ちて失格。3投成功でクリア。',
    objects: [
      { shape: 'face', role: 'アスリート（回転中）', note: '' },
      { shape: 'circle', role: 'ハンマー（回転）', note: '' },
      { shape: 'diamond', role: '角度インジケーター（往復）', note: '45度マーカー付き弧' },
    ],
    counters: [
      { id: 'good', name: '合格投数', target: 3, note: '3投でクリア' },
    ],
    winTrigger: 'インジケーターが45度ゾーンでタップ3回',
    failTrigger: 'ゾーン外タップ3回で失敗',
  },
  {
    id: 'arcade-092',
    title: 'タイムトンネル',
    brand: 'ニチブツ',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: 'タイムトンネルを飛来する物体には大小2種類ある。画面の20%以上を占める大型物体だけをタップして破壊しなければならない。小型物体をタップすると余計なエネルギーを消費して失敗。大型を5個破壊でクリア。',
    objects: [
      { shape: 'circle', role: '大型物体（画面20%以上）', note: 'タップで破壊' },
      { shape: 'circle', role: '小型物体（画面20%未満）', note: 'タップ禁止' },
      { shape: 'rect', role: 'タイムトンネル背景', note: '' },
    ],
    counters: [
      { id: 'large', name: '大型破壊数', target: 5, note: '5個でクリア' },
    ],
    winTrigger: 'counter large >= 5',
    failTrigger: '小型タップ3回で失敗',
  },
  {
    id: 'arcade-093',
    title: 'VS.キャッスルヴァニア',
    brand: 'KONAMI',
    year: 1987,
    duration: 20,
    difficulty: 'hard',
    concept: 'ドラキュラがテレポートで画面のどこかに瞬間移動してくる。出現した直後0.3秒以内だけ実体化しており、その間にタップすると聖水が当たる。0.3秒を過ぎると霧に戻り無敵になる。5回当てればクリア。',
    objects: [
      { shape: 'face', role: 'ドラキュラ（ランダム出現）', note: '出現0.3秒後から霧化' },
      { shape: 'face', role: 'シモン（下部固定）', note: '' },
      { shape: 'circle', role: '聖水（投擲）', note: '' },
    ],
    counters: [
      { id: 'hit', name: '命中数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'counter hit >= 5',
    failTrigger: '0.3秒以内に当てられなかった3回で失敗',
  },
  {
    id: 'arcade-094',
    title: 'ゴルフ',
    brand: '任天堂',
    year: 1984,
    duration: 25,
    difficulty: 'normal',
    concept: '風向きと風力がアイコンで表示される。グリーンまでの距離と風を補正した5つのスイング角度候補が表示される。ボールがグリーンに乗る正しい角度を1つ選んでタップ。3ホールをパーイン以内でクリア。',
    objects: [
      { shape: 'diamond', role: '風向きアイコン', note: '' },
      { shape: 'triangle', role: 'スイング角度候補×5', note: '1つ選択' },
      { shape: 'circle', role: 'ボール', note: '' },
      { shape: 'circle', role: 'グリーン（ターゲット）', note: '' },
    ],
    counters: [
      { id: 'pars', name: 'パーイン数', target: 3, note: '3ホールでクリア' },
    ],
    winTrigger: 'counter pars >= 3',
    failTrigger: '3ホールでボギー以上3回で失敗',
  },
  {
    id: 'arcade-095',
    title: 'T・A・N・K',
    brand: 'SNK',
    year: 1985,
    duration: 25,
    difficulty: 'hard',
    concept: '地雷原の中を戦車が進む。地雷探知機のピン音が周期で変化する——地雷が近いほどピンが速く、安全なほど遅い。4方向の移動候補が提示され、ピンが最も遅い（安全な）方向をタップして前進。地雷を踏んだら即失敗。8マス進めばクリア。',
    objects: [
      { shape: 'rect', role: '戦車（中央）', note: '' },
      { shape: 'star', role: '地雷（見えない）', note: '踏むと爆発' },
      { shape: 'diamond', role: '方向候補×4', note: 'ピン頻度でヒント' },
      { shape: 'rect', role: '地雷探知機ゲージ', note: 'ピン速度を視覚化' },
    ],
    counters: [
      { id: 'safe', name: '安全前進数', target: 8, note: '8マスでクリア' },
    ],
    winTrigger: 'counter safe >= 8',
    failTrigger: '地雷踏んだら即失敗',
  },
  {
    id: 'arcade-096',
    title: 'イー・アル・カンフー',
    brand: 'KONAMI',
    year: 1984,
    duration: 20,
    difficulty: 'hard',
    concept: '5人の武道家が順番に登場する。各武道家はダメージを受けた後に固有の「硬直時間」がある——長い者もいれば短い者もいる。硬直中だけ反撃が当たる。硬直の長さを見極め、終わる前にタップして反撃せよ。硬直が切れた後のタップは空振り。',
    objects: [
      { shape: 'face', role: '武道家（各自固有硬直時間）', note: '硬直中は光る' },
      { shape: 'face', role: 'リー（自機）', note: '' },
      { shape: 'button', role: '攻撃ボタン', note: '' },
    ],
    counters: [
      { id: 'counters', name: '反撃成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'counter counters >= 5',
    failTrigger: '硬直外タップ3回で失敗',
  },
  {
    id: 'arcade-097',
    title: '海底大戦争',
    brand: 'アイレム',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '潜水艦が水面に3秒間だけ浮上する。浮上中に上空を飛んでいる敵機を全てタップして撃墜しなければならない。3秒後に潜航するため、画面に残っている敵機は次のウェーブへ持ち越せない。5機全撃墜×3ウェーブでクリア。',
    objects: [
      { shape: 'rect', role: '潜水艦（水面に浮上）', note: '3秒でタイマー表示' },
      { shape: 'triangle', role: '敵機×5（上空）', note: 'タップで撃墜' },
      { shape: 'rect', role: '海面ライン', note: '' },
    ],
    counters: [
      { id: 'waves', name: 'ウェーブ全撃墜数', target: 3, note: '3ウェーブでクリア' },
    ],
    winTrigger: '3秒以内に5機全撃墜を3回達成',
    failTrigger: '1機でも残したまま潜航3回で失敗',
  },
  {
    id: 'arcade-098',
    title: 'HYPER SPORTS',
    brand: 'KONAMI',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: '重量挙げでバーベルが徐々に重くなっていく。自機の「現在筋力ゲージ」が表示されており、バーベルの重量が筋力の±10%以内に収まった瞬間だけ持ち上げられる。ゲージを見てタイミングを合わせてタップ。3回成功でクリア。',
    objects: [
      { shape: 'face', role: 'アスリート（スタンバイ）', note: '' },
      { shape: 'rect', role: 'バーベル（重量が増加）', note: '' },
      { shape: 'rect', role: '筋力ゲージ', note: '±10%ゾーン表示' },
      { shape: 'button', role: 'リフトボタン', note: '' },
    ],
    counters: [
      { id: 'lifts', name: 'リフト成功数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '重量が筋力の±10%以内の瞬間タップ3回',
    failTrigger: 'ゾーン外タップ3回で失敗',
  },
  {
    id: 'arcade-099',
    title: 'フロッガー',
    brand: 'KONAMI',
    year: 1981,
    duration: 20,
    difficulty: 'normal',
    concept: 'カエルが3車線の道路を渡る。各車線に車が行き来しており、それぞれ独立した速度とリズムで動いている。3車線同時に隙間が重なる瞬間が1秒間だけ生まれる。その瞬間にタップして一気に3車線を渡り切れ。3回渡ればクリア。',
    objects: [
      { shape: 'face', role: 'カエル（左端待機）', note: '' },
      { shape: 'rect', role: '車×複数（3車線、異なる速度）', note: '' },
      { shape: 'button', role: '渡るボタン', note: '' },
    ],
    counters: [
      { id: 'cross', name: '渡り切り数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3車線同時隙間でタップ3回',
    failTrigger: '車に当たったら失敗',
  },
  {
    id: 'arcade-100',
    title: 'VS.バルーンファイト',
    brand: '任天堂',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: '2体の敵バルーンファイターがそれぞれランダムに漂っている。2体の距離が最も縮まった瞬間にタップすると1回の体当たりで両方の風船を割れる。離れているときにタップしても1体にしか届かない。3回同時破壊でクリア。',
    objects: [
      { shape: 'balloon', role: '敵ファイターA（漂い移動）', note: '' },
      { shape: 'balloon', role: '敵ファイターB（漂い移動）', note: '' },
      { shape: 'face', role: '自機ファイター（中央）', note: '' },
      { shape: 'rect', role: '距離インジケーター', note: '2体の距離を表示' },
    ],
    counters: [
      { id: 'double', name: '同時破壊数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '2体が最接近の瞬間タップ3回',
    failTrigger: '片側だけ破壊3回で失敗',
  },
] as const;
