/**
 * ideas/arcade-2020q3.ts
 * Arcade Archives 2020年7〜9月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2020q3Ideas = [
  {
    id: 'arcade-120',
    title: 'P-47',
    brand: 'ジャレコ',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '対空砲が複数、それぞれ異なる速度で「充電アニメーション」を行っている。充電が完了すると砲弾が発射されてしまう。充電完了前にその砲をタップして撃破せよ。充電が速い砲を優先する判断力が問われる。5門撃破でクリア。',
    objects: [
      { shape: 'rect', role: '対空砲×3（各自充電アニメ）', note: '充電バー付き' },
      { shape: 'triangle', role: '自機P-47（上部）', note: '' },
      { shape: 'diamond', role: '砲弾（充電完了後に発射）', note: '' },
    ],
    counters: [
      { id: 'guns', name: '撃破砲門数', target: 5, note: '5門でクリア' },
    ],
    winTrigger: 'counter guns >= 5',
    failTrigger: '砲弾に当たったら失敗',
  },
  {
    id: 'arcade-121',
    title: 'カンガルー',
    brand: 'サン電子',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: 'サルがリンゴを投げる前に短い「投擲予備動作」がある。予備動作中にパンチすると逆にリンゴに当たる。予備動作が終わってサルがリンゴを放った直後の0.5秒だけパンチが当たる。サルの投げ動作を最後まで見てからタップ。5匹撃退でクリア。',
    objects: [
      { shape: 'face', role: 'サル（投擲予備動作→投擲）', note: '予備動作中は赤、投擲後は緑' },
      { shape: 'circle', role: 'リンゴ（投擲後に飛ぶ）', note: '' },
      { shape: 'face', role: 'カンガルーのお母さん（中央）', note: '' },
    ],
    counters: [
      { id: 'punched', name: '撃退数', target: 5, note: '5匹でクリア' },
    ],
    winTrigger: 'counter punched >= 5',
    failTrigger: 'リンゴに当たったら失敗',
  },
  {
    id: 'arcade-122',
    title: '鋼鉄要塞シュトラール',
    brand: 'UPL',
    year: 1992,
    duration: 20,
    difficulty: 'hard',
    concept: '要塞の外壁が回転シールドで守られている。シールドは複数のパネルが回転しており、1か所だけ隙間が生じた瞬間に内部コアが露出する。自機の射線と隙間が重なった瞬間にタップして内部コアを撃ち抜け。隙間は1秒未満しか開かない。3回命中でクリア。',
    objects: [
      { shape: 'circle', role: '要塞シールド（回転）', note: '1か所だけ隙間' },
      { shape: 'star', role: '内部コア（隙間時のみ露出）', note: '' },
      { shape: 'triangle', role: '自機（下部）', note: '' },
    ],
    counters: [
      { id: 'core', name: 'コア命中数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'counter core >= 3',
    failTrigger: 'シールド閉鎖中に撃った3回で失敗',
  },
  {
    id: 'arcade-123',
    title: 'バーガータイム',
    brand: 'データイースト',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: 'バーガー食材が足場の端から端まで踏み歩くと下に落下する。食材の真下に敵が来ているタイミングで踏み切れば巻き込める。敵は左右から食材の下に向かって歩いてくる——両側の敵が揃って食材の真下に収まった瞬間に踏み始めてまとめて潰せ。3回成功でクリア。',
    objects: [
      { shape: 'rect', role: 'バーガー食材（プラットフォーム）', note: '端から端まで踏むと落下' },
      { shape: 'face', role: '敵（左右から接近）', note: '食材の下に集まる' },
      { shape: 'face', role: 'シェフ（食材の上）', note: '' },
    ],
    counters: [
      { id: 'squashed', name: '巻き込み落下数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '左右の敵が揃ったタイミングで踏み始め3回',
    failTrigger: '敵なしで落下（空振り）3回で失敗',
  },
  {
    id: 'arcade-124',
    title: 'サーカスチャーリー',
    brand: 'KONAMI',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: 'チャーリーがトランポリンで跳ね上がる。空中の輪（リング）がブランコのように左右に揺れている。チャーリーが跳躍の頂点に達した瞬間とリングが真上を通る瞬間が重なったときにタップしてリングをつかめ。頂点とリングの位置が同時に揃う一瞬を狙え。5回成功でクリア。',
    objects: [
      { shape: 'face', role: 'チャーリー（上下に跳ねる）', note: '頂点に達すると光る' },
      { shape: 'circle', role: 'リング（左右に揺れる）', note: '真上で光る' },
    ],
    counters: [
      { id: 'grabs', name: 'リングつかみ数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '頂点とリング真上が同時の瞬間タップ5回',
    failTrigger: 'タイミングずれ3回で失敗',
  },
  {
    id: 'arcade-125',
    title: 'スーパーパンチアウト!!',
    brand: '任天堂',
    year: 1985,
    duration: 20,
    difficulty: 'hard',
    concept: '対戦相手がパンチを繰り出す前に一瞬だけ「溜め動作」を見せる。左腕が光れば左フック、右腕が光れば右アッパーが来る。光った方向と反対側にタップして回避せよ。0.4秒以内に正しい方向をタップ。間違えると被弾してHPが減る。5回回避でクリア。',
    objects: [
      { shape: 'face', role: '対戦相手（中央大型）', note: '腕の溜め動作が光る' },
      { shape: 'button', role: '左回避ボタン', note: '' },
      { shape: 'button', role: '右回避ボタン', note: '' },
      { shape: 'rect', role: 'HPゲージ', note: '' },
    ],
    counters: [
      { id: 'dodges', name: '回避成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '溜め方向と逆にタップ5回',
    failTrigger: '方向ミスで被弾3回で失敗',
  },
  {
    id: 'arcade-126',
    title: 'トライゴン',
    brand: 'KONAMI',
    year: 1990,
    duration: 25,
    difficulty: 'hard',
    concept: '自機に3門の砲台があり、それぞれ異なる角度に向けられる。画面上部に敵の配置図が表示され、3門の照準が全敵をカバーする角度になったときだけ一斉射撃が有効。3本の照準線が全ての敵点を通るようにタップして発射。カバーしきれないと残敵が生き残る。3回全滅でクリア。',
    objects: [
      { shape: 'triangle', role: '自機（下部中央）', note: '3門の角度表示' },
      { shape: 'diamond', role: '照準線×3（角度調整可）', note: '' },
      { shape: 'face', role: '敵配置×複数（上部）', note: '' },
    ],
    counters: [
      { id: 'volleys', name: '全滅斉射数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3門全て敵をカバーした状態でタップ3回',
    failTrigger: 'カバー不足で斉射3回で失敗',
  },
  {
    id: 'arcade-127',
    title: 'ジェミニウイング',
    brand: 'テクモ',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '小オーブを収集するたびに爆弾が大きくなる。画面上に「敵の塊」が出現し、その塊のサイズが数字で表示される。爆弾サイズが塊の数字と一致したときにタップして爆発させると全滅。小さすぎると爆発が届かず、大きすぎると爆風が自機に当たる。3塊全滅でクリア。',
    objects: [
      { shape: 'circle', role: '小オーブ（収集で爆弾が成長）', note: '' },
      { shape: 'bomb', role: '爆弾（サイズ表示付き）', note: 'タップで爆発' },
      { shape: 'face', role: '敵の塊（サイズ数字付き）', note: '' },
    ],
    counters: [
      { id: 'blasts', name: '全滅爆破数', target: 3, note: '3塊でクリア' },
    ],
    winTrigger: '爆弾サイズ=塊サイズの瞬間タップ3回',
    failTrigger: 'サイズ不一致爆破3回で失敗',
  },
  {
    id: 'arcade-128',
    title: 'E.D.F.',
    brand: 'ジャレコ',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: '敵の編隊が幾何学的なフォーメーションで飛行している。隊形の中心に「コア機」が隠れており、隊形が回転するたびに一瞬だけコア機が外周に露出する。その露出した0.5秒以内にタップして撃墜。隊形が再び閉じるとコアは守られてしまう。5機撃墜でクリア。',
    objects: [
      { shape: 'triangle', role: '編隊機（フォーメーション回転）', note: '' },
      { shape: 'star', role: 'コア機（外周露出時のみ光る）', note: '' },
      { shape: 'triangle', role: '自機（下部）', note: '' },
    ],
    counters: [
      { id: 'cores', name: 'コア機撃墜数', target: 5, note: '5機でクリア' },
    ],
    winTrigger: 'counter cores >= 5',
    failTrigger: '閉鎖中に撃った3回で失敗',
  },
  {
    id: 'arcade-129',
    title: "バーニン'ラバー",
    brand: 'データイースト',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: 'レーシングカーが高速で前進している。コース上に水たまりが出現し、ジャンプで飛び越えなければならない。水たまりの手前に「踏み切り点」マーカーがあり、ちょうどそこでタップしてジャンプ。早すぎると水たまりの手前に着地、遅すぎると水に落ちる。5回成功でクリア。',
    objects: [
      { shape: 'triangle', role: 'レーシングカー（前進）', note: '' },
      { shape: 'rect', role: '水たまり（障害物）', note: '' },
      { shape: 'diamond', role: '踏み切り点マーカー', note: 'ここでタップが正解' },
      { shape: 'button', role: 'ジャンプボタン', note: '' },
    ],
    counters: [
      { id: 'jumps', name: 'ジャンプ成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'counter jumps >= 5',
    failTrigger: '水たまりに落ちた3回で失敗',
  },
] as const;
