/**
 * ideas/arcade-2016.ts
 * Arcade Archives 2016年配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2016Ideas = [
  {
    id: 'arcade-035',
    title: 'バブルボブル',
    brand: 'タイトー',
    year: 1986,
    duration: 25,
    difficulty: 'normal',
    concept: 'バブが泡を吐く。泡は画面を漂いながら少しずつ膨らむ。タップで泡を飛ばし、敵が泡の真下に来た瞬間に二度目のタップで泡を落として被せよ。敵の動きを読んで狙え。3体捕獲でクリア。',
    objects: [
      { shape: 'balloon', role: '泡（漂いながら膨らむ）', note: 'タップで発射、二度目で落下' },
      { shape: 'face', role: '敵キャラ×3（横移動）', note: '' },
      { shape: 'face', role: 'バブ', note: '左端固定' },
    ],
    counters: [
      { id: 'captured', name: '捕獲数', target: 3, note: '3体でクリア' },
    ],
    winTrigger: 'counter captured >= 3',
    failTrigger: '泡が消えるまでに被せられなかった回数3回で失敗',
  },
  {
    id: 'arcade-036',
    title: 'キッドのホレホレ大作戦',
    brand: 'ニチブツ',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '敵キャラが左から歩いてくる。敵の2歩手前でタップして穴を掘り、敵が落ちた直後に穴の縁をタップして土を被せる。二段階のタイミングが両方合わないと閉じ込めに失敗する。',
    objects: [
      { shape: 'face', role: '敵（左から右へ歩く）', note: '' },
      { shape: 'rect', role: '地面（穴を掘る対象）', note: 'タップで穴が開く' },
    ],
    counters: [
      { id: 'buried', name: '埋めた数', target: 3, note: '3体埋めでクリア' },
    ],
    winTrigger: 'counter buried >= 3',
    failTrigger: '穴掘りタイミングまたは埋めタイミングを外した回数3回で失敗',
  },
  {
    id: 'arcade-037',
    title: 'ダブルドラゴンII ザ・リベンジ',
    brand: 'テクノスジャパン',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: 'ビリーとジミーが左右から同時に敵に迫る。2人が敵から等距離になった瞬間にタップして同時打撃。タイミングがずれると片方だけヒットになり効果が半減する。',
    objects: [
      { shape: 'face', role: 'ビリー（左から近づく）', note: '' },
      { shape: 'face', role: 'ジミー（右から近づく）', note: '' },
      { shape: 'face', role: '敵（中央固定）', note: '' },
    ],
    counters: [
      { id: 'syncs', name: '同時打撃数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'counter syncs >= 3',
    failTrigger: 'ずれて片側だけヒット3回で失敗',
  },
  {
    id: 'arcade-038',
    title: '聖戦士アマテラス',
    brand: 'ニチブツ',
    year: 1986,
    duration: 20,
    difficulty: 'hard',
    concept: 'アマテラスが回転刃を投げる。刃は壁で跳ね返って手元に戻ってくる。戻ってきた刃が手の届く位置に来た瞬間にタップしてキャッチ。取り損ねると自分がダメージを受ける。',
    objects: [
      { shape: 'diamond', role: '回転刃（投擲→跳ね返り）', note: '往復軌道' },
      { shape: 'face', role: 'アマテラス（中央）', note: '' },
    ],
    counters: [
      { id: 'catches', name: 'キャッチ数', target: 5, note: '5回連続キャッチでクリア' },
    ],
    winTrigger: 'counter catches >= 5',
    failTrigger: '取り損ね3回で失敗',
  },
  {
    id: 'arcade-039',
    title: 'フラック・アタック',
    brand: 'KONAMI',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '画面上半分に飛行機、下半分に戦車が現れる。飛んでいる敵には上半分をタップ、地上の敵には下半分をタップして砲撃。エリアを間違えると弾が届かない。6体撃破でクリア。',
    objects: [
      { shape: 'triangle', role: '飛行機敵（上半分）', note: '' },
      { shape: 'rect', role: '戦車敵（下半分）', note: '' },
    ],
    counters: [
      { id: 'destroyed', name: '撃破数', target: 6, note: '6体でクリア' },
    ],
    winTrigger: 'counter destroyed >= 6',
    failTrigger: 'エリア間違いタップ3回で失敗',
  },
  {
    id: 'arcade-040',
    title: 'グラディウスII ゴーファーの野望',
    brand: 'KONAMI',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '自機に追随するオプション（光球）が4個ある。4個が画面の四隅に散開した瞬間にタップして全オプションを固定し、4方向同時射撃を発動。広がりきる前にタップすると射角が狭まる。',
    objects: [
      { shape: 'circle', role: 'オプション×4（四隅へ展開）', note: '' },
      { shape: 'triangle', role: '自機（中央）', note: '' },
      { shape: 'button', role: '固定ボタン', note: '' },
    ],
    counters: [
      { id: 'volleys', name: '四方射撃数', target: 3, note: '3回成功でクリア' },
    ],
    winTrigger: '4個全て四隅に達した状態でタップ3回',
    failTrigger: '展開不足でタップ3回で失敗',
  },
  {
    id: 'arcade-041',
    title: 'アームドF',
    brand: 'ニチブツ',
    year: 1988,
    duration: 20,
    difficulty: 'hard',
    concept: 'ロボが被弾し続けてHPが残り1になった。爆発まで3秒——その間にタップしてパイロットを射出せよ。射出後に現れる脱出ポッドを素早くタップしてキャッチできればクリア。時間切れまたはポッド見逃しで失敗。',
    objects: [
      { shape: 'rect', role: 'ロボ（点滅中）', note: '3秒後に爆発' },
      { shape: 'circle', role: '脱出ポッド（射出後に出現）', note: '2秒で消える' },
      { shape: 'button', role: '射出ボタン', note: '' },
    ],
    counters: [
      { id: 'escapes', name: '脱出成功数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '射出タップ→ポッドタップを3回完遂',
    failTrigger: '3秒以内に射出しないまたはポッドを見逃して失敗',
  },
  {
    id: 'arcade-042',
    title: '奇々怪界',
    brand: 'タイトー',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: 'お化けが実体（不透明）と透明体の間を周期的に切り替わる。実体の間だけお札が通じる。実体の瞬間だけタップして退治。透明体のときにタップするとお札が無駄になり残弾が減る。',
    objects: [
      { shape: 'face', role: 'お化け×4（実体/透明を周期切替）', note: '' },
      { shape: 'star', role: 'お札残弾インジケーター', note: '最大5枚' },
    ],
    counters: [
      { id: 'exorcised', name: '退治数', target: 4, note: '4体でクリア' },
    ],
    winTrigger: 'counter exorcised >= 4',
    failTrigger: 'お札残弾0で失敗',
  },
  {
    id: 'arcade-043',
    title: '魂斗羅',
    brand: 'KONAMI',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: 'ビルとランスが並走しながら交互に射撃している。片方が弾切れ（装填中）の時だけ相方が前に出て代わりに撃つ。装填中のキャラが最前線に出た瞬間に相方をタップして援護射撃に切り替えよ。',
    objects: [
      { shape: 'face', role: 'ビル（装填/射撃切替）', note: '' },
      { shape: 'face', role: 'ランス（装填/射撃切替）', note: '' },
      { shape: 'button', role: 'ビル射撃ボタン', note: '' },
      { shape: 'button', role: 'ランス射撃ボタン', note: '' },
    ],
    counters: [
      { id: 'covers', name: '援護成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'counter covers >= 5',
    failTrigger: '装填中キャラを射撃タップ3回で失敗',
  },
  {
    id: 'arcade-044',
    title: 'ダライアス',
    brand: 'タイトー',
    year: 1986,
    duration: 25,
    difficulty: 'hard',
    concept: '巨大ボス魚が口を開いて砲撃の準備をする。口の開き幅がゲージに表示される。ゲージがちょうど「最大幅」マーカーに達した瞬間にタップしてアームレーザーを撃ち込め。過小/過大どちらも通じない。',
    objects: [
      { shape: 'ellipse', role: 'ボス魚の口（開閉アニメ）', note: '' },
      { shape: 'rect', role: '口幅ゲージ', note: '「最大幅」マーカー付き' },
      { shape: 'button', role: '射撃ボタン', note: '' },
    ],
    counters: [
      { id: 'hits', name: '命中数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'counter hits >= 3',
    failTrigger: 'ゲージがマーカー外でタップ3回で失敗',
  },
  {
    id: 'arcade-045',
    title: 'アトミックロボキッド',
    brand: 'UPL',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '原子力エネルギーオーブが6個浮かんでいる。ロボが5個収集するとクリアだが、6個目を収集するとオーバーロードで爆発。5個タップして止まれ。6個目だけ絶対に避けよ。',
    objects: [
      { shape: 'circle', role: 'エネルギーオーブ×6', note: '1個だけ赤（危険）' },
      { shape: 'face', role: 'アトミックロボキッド', note: '' },
    ],
    counters: [
      { id: 'collected', name: '収集数', target: 5, note: '5個でクリア' },
    ],
    winTrigger: 'counter collected >= 5（赤オーブを取らずに）',
    failTrigger: '赤オーブをタップで即失敗',
  },
  {
    id: 'arcade-046',
    title: 'テラフォース',
    brand: 'ニチブツ',
    year: 1987,
    duration: 25,
    difficulty: 'hard',
    concept: '自機の爆撃ゲージが5秒かけてゆっくり上昇する。ターゲットリングが画面上を移動しており、リングがボスの核心と重なった瞬間にゲージMAXになるよう逆算してタップ。ズレると外れる。',
    objects: [
      { shape: 'circle', role: 'ターゲットリング（移動）', note: '' },
      { shape: 'star', role: 'ボスの核心（固定）', note: '' },
      { shape: 'rect', role: '爆撃ゲージ', note: '5秒でMAX' },
      { shape: 'button', role: '爆撃ボタン', note: '' },
    ],
    counters: [
      { id: 'direct', name: '直撃数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'リング+核心+ゲージMAXが同時の瞬間にタップ3回',
    failTrigger: '条件不一致タップ3回で失敗',
  },
  {
    id: 'arcade-047',
    title: '悪魔城ドラキュラ',
    brand: 'KONAMI',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: 'メデューサの首が正弦波を描いて飛んでくる。首の高さが上下に変動する中で、シモンの立ち位置（中段固定）と同じ高さになった一瞬にタップして鞭を振れ。高さがずれていると空振りになる。',
    objects: [
      { shape: 'face', role: 'メデューサの首（正弦波移動）', note: '' },
      { shape: 'face', role: 'シモン・ベルモンド（中段固定）', note: '' },
      { shape: 'button', role: '鞭ボタン', note: '' },
    ],
    counters: [
      { id: 'whips', name: '命中数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'counter whips >= 5',
    failTrigger: '空振り3回で失敗',
  },
] as const;
