/**
 * ideas/arcade-2023q4.ts
 * Arcade Archives 2023年10〜12月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2023q4Ideas = [
  {
    id: 'arcade-276',
    title: 'ダライアスII',
    brand: 'タイトー',
    year: 1989,
    duration: 25,
    difficulty: 'hard',
    concept: 'ブラックホール爆弾が重力場を形成し、周囲の敵を引き寄せる。爆弾展開から3秒後に自動爆発するが、その時点で5体以上が引き寄せられていれば大爆発になる。3秒の間、待てるだけ待って最大数の敵が集まった瞬間にタップして手動起爆。5体以上同時爆破×3回でクリア。',
    objects: [
      { shape: 'circle', role: 'ブラックホール爆弾（重力場）', note: '3秒タイマー付き' },
      { shape: 'face', role: '敵×複数（引き寄せられる）', note: '5体以上で光る' },
      { shape: 'triangle', role: 'シルバーホーク（下部）', note: '' },
    ],
    counters: [
      { id: 'blasts', name: '5体以上同時爆破数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '5体以上集合の瞬間タップ3回',
    failTrigger: '3秒で自動爆発（4体以下）3回で失敗',
  },
  {
    id: 'arcade-277',
    title: 'ガッタンゴットン',
    brand: 'KONAMI',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: '機関車がレールを走っている。レールの先が途切れており、次のレール片をリアルタイムで敷かなければならない。カーブが来るか直線が来るかはコースの形で分かる——「カーブ」か「直線」かのボタンを線路が途切れる前にタップ。ミスすると脱線。5区間でクリア。',
    objects: [
      { shape: 'rect', role: '機関車（前進）', note: '' },
      { shape: 'rect', role: 'レール（先が途切れている）', note: '' },
      { shape: 'button', role: '直線レールボタン', note: '' },
      { shape: 'button', role: 'カーブレールボタン', note: '' },
    ],
    counters: [
      { id: 'sections', name: '区間通過数', target: 5, note: '5区間でクリア' },
    ],
    winTrigger: '正しいレール種を途切れる前にタップ5回',
    failTrigger: 'レール種ミスで脱線3回で失敗',
  },
  {
    id: 'arcade-278',
    title: 'ブランディア',
    brand: 'アルュメ',
    year: 1992,
    duration: 20,
    difficulty: 'normal',
    concept: '魔法戦士の剣が敵の属性攻撃（炎・雷・氷）を吸収して蓄える。蓄えた属性に弱い敵が出現する3秒以内にタップして放出——弱い敵でない間に放出すると無効化され蓄えがリセットされる。吸収→3秒以内に弱敵に放出のサイクルを5回完遂でクリア。',
    objects: [
      { shape: 'diamond', role: '剣（吸収した属性の色で輝く）', note: '3秒カウントダウン' },
      { shape: 'face', role: '属性攻撃を放つ敵→弱敵が出現', note: '' },
      { shape: 'face', role: '魔法戦士（中央）', note: '' },
    ],
    counters: [
      { id: 'releases', name: '吸収放出成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '吸収後3秒以内に弱敵へタップ5回',
    failTrigger: '3秒経過またはミス放出3回で失敗',
  },
  {
    id: 'arcade-279',
    title: 'バーニングフォース',
    brand: 'ナムコ',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: 'スピーダーバイクが高速でコースを走る。ヒートシーカーが敵航空機に向けて自動的にロックオンし始め、1.5秒でロック完了する。しかし敵機は3秒しか画面にいない——ロックオン完了（インジケーターが実線になる）の瞬間にタップして発射。未完了での発射は外れる。5機撃墜でクリア。',
    objects: [
      { shape: 'triangle', role: 'スピーダーバイク（前進）', note: '' },
      { shape: 'triangle', role: '敵航空機（3秒出現）', note: '' },
      { shape: 'circle', role: 'ロックオンインジケーター（点線→実線）', note: '実線で光る' },
    ],
    counters: [
      { id: 'locked', name: 'ロック完了撃墜数', target: 5, note: '5機でクリア' },
    ],
    winTrigger: 'ロックオン実線の瞬間タップ5回',
    failTrigger: 'ロック不完了発射3回で失敗',
  },
  {
    id: 'arcade-280',
    title: '大王',
    brand: 'アテナ',
    year: 1993,
    duration: 20,
    difficulty: 'hard',
    concept: '戦闘機がエネルギー弾を1秒ごとに吸収して内部に蓄積する。5発蓄積した状態でタップするとメガ解放——6発目を吸収するとオーバーロードで爆発失敗。5発溜まったら即タップ。敵弾が来るたびにカウントが増えるため、5で止まる瞬間を逃さないこと。3回メガ解放でクリア。',
    objects: [
      { shape: 'triangle', role: '戦闘機（中央）', note: '' },
      { shape: 'diamond', role: '敵弾（飛来・自動吸収）', note: '' },
      { shape: 'rect', role: '蓄積カウンター（1〜5）', note: '5でタップ、6でアウト' },
    ],
    counters: [
      { id: 'mega', name: 'メガ解放数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'カウンター5でタップ3回',
    failTrigger: 'カウンター6以上（オーバーロード）3回で失敗',
  },
  {
    id: 'arcade-281',
    title: 'ショーリンズロード',
    brand: 'KONAMI',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: '少林寺の修行僧がボールをキックして敵に当てる。ボールは放物線を描くため、高すぎると敵の頭上を通過し、低すぎると手前の地面に当たる。敵の「当たり高さ」インジケーターとボールの軌道が重なるタイミングでタップ。5体撃退でクリア。',
    objects: [
      { shape: 'circle', role: 'ボール（放物線飛行）', note: '' },
      { shape: 'face', role: '少林寺の修行僧（左端）', note: '' },
      { shape: 'face', role: '敵（当たり高さインジケーター付き）', note: '' },
    ],
    counters: [
      { id: 'hit', name: '撃退数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'ボール軌道が敵インジケーターと重なる瞬間タップ5回',
    failTrigger: 'ボール高さズレ3回で失敗',
  },
  {
    id: 'arcade-282',
    title: 'ダイノレックス',
    brand: 'タイトー',
    year: 1992,
    duration: 20,
    difficulty: 'normal',
    concept: '恐竜ファイターが振り返りながら攻撃を変えてくる。背後から忍び寄ってくる敵をテイルスイープで一掃できる——自機の後方に敵が回り込んだとき（レーダーが「後方」を示した瞬間）にタップしてテイルスイープ。正面の敵には正面攻撃が必要。5回テイルスイープでクリア。',
    objects: [
      { shape: 'face', role: 'ダイノレックス（中央）', note: '' },
      { shape: 'circle', role: 'レーダー（敵方向を示す）', note: '後方で光る' },
      { shape: 'face', role: '敵恐竜（背後に回り込む）', note: '' },
    ],
    counters: [
      { id: 'sweeps', name: 'テイルスイープ数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'レーダーが後方を示した瞬間タップ5回',
    failTrigger: '前方敵にテイルスイープ3回で失敗',
  },
  {
    id: 'arcade-283',
    title: 'ワープ&ワープ',
    brand: 'ナムコ',
    year: 1981,
    duration: 20,
    difficulty: 'normal',
    concept: '床にワープホールを開くと、そこへ踏み込んだ敵が反対側の縁から出てきて崖から落ちる。敵がワープホールを踏む直前にホールをタップして開ける——少し早すぎると敵が踏む前にホールが閉じてしまう。ちょうど踏む前の0.3秒にタップ。5体落下でクリア。',
    objects: [
      { shape: 'circle', role: 'ワープホール（タップで出現・3秒後消滅）', note: '' },
      { shape: 'face', role: '敵（ホール方向へ歩く）', note: 'ホール直前0.3秒で光る' },
      { shape: 'rect', role: 'フィールド（縁が崖）', note: '' },
    ],
    counters: [
      { id: 'fallen', name: '落下させた数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '敵が踏む直前0.3秒にタップ5回',
    failTrigger: 'ホールが閉じて敵が素通り3回で失敗',
  },
  {
    id: 'arcade-284',
    title: 'スクランブルフォーメーション',
    brand: 'タイトー',
    year: 1986,
    duration: 20,
    difficulty: 'hard',
    concept: '自機が仲間機をビームで捕まえてフォーメーションを組める。敵基地の弱点はシルエットが示す「3機フォーメーション形状」と一致したときだけ貫通できる。上部に表示された目標シルエットと同じ形に捕まえた仲間機を配置してからタップ。3回形状一致でクリア。',
    objects: [
      { shape: 'triangle', role: '自機（中央）', note: '' },
      { shape: 'triangle', role: '仲間機×2（ビームで捕まえる）', note: '' },
      { shape: 'rect', role: '目標フォーメーションシルエット（上部）', note: '' },
    ],
    counters: [
      { id: 'matched', name: 'フォーメーション一致数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '目標シルエットと形状一致でタップ3回',
    failTrigger: '形状不一致タップ3回で失敗',
  },
  {
    id: 'arcade-285',
    title: 'ポールポジションII',
    brand: 'ナムコ',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: '4コースから1コースを選んで走行するとき、コースごとに異なる「最適トップスピード」がある。スピードメーターがそのコースの最適ゾーン（緑帯）に入ったときにアクセルを維持してタップすることで最短ラップを刻める。速すぎても遅すぎてもタイムが落ちる。3コース連続最適走行でクリア。',
    objects: [
      { shape: 'triangle', role: 'レーシングカー（前進）', note: '' },
      { shape: 'rect', role: 'スピードメーター（最適ゾーン緑帯付き）', note: '' },
      { shape: 'rect', role: 'コース選択（4種類）', note: '' },
    ],
    counters: [
      { id: 'optimal', name: '最適走行コース数', target: 3, note: '3コースでクリア' },
    ],
    winTrigger: '速度が最適ゾーンの状態でタップ3回',
    failTrigger: 'ゾーン外で走行3コースで失敗',
  },
  {
    id: 'arcade-286',
    title: 'ソニックウィングス',
    brand: 'ビデオシステム',
    year: 1992,
    duration: 20,
    difficulty: 'normal',
    concept: 'スペシャル攻撃はメダル5枚収集後に発動できる。スペシャルは画面全体を一掃するが、敵の大編隊が密集しているタイミングで撃てばより多くを倒せる。5体以上が密集した状態を待ってからタップ。3体以下のときに撃つとメダルが無駄になる。3回5体以上一掃でクリア。',
    objects: [
      { shape: 'triangle', role: '自機（下部）', note: '' },
      { shape: 'face', role: '敵×複数（編隊で接近）', note: '5体以上密集で光る' },
      { shape: 'coin', role: 'メダル（収集で5枚に）', note: '' },
    ],
    counters: [
      { id: 'sweeps', name: '5体以上一掃数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '5体以上密集の瞬間タップ3回',
    failTrigger: '4体以下でタップ3回で失敗',
  },
  {
    id: 'arcade-287',
    title: 'ミスティックウォリアーズ',
    brand: 'KONAMI',
    year: 1993,
    duration: 20,
    difficulty: 'normal',
    concept: '忍者が壁に手裏剣を刺してそれを足場に壁走りする。敵が壁の出っ張りの陰に隠れているとき、手裏剣を壁の適切な高さに刺してその位置から飛びつくと陰から排除できる。手裏剣の着地高さが「陰の高さより少し上」に来た瞬間にタップして刺す。5体排除でクリア。',
    objects: [
      { shape: 'diamond', role: '手裏剣（壁に刺さる・足場になる）', note: '' },
      { shape: 'face', role: '忍者（壁走り）', note: '' },
      { shape: 'face', role: '敵（出っ張りの陰）', note: '' },
      { shape: 'rect', role: '壁（出っ張り付き）', note: '' },
    ],
    counters: [
      { id: 'eliminated', name: '排除数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '手裏剣高さが陰の上に来た瞬間タップ5回',
    failTrigger: '高さが合わず陰から出られない3回で失敗',
  },
  {
    id: 'arcade-288',
    title: 'ソリタリーファイター',
    brand: 'タイトー',
    year: 1991,
    duration: 20,
    difficulty: 'hard',
    concept: '格闘家のHPが30%以下になると「バーストレディ」インジケーターが点灯する。相手が攻撃スイングの途中（モーション中）にバーストレディが点灯しているときにタップすると超反撃が炸裂——スイング外や通常HPでは発動しない。3回超反撃でクリア。',
    objects: [
      { shape: 'face', role: '格闘家（HP30%以下）', note: '' },
      { shape: 'rect', role: 'バーストレディインジケーター（点灯）', note: '' },
      { shape: 'face', role: '相手（攻撃スイングモーション）', note: 'スイング中に光る' },
    ],
    counters: [
      { id: 'burst', name: '超反撃数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'バーストレディ点灯+相手スイング中にタップ3回',
    failTrigger: '条件不一致タップ3回で失敗',
  },
] as const;
