/**
 * ideas/arcade-2018.ts
 * Arcade Archives 2018年配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2018Ideas = [
  {
    id: 'arcade-057',
    title: '快傑ヤンチャ丸',
    brand: 'アイレム',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: 'ヤンチャ丸の独楽が壁に当たって跳ね返りながら飛ぶ。跳ね返る直前にタップして軌道を変え、敵の方向へ誘導せよ。5体に命中させてクリア。',
    objects: [
      { shape: 'star', role: '独楽（壁で跳ね返る）', note: '跳ね返り直前にタップで軌道変更' },
      { shape: 'face', role: '敵×5', note: '画面各所に配置' },
    ],
    counters: [
      { id: 'hits', name: '命中数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'counter hits >= 5',
    failTrigger: '制限時間切れ',
  },
  {
    id: 'arcade-058',
    title: '妖獣伝',
    brand: 'アイレム',
    year: 1986,
    duration: 25,
    difficulty: 'hard',
    concept: 'ボスが数秒ごとに形態を変え続けている。各形態には一か所だけ弱点（ほのかに光る箇所）があり、次の形態に変わる前の0.5秒だけ有効。光っている部位をタップして3回ヒットでクリア。',
    objects: [
      { shape: 'face', role: 'ボス（形態変化）', note: '弱点部位が0.5秒だけ光る' },
    ],
    counters: [
      { id: 'hits', name: 'ヒット数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'counter hits >= 3',
    failTrigger: '弱点以外タップ3回で失敗',
  },
  {
    id: 'arcade-059',
    title: 'ムーンパトロール',
    brand: 'アイレム',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: '月面バギーが走る先に2種の障害が交互に現れる。クレーターにはJUMPボタンをタップ、上空のUFO砲撃にはLASERボタンをタップ。どちらの障害か見極めて正しい方を押せ。5障害連続正解でクリア。',
    objects: [
      { shape: 'rect', role: 'クレーター（地面の穴）', note: 'JUMPが必要' },
      { shape: 'diamond', role: 'UFO砲撃（上空）', note: 'LASERが必要' },
      { shape: 'button', role: 'JUMPボタン', note: '' },
      { shape: 'button', role: 'LASERボタン', note: '' },
    ],
    counters: [
      { id: 'cleared', name: '回避数', target: 5, note: '5連続正解でクリア' },
    ],
    winTrigger: 'counter cleared >= 5',
    failTrigger: '誤ったボタンタップで失敗',
  },
  {
    id: 'arcade-060',
    title: 'パンチアウト!!',
    brand: '任天堂',
    year: 1983,
    duration: 20,
    difficulty: 'hard',
    concept: '対戦相手が攻撃前に必ず「予告動作」を見せる（目が光る/肩が上がる/腕が引く）。その動作が何パンチの予告かを見極めて、来る直前に正しい回避方向（左/右/下）をタップ。3回連続回避でクリア。',
    objects: [
      { shape: 'face', role: '対戦相手（予告動作あり）', note: '3種の予告動作' },
      { shape: 'button', role: '左回避ボタン', note: '' },
      { shape: 'button', role: '右回避ボタン', note: '' },
      { shape: 'button', role: 'ダックボタン', note: '' },
    ],
    counters: [
      { id: 'dodges', name: '回避数', target: 3, note: '3回連続でクリア' },
    ],
    winTrigger: 'counter dodges >= 3（連続、失敗でリセット）',
    failTrigger: '誤った方向タップで連続リセット、3回失敗で終了',
  },
  {
    id: 'arcade-061',
    title: '10ヤードファイト',
    brand: 'アイレム',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: '3人のレシーバーが異なるルートを走っている。一人だけ一瞬「OPEN」と光る瞬間がある。その0.5秒以内にそのレシーバーをタップしてパス。3回成功でタッチダウン。',
    objects: [
      { shape: 'face', role: 'レシーバーA（ルート移動）', note: '時々OPENと光る' },
      { shape: 'face', role: 'レシーバーB（ルート移動）', note: '同上' },
      { shape: 'face', role: 'レシーバーC（ルート移動）', note: '同上' },
    ],
    counters: [
      { id: 'passes', name: 'パス成功数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'counter passes >= 3',
    failTrigger: 'OPEN状態以外のレシーバーへタップ3回で失敗',
  },
  {
    id: 'arcade-062',
    title: 'ドンキーコング',
    brand: '任天堂',
    year: 1981,
    duration: 20,
    difficulty: 'normal',
    concept: '樽が坂を転がり落ちてくる。樽には影がついており、影の向きが「左の坂」か「右の坂」かを示している。樽が坂の足元に来た瞬間、影の示す坂側でタップしてジャンプ。5本連続回避でクリア。',
    objects: [
      { shape: 'circle', role: '樽（坂を転がる）', note: '影が次の坂方向を示す' },
      { shape: 'button', role: '左ジャンプボタン', note: '' },
      { shape: 'button', role: '右ジャンプボタン', note: '' },
    ],
    counters: [
      { id: 'dodged', name: '回避数', target: 5, note: '5本連続でクリア' },
    ],
    winTrigger: 'counter dodged >= 5',
    failTrigger: '樽に当たったら失敗',
  },
  {
    id: 'arcade-063',
    title: 'スカイスキッパー',
    brand: '任天堂',
    year: 1981,
    duration: 20,
    difficulty: 'normal',
    concept: '飛行機が建物の周りを旋回する。ゴリラが後ろを向いた瞬間（不注意状態）だけ近づいて捕虜の動物をタップして救出できる。ゴリラが前を向いている時に近づくと撃墜される。3体救出でクリア。',
    objects: [
      { shape: 'triangle', role: '飛行機（旋回）', note: '' },
      { shape: 'face', role: 'ゴリラ（前向き↔後向き切替）', note: '' },
      { shape: 'circle', role: '捕虜の動物×3', note: 'ゴリラ不注意中だけタップ有効' },
    ],
    counters: [
      { id: 'rescued', name: '救出数', target: 3, note: '3体でクリア' },
    ],
    winTrigger: 'counter rescued >= 3',
    failTrigger: 'ゴリラ前向き時に近づいたら撃墜→失敗',
  },
  {
    id: 'arcade-064',
    title: 'オメガファイター',
    brand: 'UPL',
    year: 1989,
    duration: 20,
    difficulty: 'hard',
    concept: 'オメガファイターは至近距離で最大威力を発揮する特殊砲を持つ。敵グループが自機オーラ圏内（最接近）まで引き付けた瞬間にタップしてオメガストライク。その前に撃つと威力が大幅に落ちる。',
    objects: [
      { shape: 'triangle', role: '自機', note: 'オーラ圏を円で表示' },
      { shape: 'circle', role: '敵グループ（接近中）', note: '' },
      { shape: 'button', role: 'オメガストライクボタン', note: '' },
    ],
    counters: [
      { id: 'omegaHits', name: 'オメガ命中数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '敵がオーラ圏内でタップ3回',
    failTrigger: 'オーラ圏外タップ3回で失敗',
  },
  {
    id: 'arcade-065',
    title: 'アーガス',
    brand: 'ジャレコ',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: '自機のバリアが120度の扇形を防護する。敵の弾が3方向から来る。弾が来る方向にバリアを向けてタップして防護。タップするたびにバリアが60度回転する。5発連続ブロックでクリア。',
    objects: [
      { shape: 'triangle', role: '自機', note: 'バリア扇形を表示' },
      { shape: 'circle', role: '敵弾（3方向から飛来）', note: '' },
      { shape: 'button', role: 'バリア回転ボタン', note: 'タップで60度回転' },
    ],
    counters: [
      { id: 'blocks', name: 'ブロック数', target: 5, note: '5連続でクリア' },
    ],
    winTrigger: 'counter blocks >= 5（連続）',
    failTrigger: 'バリアが向いていない方向からの弾で失敗',
  },
  {
    id: 'arcade-066',
    title: 'エキサイトバイク',
    brand: '任天堂',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: 'バイクに登り坂と下り坂が交互に来る。登り坂でタップしてターボON、頂点を越えたらタップしてターボOFF。ONのまま続けると過熱して止まる。3つの丘を過熱なしに乗り越えればクリア。',
    objects: [
      { shape: 'triangle', role: 'バイク（走行）', note: '' },
      { shape: 'rect', role: '過熱ゲージ', note: '上昇し続けたらオーバーヒート' },
      { shape: 'button', role: 'ターボON/OFFボタン', note: '' },
    ],
    counters: [
      { id: 'hills', name: 'クリアした丘数', target: 3, note: '3つでクリア' },
    ],
    winTrigger: 'counter hills >= 3',
    failTrigger: '過熱ゲージMAXで失敗',
  },
  {
    id: 'arcade-067',
    title: 'ASO',
    brand: 'SNK',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: '3種のアーマーパーツ（頭/胴/脚）が画面に浮かぶ。正しい装着順序（頭→胴→脚）で光っているパーツだけをタップして装着完了。誤ったパーツをタップすると全部外れてやり直し。',
    objects: [
      { shape: 'rect', role: '頭パーツ（順番に光る）', note: '' },
      { shape: 'rect', role: '胴パーツ（順番に光る）', note: '' },
      { shape: 'rect', role: '脚パーツ（順番に光る）', note: '' },
    ],
    counters: [
      { id: 'parts', name: '正順装着数', target: 3, note: '3個でクリア' },
    ],
    winTrigger: '頭→胴→脚の順にタップ完了',
    failTrigger: '誤った順序でタップするとリセット、3回で失敗',
  },
  {
    id: 'arcade-068',
    title: 'アーバンチャンピオン',
    brand: '任天堂',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: '路上の喧嘩。相手をマンホールの縁まで追い詰めたら、相手が前のめりに揺れた瞬間にタップして最後の一押し。前のめり以外でタップすると逆に押し返される。3回成功でクリア。',
    objects: [
      { shape: 'face', role: '自キャラ（左）', note: '' },
      { shape: 'face', role: '相手（右・前のめり↔後ろ体重切替）', note: '' },
      { shape: 'rect', role: 'マンホール（右端）', note: '' },
    ],
    counters: [
      { id: 'pushins', name: '落とし数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'counter pushins >= 3',
    failTrigger: '後ろ体重でタップ3回で失敗',
  },
  {
    id: 'arcade-069',
    title: 'ルート16',
    brand: 'サン電子',
    year: 1981,
    duration: 25,
    difficulty: 'normal',
    concept: '車がマップの交差点に差し掛かる。敵車が巡回しており、視野内にいる間は交差点に入れない。敵車が交差点から視野外に出た0.5秒でタップして曲がれ。5か所の交差点を通過してゴールへ。',
    objects: [
      { shape: 'rect', role: '自車（移動）', note: '' },
      { shape: 'rect', role: '敵巡回車（視野表示）', note: '視野が交差点にかかると赤' },
      { shape: 'button', role: '曲がるボタン', note: '' },
    ],
    counters: [
      { id: 'intersections', name: '通過交差点数', target: 5, note: '5か所でクリア' },
    ],
    winTrigger: 'counter intersections >= 5',
    failTrigger: '敵車視野内でタップ3回で失敗',
  },
  {
    id: 'arcade-070',
    title: 'アテナ',
    brand: 'SNK',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: '3つの宝箱が並んでいる。そのうち1つに伝説の剣が入っており、かすかに輝いている。3秒以内に正しい宝箱をタップして入手。外れると3秒のペナルティ待機。3回正解でクリア。',
    objects: [
      { shape: 'rect', role: '宝箱A', note: '' },
      { shape: 'rect', role: '宝箱B', note: '正解はランダムでかすかに輝く' },
      { shape: 'rect', role: '宝箱C', note: '' },
    ],
    counters: [
      { id: 'correct', name: '正解数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'counter correct >= 3',
    failTrigger: '3秒以内に正解できなかった回数3回で失敗',
  },
  {
    id: 'arcade-071',
    title: 'ドンキーコングJR.',
    brand: '任天堂',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: '2本の蔦が左右に揺れている。蔦は互いに異なるリズムで揺れる。右蔦が中央に寄った瞬間に右をタップ、左蔦が中央に寄った瞬間に左をタップして交互に掴みながら登れ。リズムを外すと落下。',
    objects: [
      { shape: 'rect', role: '左蔦（独自リズムで揺れる）', note: '' },
      { shape: 'rect', role: '右蔦（独自リズムで揺れる）', note: '' },
      { shape: 'face', role: 'ドンキーコングJR.', note: '' },
      { shape: 'button', role: '左掴みボタン', note: '' },
      { shape: 'button', role: '右掴みボタン', note: '' },
    ],
    counters: [
      { id: 'grabs', name: '掴み数', target: 10, note: '10回で頂上到達→クリア' },
    ],
    winTrigger: 'counter grabs >= 10',
    failTrigger: 'リズムを外してタップ3回で落下→失敗',
  },
] as const;
