/**
 * ideas/arcade-2023q1.ts
 * Arcade Archives 2023年1〜3月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2023q1Ideas = [
  {
    id: 'arcade-238',
    title: 'ギャラガ',
    brand: 'ナムコ',
    year: 1981,
    duration: 20,
    difficulty: 'normal',
    concept: '敵ギャラガが宙返りルートを描いて飛行している。ルート上に「交差点」が1か所あり、異なる方向から来た3機が同時に通過する瞬間がある。その瞬間にタップして1発で3機まとめて撃墜。3機が揃う前に撃つと1〜2機しか当たらない。3回の3機同時撃墜でクリア。',
    objects: [
      { shape: 'triangle', role: 'ギャラガ×複数（ループルート飛行）', note: '交差点で3機が光る' },
      { shape: 'triangle', role: '自機（下部）', note: '' },
    ],
    counters: [
      { id: 'triples', name: '3機同時撃墜数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '交差点に3機揃った瞬間タップ3回',
    failTrigger: '2機以下で撃墜3回で失敗',
  },
  {
    id: 'arcade-239',
    title: 'SENJYO',
    brand: 'テーカン',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: '遠近感のある3D道路上を敵戦車が近づいてくる。照準リングが遠い敵では大きく、近い敵では小さくなる。最大威力が出るのは照準リングが戦車の正確な幅と一致した「中距離」のみ。リングと戦車のサイズが完全一致した瞬間にタップして発射。5体撃破でクリア。',
    objects: [
      { shape: 'circle', role: '照準リング（距離で大きさ変化）', note: '一致すると光る' },
      { shape: 'rect', role: '敵戦車（3D遠近感で接近）', note: '' },
      { shape: 'triangle', role: '自機（手前・固定）', note: '' },
    ],
    counters: [
      { id: 'hit', name: '精密命中数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '照準と戦車サイズ一致の瞬間タップ5回',
    failTrigger: 'サイズ不一致タップ3回で失敗',
  },
  {
    id: 'arcade-240',
    title: 'タンクフォース',
    brand: 'ナムコ',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: '基地の門に向かってくる敵タンクを、スチール壁を経由したリコシェット（跳弾）で倒す。直接は狙えない角度にいる敵に対して、壁の反射後の軌道が敵に当たるよう照準を合わせてタップ。反射後の軌道（点線）が敵に重なった瞬間が撃つタイミング。3体撃破でクリア。',
    objects: [
      { shape: 'rect', role: '自軍タンク（左端）', note: '' },
      { shape: 'rect', role: 'スチール壁（反射）', note: '' },
      { shape: 'diamond', role: 'リコシェット軌道（点線）', note: '敵と重なると光る' },
      { shape: 'rect', role: '敵タンク（壁の陰）', note: '' },
    ],
    counters: [
      { id: 'rico', name: 'リコシェット撃破数', target: 3, note: '3体でクリア' },
    ],
    winTrigger: 'counter rico >= 3',
    failTrigger: '直射3回で失敗',
  },
  {
    id: 'arcade-241',
    title: 'ニュージーランドストーリー',
    brand: 'タイトー',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: 'ティキの矢が放物線を描いて飛ぶ。天井に吊るされた風船の紐（ひも）を切ると友達が落下して救出できる。風船本体を撃つと爆発して友達が落ちてしまう——矢の弧の頂点が紐の部分（風船の下）に重なるタイミングでタップ。5人救出でクリア。',
    objects: [
      { shape: 'balloon', role: '風船（天井から吊り下げ）', note: '紐の部分が当たり判定' },
      { shape: 'face', role: '友達（風船の中）', note: '' },
      { shape: 'diamond', role: '矢の弧軌道（頂点が紐と重なると光る）', note: '' },
      { shape: 'face', role: 'ティキ（左端）', note: '' },
    ],
    counters: [
      { id: 'rescued', name: '救出数', target: 5, note: '5人でクリア' },
    ],
    winTrigger: '矢の頂点が紐部分の瞬間タップ5回',
    failTrigger: '風船本体を撃って3回で失敗',
  },
  {
    id: 'arcade-242',
    title: 'フェリオス',
    brand: 'ナムコ',
    year: 1989,
    duration: 20,
    difficulty: 'hard',
    concept: 'アルテミスが回転しながら矢を全方向へ放射する。敵が同じ方向から3本同時に矢を放ってくる瞬間がある。その方向に向けた盾スピンで3本まとめて弾き返せる——1〜2本の時は弾いても無駄。3本同時の方向を確認してからタップ。3回3本同時ブロックでクリア。',
    objects: [
      { shape: 'face', role: 'アルテミス（中央）', note: '' },
      { shape: 'diamond', role: '敵の矢×複数（各方向から飛来）', note: '3本同方向時に光る' },
      { shape: 'circle', role: '盾スピン（タップで発動）', note: '' },
    ],
    counters: [
      { id: 'blocks', name: '3本同時ブロック数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3本同方向の瞬間タップ3回',
    failTrigger: '1〜2本時にタップ3回で失敗',
  },
  {
    id: 'arcade-243',
    title: 'まじかるスピード',
    brand: 'アルュメ',
    year: 1994,
    duration: 20,
    difficulty: 'normal',
    concept: '魔法レーサーが高速コースを走っている。マジックゲートが出現し、ゲートの中心（ゴールドゾーン）を通過すると速度ブーストが最大になる。両端のシルバーゾーンを通ると半分のブーストしか得られない。ゲートが近づくにつれて中心を狙ってタップ。5回ゴールドゾーン通過でクリア。',
    objects: [
      { shape: 'triangle', role: '魔法レーサー（前進）', note: '' },
      { shape: 'rect', role: 'マジックゲート（ゴールド中心/シルバー端）', note: '' },
    ],
    counters: [
      { id: 'gold', name: 'ゴールドゾーン通過数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'ゴールドゾーン通過でタップ5回',
    failTrigger: 'シルバーゾーン通過3回で失敗',
  },
  {
    id: 'arcade-244',
    title: 'グロブダー',
    brand: 'ナムコ',
    year: 1984,
    duration: 20,
    difficulty: 'hard',
    concept: 'グロブダーが敵タンクを倒すとエネルギーが充填され、最大充填でメガブラストが自動発動する。広い場所でメガブラストを発動しても当たる敵が少ない——最後の1体を倒す前に残り敵を中央に引き付け、3体以上が密集してからタップして最後の1体を仕留めてメガブラスト。3回密集ブラストでクリア。',
    objects: [
      { shape: 'rect', role: 'グロブダー（中央）', note: '' },
      { shape: 'rect', role: '敵タンク×複数（移動）', note: '3体以上密集で光る' },
      { shape: 'rect', role: 'エネルギーゲージ（充填中）', note: 'MAXでメガブラスト' },
    ],
    counters: [
      { id: 'blasts', name: '密集メガブラスト数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3体以上密集＋エネルギーMAXでタップ3回',
    failTrigger: '1〜2体散開状態でブラスト3回で失敗',
  },
  {
    id: 'arcade-245',
    title: 'ドンドコドン',
    brand: 'タイトー',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: 'ドワーフがハンマーで敵をスタンさせると、その敵を持ち上げて投げられる。別の敵が接近しているとき、スタンした敵を投げつけて連鎖撃破を狙う。投げる方向に敵2体目が来た瞬間にタップして投擲——方向を間違えると壁に当たって終わり。5回連鎖でクリア。',
    objects: [
      { shape: 'face', role: 'スタンした敵（持ち上げ可）', note: '' },
      { shape: 'face', role: '2体目の敵（接近中）', note: '投擲方向に来ると光る' },
      { shape: 'face', role: 'ドワーフ（左端）', note: '' },
    ],
    counters: [
      { id: 'chains', name: '連鎖撃破数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'counter chains >= 5',
    failTrigger: '壁に投擲3回で失敗',
  },
  {
    id: 'arcade-246',
    title: 'スカイキッドDX',
    brand: 'ナムコ',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: '複葉機が逆さまになって爆弾を投下するシーン。逆さ飛行中は画面が上下反転して見える。目標艦が動いており、逆さ状態の機体の「影」が目標の真上を通過した瞬間にタップして投下。正面飛行の感覚で逆算して判断せよ。3回直撃でクリア。',
    objects: [
      { shape: 'triangle', role: '複葉機（逆さ飛行）', note: '' },
      { shape: 'circle', role: '爆弾（投下後に落下）', note: '' },
      { shape: 'rect', role: '目標艦（移動）', note: '' },
      { shape: 'diamond', role: '機体の影（地上に投影）', note: '目標と重なると光る' },
    ],
    counters: [
      { id: 'hits', name: '直撃数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '影と目標が重なった瞬間タップ3回',
    failTrigger: '外れ投下3回で失敗',
  },
  {
    id: 'arcade-247',
    title: 'ターボフォース',
    brand: 'ビデオシステム',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: 'レーシングカーが高速でカーブを攻める。2台のライバル車がバンクカーブの内側と外側をふさいでいる。2台の間隔がわずかに広がる「すり抜けギャップ」の瞬間、バンキングアングルインジケーターが正しい傾き角を示す——インジケーターがギャップの傾きと一致したときにタップ。5回通過でクリア。',
    objects: [
      { shape: 'triangle', role: '自車（後方）', note: '' },
      { shape: 'rect', role: 'ライバル車×2（内外をふさぐ）', note: '' },
      { shape: 'rect', role: 'バンキングアングルインジケーター', note: 'ギャップ角と一致で光る' },
    ],
    counters: [
      { id: 'passes', name: 'ギャップ通過数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'インジケーター一致の瞬間タップ5回',
    failTrigger: '角度ズレで激突3回で失敗',
  },
  {
    id: 'arcade-248',
    title: '3DサンダーセプターII',
    brand: 'ナムコ',
    year: 1986,
    duration: 20,
    difficulty: 'hard',
    concept: '3Dトンネルを飛行中、敵が正面から接近してくる。照準の「フォーカスリング」が遠い敵には大きく、近い敵には小さく収縮する。最大ダメージはフォーカスリングが敵の外形と完全に一致したときだけ——一致の瞬間にタップして発射。5回精密射撃でクリア。',
    objects: [
      { shape: 'circle', role: 'フォーカスリング（収縮中）', note: '敵の外形と一致で光る' },
      { shape: 'face', role: '敵（3D接近）', note: '' },
      { shape: 'triangle', role: 'サンダーセプターII（中央）', note: '' },
    ],
    counters: [
      { id: 'precise', name: '精密射撃数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'フォーカスリング=敵外形の瞬間タップ5回',
    failTrigger: 'リングズレ射撃3回で失敗',
  },
  {
    id: 'arcade-249',
    title: '地獄めぐり',
    brand: 'タイトー',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '僧侶が神社でお祈りすると霊力が宿る（3秒間）。霊力がある間だけ霊体の妖怪にお札が通じる。神社でタップしてお祈り→霊力ウィンドウ3秒以内に妖怪をタップして撃退。霊力が切れた後の妖怪タップは無効。5体撃退でクリア。',
    objects: [
      { shape: 'circle', role: '神社（タップでお祈り）', note: '霊力3秒タイマー' },
      { shape: 'face', role: '妖怪（霊体）', note: '霊力中は色が変わる' },
      { shape: 'face', role: '僧侶（移動）', note: '' },
    ],
    counters: [
      { id: 'exorcised', name: '退治数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'お祈り→霊力3秒以内タップの2段階×5体',
    failTrigger: '霊力切れ状態での妖怪タップ3回で失敗',
  },
  {
    id: 'arcade-250',
    title: 'ナバロン',
    brand: 'ナムコ',
    year: 1980,
    duration: 20,
    difficulty: 'normal',
    concept: '固定砲台が左右に首を振っている。敵が複数の高度から波状攻撃してくる。砲台の向きが「複数の敵が最も密集した高度」に重なった瞬間だけ発射すれば複数まとめて撃破できる。3体以上が砲台の射線に揃った瞬間にタップ。3回3体以上撃破でクリア。',
    objects: [
      { shape: 'rect', role: '固定砲台（左右首振り）', note: '' },
      { shape: 'triangle', role: '敵×複数（各高度から侵入）', note: '3体以上射線上で光る' },
    ],
    counters: [
      { id: 'multi', name: '3体以上同時撃破数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '射線上3体以上の瞬間タップ3回',
    failTrigger: '2体以下での発射3回で失敗',
  },
] as const;
