/**
 * ideas/arcade-2025q2.ts
 * Arcade Archives 2025年4〜6月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2025q2Ideas = [
  {
    id: 'arcade-354',
    title: 'アサルトプラス',
    brand: 'ナムコ',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: 'タンクが急傾斜の坂を登り、坂の頂点で「前輪が浮く瞬間（無重力の0.3秒）」がある。その瞬間にタップして砲塔を最大仰角まで上げると谷の向こうの標的に届く放物線弾道になる——浮く前後では仰角が足りない。3回長距離砲撃でクリア。',
    objects: [
      { shape: 'rect', role: 'タンク（坂を登る）', note: '前輪浮きの瞬間に光る' },
      { shape: 'rect', role: '急傾斜の坂', note: '' },
      { shape: 'star', role: '遠方の標的（谷の向こう）', note: '' },
    ],
    counters: [
      { id: 'shots', name: '長距離砲撃数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '前輪浮きの0.3秒にタップ3回',
    failTrigger: '浮き前後にタップ3回で失敗',
  },
  {
    id: 'arcade-355',
    title: 'クレイジーコップ',
    brand: 'KONAMI',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '前方の犯罪者の車がタイヤのグリップ音を出しながら曲がる準備をしている。グリップ音が「最大音量」に達した瞬間（右折か左折かが確定する瞬間）にタップして追跡方向を合わせる——最大音量前に判断すると逆方向へ進んでしまう。5回追跡成功でクリア。',
    objects: [
      { shape: 'rect', role: '犯罪者の車（前方）', note: 'グリップ音最大時に光る' },
      { shape: 'rect', role: '警察カー（中央）', note: '' },
      { shape: 'rect', role: '音量インジケーター', note: '' },
    ],
    counters: [
      { id: 'chases', name: '追跡成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'グリップ音最大の瞬間タップ5回',
    failTrigger: '最大前に判断3回で失敗',
  },
  {
    id: 'arcade-356',
    title: '戦え!ビッグファイター',
    brand: '日本物産',
    year: 1989,
    duration: 20,
    difficulty: 'hard',
    concept: '超エネルギーが右回りの渦を形成する。渦の目（中心点）が体の中心と一致した瞬間にタップして必殺技を放つ——渦の目が中心からズレていると暴発して逆ダメージになる。渦は高速で回転するので中心一致の瞬間を正確に見極める。3回必殺技でクリア。',
    objects: [
      { shape: 'circle', role: '超エネルギーの渦（回転）', note: '渦の目が中心一致で光る' },
      { shape: 'face', role: 'ビッグファイター（中央）', note: '' },
      { shape: 'face', role: '対戦相手（前方）', note: '' },
    ],
    counters: [
      { id: 'specials', name: '必殺技数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '渦の目が中心一致の瞬間タップ3回',
    failTrigger: '渦の目ズレでタップ3回で失敗',
  },
  {
    id: 'arcade-357',
    title: 'ピンボールアクション',
    brand: 'テーカン',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: 'ボールが落下してフリッパーに向かってくる。ボールの落下速度から計算した「ジャストヒットポイント（最適打撃点）」が光っている——ボールがジャストヒットポイントを通過した瞬間にタップしてフリッパーを弾く。通過前は空振り、通過後は弱々しい当たりになる。5回ジャストヒットでクリア。',
    objects: [
      { shape: 'circle', role: 'ピンボール（落下中）', note: '' },
      { shape: 'star', role: 'ジャストヒットポイント（光る）', note: 'ボール通過時に最大光' },
      { shape: 'rect', role: 'フリッパー（下部）', note: '' },
    ],
    counters: [
      { id: 'hits', name: 'ジャストヒット数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'ボールがジャストポイント通過の瞬間タップ5回',
    failTrigger: '通過前後にタップ3回で失敗',
  },
  {
    id: 'arcade-358',
    title: 'スーパーゼビウス',
    brand: 'ナムコ',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: 'スペシャルフラッグが地中から浮上してくる。地表に出てきた瞬間の1秒だけが撃てるウィンドウ——完全に地表から出てきた瞬間（露出した0.1秒後）にタップして撃つと高得点ボーナスが発生する。地中にいる間は撃てない。5回地表出現タイミング撃墜でクリア。',
    objects: [
      { shape: 'star', role: 'スペシャルフラッグ（地中から浮上）', note: '地表出現の瞬間に光る' },
      { shape: 'rect', role: '地面（浮上前は隠れている）', note: '' },
      { shape: 'triangle', role: 'ソルバルウ（上部）', note: '' },
    ],
    counters: [
      { id: 'hits', name: '地表出現撃墜数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '地表出現直後1秒以内にタップ5回',
    failTrigger: '地中や出現後1秒超でタップ3回で失敗',
  },
  {
    id: 'arcade-359',
    title: 'パンクショット',
    brand: 'KONAMI',
    year: 1990,
    duration: 20,
    difficulty: 'normal',
    concept: 'パンクショットで相手のブロックを突き破る。相手のブロック手が最高点（真上）に達した瞬間——手がリングの高さを超えた「腕の真上」にタップしてボールをパンチ発動。ブロック手が真上以外にある時はボールを弾かれる。3回パンクショット成功でクリア。',
    objects: [
      { shape: 'circle', role: 'バスケットボール（空中）', note: '' },
      { shape: 'face', role: '相手選手（ブロック中）', note: '手が真上の瞬間に光る' },
      { shape: 'face', role: '自選手（中央）', note: '' },
    ],
    counters: [
      { id: 'punks', name: 'パンクショット数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '相手の手が真上に来た瞬間タップ3回',
    failTrigger: '手が真上以外でタップ3回で失敗',
  },
  {
    id: 'arcade-360',
    title: 'ネビュラスレイ',
    brand: 'ナムコ',
    year: 1994,
    duration: 20,
    difficulty: 'hard',
    concept: '敵密集群の中に「起点」になる1体だけが光っている——その起点の敵から放電すると連鎖電撃が全体に広がる。起点の敵が光った瞬間にタップして放電すると最大連鎖が発動。起点以外の敵を狙うと連鎖が途中で止まる。3回最大連鎖でクリア。',
    objects: [
      { shape: 'star', role: '起点の敵（1体だけ光る）', note: '連鎖の出発点' },
      { shape: 'face', role: '敵密集群（複数）', note: '' },
      { shape: 'triangle', role: 'ネビュラスレイ自機（下部）', note: '' },
    ],
    counters: [
      { id: 'chains', name: '最大連鎖数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '起点が光った瞬間タップ3回',
    failTrigger: '起点以外を狙って3回で失敗',
  },
  {
    id: 'arcade-361',
    title: '琉球',
    brand: 'サクセス',
    year: 1990,
    duration: 20,
    difficulty: 'normal',
    concept: '積み上がったパイ（麻雀牌）が崩れ始める瞬間がある。最上部の1枚目が傾き始める「直前0.3秒」にタップして支え木を差し込むと崩壊を止められる——傾き始めてからでは間に合わない。傾く前に早めに差し込んでも固定できない。5回崩壊防止でクリア。',
    objects: [
      { shape: 'rect', role: '牌の積み上がり（崩れそう）', note: '崩壊直前0.3秒に光る' },
      { shape: 'rect', role: '支え木（差し込む）', note: '' },
    ],
    counters: [
      { id: 'saves', name: '崩壊防止数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '崩壊直前0.3秒にタップ5回',
    failTrigger: '傾き後タップ3回で失敗',
  },
  {
    id: 'arcade-362',
    title: 'スーパーワールドコート',
    brand: 'ナムコ',
    year: 1993,
    duration: 20,
    difficulty: 'normal',
    concept: '相手がレシーブ体勢を変える「動き出しの瞬間（体重移動開始）」を読んで逆方向にサーブする。相手が動き始めた瞬間にタップして逆コーナーに打つと完全に裏をかいたエース——動き切ってから打つと完全に読まれて返される。5回エースでクリア。',
    objects: [
      { shape: 'face', role: '相手選手（構えを変える）', note: '動き出し瞬間に光る' },
      { shape: 'circle', role: 'テニスボール（サーブ待機）', note: '' },
      { shape: 'face', role: '自選手（サーブ側）', note: '' },
    ],
    counters: [
      { id: 'aces', name: 'エース数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '相手動き出しの瞬間にタップ5回',
    failTrigger: '動き切ってからタップ3回で失敗',
  },
  {
    id: 'arcade-363',
    title: 'リッジレーサー',
    brand: 'ナムコ',
    year: 1993,
    duration: 20,
    difficulty: 'hard',
    concept: 'コーナーでタイヤが「グリップ限界点」に達するとスキール音が鳴り始める——スキール音が鳴り始めた瞬間にタップしてカウンターステアを当てるとクリーンドリフトになる。鳴る前に切るとアンダーステア、鳴り出してから0.5秒以上経つとスピン。3回クリーンドリフトでクリア。',
    objects: [
      { shape: 'rect', role: 'リッジレーサー（コーナリング中）', note: '' },
      { shape: 'rect', role: 'スキール音インジケーター', note: '鳴り始めの瞬間に光る' },
      { shape: 'rect', role: 'コーナー（カーブした道）', note: '' },
    ],
    counters: [
      { id: 'drifts', name: 'クリーンドリフト数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'スキール音鳴り始めの瞬間タップ3回',
    failTrigger: '鳴る前や0.5秒超でタップ3回で失敗',
  },
  {
    id: 'arcade-364',
    title: 'スパイナルブレーカーズ',
    brand: 'ビデオシステム',
    year: 1991,
    duration: 20,
    difficulty: 'hard',
    concept: '相手の背骨が「最大湾曲（くの字の最深点）」になった瞬間だけ脊椎への打撃が有効になる——背骨が最大湾曲の0.2秒にタップしてスパイナルブレイク。背骨が真っ直ぐの時に打っても効かず、湾曲の途中でも不完全。5回スパイナルブレイクでクリア。',
    objects: [
      { shape: 'face', role: '相手（背骨が湾曲する）', note: '最大湾曲時に背骨が光る' },
      { shape: 'face', role: '自キャラ（後方）', note: '' },
    ],
    counters: [
      { id: 'breaks', name: 'スパイナルブレイク数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '背骨最大湾曲の0.2秒にタップ5回',
    failTrigger: '湾曲不足時タップ3回で失敗',
  },
  {
    id: 'arcade-365',
    title: 'ストラテジーX',
    brand: 'KONAMI',
    year: 1981,
    duration: 20,
    difficulty: 'normal',
    concept: '地雷原を進むタンク。地雷は一定周期で地中に完全に沈む（地表から消える）瞬間がある——地雷が地中に完全に沈んだ瞬間（地表の波紋が消えた直後）にタップして前進。地表に出ている間に前進すると踏んでしまう。5回安全前進でクリア。',
    objects: [
      { shape: 'circle', role: '地雷（地中と地表を行き来）', note: '地中に沈んだ瞬間に消える' },
      { shape: 'rect', role: 'タンク（前進待機）', note: '' },
    ],
    counters: [
      { id: 'advances', name: '安全前進数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '地雷が地中に沈んだ瞬間タップ5回',
    failTrigger: '地表にある間前進3回で失敗',
  },
  {
    id: 'arcade-366',
    title: 'クレイジーバルーン',
    brand: 'タイトー',
    year: 1980,
    duration: 20,
    difficulty: 'normal',
    concept: '通路の壁に「突起（トゲ）」があり、周期的に壁に引っ込む（収縮する）。突起が完全に壁の中に引っ込んだ瞬間（地表から消えた直後0.3秒）にタップしてバルーンを通過させる——突起が出ている間は触れると破裂する。5回安全通過でクリア。',
    objects: [
      { shape: 'triangle', role: '突起・トゲ（収縮する）', note: '完全収縮時に消える' },
      { shape: 'balloon', role: 'バルーン（進行中）', note: '' },
      { shape: 'rect', role: '通路の壁', note: '' },
    ],
    counters: [
      { id: 'passes', name: '安全通過数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '突起が完全に引っ込んだ瞬間タップ5回',
    failTrigger: '突起が出ている間にタップ3回で失敗',
  },
] as const;
