/**
 * ideas/arcade-2020q2.ts
 * Arcade Archives 2020年4〜6月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2020q2Ideas = [
  {
    id: 'arcade-111',
    title: 'ティンスター',
    brand: 'タイトー',
    year: 1983,
    duration: 20,
    difficulty: 'hard',
    concept: '無法者との早撃ち対決。相手の手がホルスターへ向かって動き始めた「第一フレーム」を見極めてタップ。動き出す前のタップは「フライング」で即失格。動き出した瞬間に反応することだけが正解。3回勝利でクリア。',
    objects: [
      { shape: 'face', role: '無法者（右側）', note: 'ホルスターへの手の動きがアニメ' },
      { shape: 'face', role: '保安官（左側）', note: '' },
      { shape: 'button', role: '抜き打ちボタン', note: '' },
    ],
    counters: [
      { id: 'wins', name: '決闘勝利数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '相手の動き出し後0.3秒以内にタップ3回',
    failTrigger: '動き出し前のフライングタップで即失敗',
  },
  {
    id: 'arcade-112',
    title: 'プラスアルファ',
    brand: 'ジャレコ',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: 'パワーアップカプセルが画面に落下してくる。各カプセルには「+1」「+2」「+3」「-1」「-2」の数値が書かれている。現在スコアと目標スコアが表示されており、目標にぴったり合わせるカプセルだけをタップして収集。オーバーも不足も失敗。3回目標達成でクリア。',
    objects: [
      { shape: 'circle', role: 'カプセル×5（落下・数値付き）', note: '+1/+2/+3/-1/-2' },
      { shape: 'rect', role: 'スコアゲージ（現在値/目標値）', note: '' },
    ],
    counters: [
      { id: 'exact', name: '目標一致数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'スコアが目標値にぴったり一致3回',
    failTrigger: '目標オーバーまたは時間切れ3回で失敗',
  },
  {
    id: 'arcade-113',
    title: 'チューブパニック',
    brand: 'ニチブツ',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: '円形チューブの中を自機が飛んでいる。チューブ断面が迫ってくるたびに壁の一部に通過口が開いている——上・右・下・左の4か所のどこかに隙間がある。隙間の方向をタップして通過せよ。間違えると壁に激突。5壁通過でクリア。',
    objects: [
      { shape: 'triangle', role: '自機（中央）', note: '' },
      { shape: 'circle', role: 'チューブ断面（近づいてくる）', note: '4か所のうち1か所が隙間' },
      { shape: 'button', role: '上ボタン', note: '' },
      { shape: 'button', role: '右ボタン', note: '' },
      { shape: 'button', role: '下ボタン', note: '' },
      { shape: 'button', role: '左ボタン', note: '' },
    ],
    counters: [
      { id: 'passed', name: '通過数', target: 5, note: '5壁でクリア' },
    ],
    winTrigger: 'counter passed >= 5',
    failTrigger: '壁に激突3回で失敗',
  },
  {
    id: 'arcade-114',
    title: 'VS.レッキングクルー',
    brand: '任天堂',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: 'ビルの解体作業。壁パネルのうち「支柱」に隣接しているパネルは壊すと上階が崩落する（赤マーカー付き）。支柱から離れたパネル（緑マーカー）だけを順番にタップして安全に解体せよ。赤パネルを叩くと即崩落失敗。5枚安全解体でクリア。',
    objects: [
      { shape: 'face', role: 'マリオ（ハンマー持ち）', note: '' },
      { shape: 'rect', role: '安全パネル（緑マーカー）', note: 'タップで破壊' },
      { shape: 'rect', role: '危険パネル（赤マーカー）', note: 'タップ禁止' },
      { shape: 'rect', role: '支柱（固定）', note: '' },
    ],
    counters: [
      { id: 'safe', name: '安全解体数', target: 5, note: '5枚でクリア' },
    ],
    winTrigger: 'counter safe >= 5',
    failTrigger: '危険パネルを叩いたら即失敗',
  },
  {
    id: 'arcade-115',
    title: 'ラジカルラジアル',
    brand: 'ニチブツ',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: 'レーシングカーが円形コースを周回している。ダッシュボードに角度ダイヤルが表示されており、針が「パワーゾーン」（最適加速角度）を通過した瞬間にタップして加速ブーストを発動。ゾーン外のタップは空吹かしでタイムロス。5回ブースト成功でクリア。',
    objects: [
      { shape: 'triangle', role: 'レーシングカー（周回）', note: '' },
      { shape: 'circle', role: '角度ダイヤル（針が回転）', note: 'パワーゾーン帯が光る' },
      { shape: 'button', role: 'ブーストボタン', note: '' },
    ],
    counters: [
      { id: 'boosts', name: 'ブースト成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '針がパワーゾーン内でタップ5回',
    failTrigger: 'ゾーン外タップ3回で失敗',
  },
  {
    id: 'arcade-116',
    title: 'ノーティボーイ',
    brand: 'ジャレコ',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: '少年がボールを壁に向けて投げる。ボールは壁で跳ね返って別の方向へ飛んでいく——跳ね返り先の軌道が点線で予測表示される。点線の先に敵が重なったタイミングでタップして投擲。敵の位置が変わるたびに跳ね返り角度も変わる。5体撃退でクリア。',
    objects: [
      { shape: 'face', role: '少年（下部固定）', note: '' },
      { shape: 'circle', role: 'ボール（壁で跳ね返る）', note: '' },
      { shape: 'rect', role: '壁（跳ね返り）', note: '' },
      { shape: 'diamond', role: '跳ね返り軌道（点線）', note: '敵と重なると光る' },
      { shape: 'face', role: '敵（移動）', note: '' },
    ],
    counters: [
      { id: 'hit', name: '撃退数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'counter hit >= 5',
    failTrigger: '軌道外れ投擲3回で失敗',
  },
  {
    id: 'arcade-117',
    title: 'サンセットライダーズ',
    brand: 'KONAMI',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: '画面上部に指名手配ポスターが1枚掲示される（特徴：帽子の色・髭の有無・服の色）。5人の無法者が横一列に並んで現れる——ポスターと一致する人物は1人だけ。1.5秒以内に正しい人物をタップして賞金首を確保。間違いは一般市民への誤射。3人確保でクリア。',
    objects: [
      { shape: 'face', role: '無法者×5（横一列）', note: '各自異なる外見' },
      { shape: 'rect', role: '指名手配ポスター（上部）', note: '特徴3点表示' },
    ],
    counters: [
      { id: 'captured', name: '賞金首確保数', target: 3, note: '3人でクリア' },
    ],
    winTrigger: 'counter captured >= 3',
    failTrigger: '一般市民への誤射3回で失敗',
  },
  {
    id: 'arcade-118',
    title: 'VS.ベースボール',
    brand: '任天堂',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: 'ピッチャーが投球モーションを取る。球種アイコン（ストレート/カーブ/チェンジアップ）と球速が表示される。球がホームベースに到達するまでの時間を逆算してタップ。球種によって到達時間が異なる——ストレートは早め、カーブは遅めにタップ。3安打でクリア。',
    objects: [
      { shape: 'face', role: 'ピッチャー（投球モーション）', note: '' },
      { shape: 'circle', role: 'ボール（飛来）', note: '' },
      { shape: 'diamond', role: '球種アイコン', note: 'ストレート/カーブ/チェンジアップ' },
      { shape: 'button', role: 'バットスイングボタン', note: '' },
    ],
    counters: [
      { id: 'hits', name: '安打数', target: 3, note: '3安打でクリア' },
    ],
    winTrigger: 'counter hits >= 3',
    failTrigger: '三振3回で失敗',
  },
  {
    id: 'arcade-119',
    title: 'ウィズ',
    brand: 'セイブ開発',
    year: 1985,
    duration: 20,
    difficulty: 'hard',
    concept: '魔法使いが呪文を詠唱する。発射された魔法弾が空中の3つの魔法陣（リング）を順番に通過することで威力が増幅される。各リングは短時間だけ開く——弾がリング前に来た瞬間にタップしてリングを開け。3リング全て通過させると最大威力の呪文が炸裂。3回成功でクリア。',
    objects: [
      { shape: 'face', role: '魔法使い（左端）', note: '' },
      { shape: 'circle', role: '魔法弾（右へ飛行）', note: '' },
      { shape: 'circle', role: '魔法陣×3（一列に配置）', note: '弾接近時にタップで開く' },
      { shape: 'face', role: '敵（右端）', note: '' },
    ],
    counters: [
      { id: 'maxspells', name: '最大威力呪文数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3リング全通過×3回',
    failTrigger: 'リングを1つでも閉じたまま通過3回で失敗',
  },
] as const;
