/**
 * ideas/arcade-2025q4.ts
 * Arcade Archives 2025年10〜12月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2025q4Ideas = [
  {
    id: 'arcade-380',
    title: 'ジービー',
    brand: 'ナムコ',
    year: 1978,
    duration: 20,
    difficulty: 'normal',
    concept: 'ボールを弾いてターゲットブロックに当てる。フリッパーの「最適角度（3通りのうち正解の1通り）」がターゲット方向に向いた瞬間に光る——光った瞬間にタップしてフリッパーを固定すると、次のボールをタップで弾いた時にターゲットに一直線で飛ぶ。角度を外すと外れる。5回ターゲット命中でクリア。',
    objects: [
      { shape: 'circle', role: 'ボール（落下中）', note: '' },
      { shape: 'rect', role: 'フリッパー（角度が変わる）', note: '最適角度時に光る' },
      { shape: 'star', role: 'ターゲットブロック（上部）', note: '' },
    ],
    counters: [
      { id: 'hits', name: 'ターゲット命中数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'フリッパーが最適角度に来た瞬間タップ→ボールを弾く×5回',
    failTrigger: '角度が外れた状態で弾く3回で失敗',
  },
  {
    id: 'arcade-381',
    title: 'バトランティス',
    brand: 'KONAMI',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '地面から敵が浮上してくる際に「浮上エフェクト（地面の波紋）」が広がる。波紋が最大に広がった瞬間——波紋の外縁が最大半径に達した瞬間に対地爆弾をタップして投下すると波紋の内側に確実に命中する。波紋より外に落ちると無効化される。5回浮上時命中でクリア。',
    objects: [
      { shape: 'circle', role: '地面波紋（広がる）', note: '最大半径時に光る' },
      { shape: 'face', role: '浮上中の敵（波紋の中心）', note: '' },
      { shape: 'triangle', role: '自機（上空）', note: '' },
    ],
    counters: [
      { id: 'hits', name: '浮上時命中数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '波紋が最大半径に達した瞬間タップ5回',
    failTrigger: '波紋外に落下3回で失敗',
  },
  {
    id: 'arcade-382',
    title: 'ジョイフルロード',
    brand: 'SNK',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: '食べ物が散らばるフィールドをキャラが走っている。キャラと食べ物が「完全重なり（通過音が高くなる瞬間）」になった時にタップして食べる——通過音が低い（食べ物からズレている）時にタップしても空振り。食べ物の中心と完全重なった瞬間だけが食べられる。5回完全重なり食べでクリア。',
    objects: [
      { shape: 'star', role: '食べ物（フィールドに散らばる）', note: '完全重なりで光る' },
      { shape: 'face', role: 'キャラクター（走る）', note: '' },
      { shape: 'rect', role: '通過音インジケーター', note: '' },
    ],
    counters: [
      { id: 'eats', name: '完全重なり食べ数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '食べ物と完全重なりの瞬間タップ5回',
    failTrigger: 'ズレた状態でタップ3回で失敗',
  },
  {
    id: 'arcade-383',
    title: 'ミッドナイトランディング',
    brand: 'タイトー',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '夜間着陸の最終進入。降下率インジケーターが適正角「3度（緑ゾーン）」を示している間だけ安全に着陸できる——インジケーターが緑ゾーンに入った瞬間にタップしてオートランド確定。急すぎ（赤ゾーン）でも浅すぎ（黄ゾーン）でもハードランディングになる。3回適正着陸でクリア。',
    objects: [
      { shape: 'triangle', role: '飛行機（最終進入中）', note: '' },
      { shape: 'rect', role: '降下率インジケーター（緑・黄・赤ゾーン）', note: '緑ゾーン入りで光る' },
      { shape: 'rect', role: '夜間滑走路（前方）', note: '' },
    ],
    counters: [
      { id: 'landings', name: '適正着陸数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'インジケーターが緑ゾーンに入った瞬間タップ3回',
    failTrigger: '赤・黄ゾーンでタップ3回で失敗',
  },
  {
    id: 'arcade-384',
    title: 'サイオン',
    brand: 'セイブ開発',
    year: 1984,
    duration: 20,
    difficulty: 'hard',
    concept: '部屋の壁が周期的に「透明化（完全に見えなくなる）」する。壁が完全透明になった瞬間（0.4秒間）にタップして通り抜ける——透明化の始まりかけや不透明に戻り始める瞬間では通り抜けられない。完全透明の0.4秒だけが通り抜けの窓。5回通り抜けでクリア。',
    objects: [
      { shape: 'rect', role: '壁（透明化する）', note: '完全透明時に消える' },
      { shape: 'face', role: 'サイオンのキャラ（部屋の中）', note: '' },
    ],
    counters: [
      { id: 'passes', name: '通り抜け数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '壁が完全透明の0.4秒にタップ5回',
    failTrigger: '半透明時にタップ3回で失敗',
  },
  {
    id: 'arcade-385',
    title: 'トーキョーウォーズ',
    brand: 'ナムコ',
    year: 1996,
    duration: 20,
    difficulty: 'normal',
    concept: '都市部の高層ビルの角から敵タンクが出てくる。半分隠れている間は建物が遮蔽してくれるが、建物から完全に出た瞬間（露出100%）にタップして砲撃すると一発撃墜——半分出た状態では建物に弾が当たる。3回完全露出撃墜でクリア。',
    objects: [
      { shape: 'rect', role: '敵タンク（建物の角から出る）', note: '完全露出時に光る' },
      { shape: 'rect', role: '高層ビル（遮蔽）', note: '' },
      { shape: 'rect', role: '自タンク（中央）', note: '' },
    ],
    counters: [
      { id: 'kills', name: '完全露出撃墜数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '敵タンクが完全に露出した瞬間タップ3回',
    failTrigger: '半分隠れた状態で撃つ3回で失敗',
  },
  {
    id: 'arcade-386',
    title: 'ギャラクティックウォーリアーズ',
    brand: 'KONAMI',
    year: 1985,
    duration: 20,
    difficulty: 'hard',
    concept: '星間物質の「共鳴フィールド」が発生する。フィールドの振動が「最大共振（同期点）」に達した瞬間にタップして共鳴砲を発射すると、共鳴が周囲の敵全員を一気に吹き飛ばす——同期点前後では単発砲弾で1体しか倒せない。3回共鳴砲でクリア。',
    objects: [
      { shape: 'ellipse', role: '共鳴フィールド（振動する）', note: '最大共振時に輝く' },
      { shape: 'face', role: '敵戦士×複数（周囲）', note: '' },
      { shape: 'face', role: '宇宙戦士（中央）', note: '' },
    ],
    counters: [
      { id: 'resonances', name: '共鳴砲数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'フィールドが最大共振の瞬間タップ3回',
    failTrigger: '共振不足時タップ3回で失敗',
  },
  {
    id: 'arcade-387',
    title: 'ボムビー',
    brand: 'ナムコ',
    year: 1979,
    duration: 20,
    difficulty: 'normal',
    concept: '敵の蜂が爆弾を投下してくる。爆弾の落下ラインが「自分の花の真上」を通過した瞬間にタップして花から飛び立ち回避——落下ラインが花の真上以外にある時に飛び立っても花を無駄に離れてしまう。真上通過の0.3秒だけが最適回避タイミング。5回回避でクリア。',
    objects: [
      { shape: 'bomb', role: '爆弾（落下ライン上）', note: '真上通過時に光る' },
      { shape: 'star', role: '花（自分のいる場所）', note: '' },
      { shape: 'face', role: '蜂（上空）', note: '' },
    ],
    counters: [
      { id: 'evades', name: '回避数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '爆弾が花の真上を通過した瞬間タップ5回',
    failTrigger: '真上以外でタップ3回で失敗',
  },
  {
    id: 'arcade-388',
    title: '闘神ブレイザーズ',
    brand: 'ビデオシステム',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: '気合い充填後、拳の炎が「最大」から自然消火に向かっていく。炎が消える直前——消火まで残り0.3秒のタイミングにタップして打つと「ブレイザーフィニッシュ（最後の炎を叩き込む必殺打）」が発動。炎が消えてからでは通常打撃に戻る。3回ブレイザーフィニッシュでクリア。',
    objects: [
      { shape: 'triangle', role: '炎（消えていく）', note: '残り0.3秒で赤く点滅' },
      { shape: 'face', role: '闘神（中央）', note: '' },
      { shape: 'face', role: '対戦相手（前方）', note: '' },
    ],
    counters: [
      { id: 'finishes', name: 'ブレイザーフィニッシュ数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '炎が消える0.3秒前にタップ3回',
    failTrigger: '炎消灯後タップ3回で失敗',
  },
  {
    id: 'arcade-389',
    title: 'バミューダトライアングル',
    brand: 'SNK',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '次元の亀裂が開閉を繰り返し、最大開口の瞬間に敵が最も多く出現する。亀裂が最大に開いた0.5秒にタップして一斉砲撃すると出現した全敵を巻き込む——最大開口前後では出現数が少なくて1〜2体しか当たらない。3回最大開口砲撃でクリア。',
    objects: [
      { shape: 'ellipse', role: '次元の亀裂（開閉する）', note: '最大開口時に白く輝く' },
      { shape: 'face', role: '出現する敵×複数', note: '最大開口時に密集' },
      { shape: 'triangle', role: '自機（下部）', note: '' },
    ],
    counters: [
      { id: 'volleys', name: '最大開口砲撃数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '亀裂が最大開口の0.5秒にタップ3回',
    failTrigger: '開口不足時タップ3回で失敗',
  },
  {
    id: 'arcade-390',
    title: 'ロックンロープ',
    brand: 'KONAMI',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: '電気が流れているロープに敵が近づいてくる。ロープと敵の距離が「最短（最接近点）」になった瞬間にタップしてロープを振動させると電気が敵に伝わって撃退できる——最接近前後では電気が届かない。最接近の0.3秒だけが電撃撃退のチャンス。5回電撃撃退でクリア。',
    objects: [
      { shape: 'ellipse', role: '電気ロープ（張ってある）', note: '' },
      { shape: 'face', role: '敵（近づいてくる）', note: '最接近時に光る' },
      { shape: 'face', role: 'キャラクター（ロープの上）', note: '' },
    ],
    counters: [
      { id: 'zaps', name: '電撃撃退数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'ロープと敵が最接近した瞬間タップ5回',
    failTrigger: '最接近前後にタップ3回で失敗',
  },
  {
    id: 'arcade-391',
    title: 'アウトフォクシーズ',
    brand: 'ナムコ',
    year: 1995,
    duration: 20,
    difficulty: 'hard',
    concept: '追跡中の獲物が物陰に隠れようとしている。物陰に完全に入る「0.3秒前」にタップしてショットを放つと、物陰に入る直前の獲物に命中する——物陰に完全に入ってから撃つと姿が消えて弾が当たらない。0.3秒前の先読みが必要。5回物陰入り前撃墜でクリア。',
    objects: [
      { shape: 'face', role: '獲物（物陰に向かって走る）', note: '物陰入り0.3秒前に光る' },
      { shape: 'rect', role: '物陰（柱・壁）', note: '' },
      { shape: 'face', role: '追跡者（中央）', note: '' },
    ],
    counters: [
      { id: 'kills', name: '物陰入り前撃墜数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '物陰入り0.3秒前にタップ5回',
    failTrigger: '物陰に完全に入ってから撃つ3回で失敗',
  },
  {
    id: 'arcade-392',
    title: 'スペースインベーダー',
    brand: 'タイトー',
    year: 1978,
    duration: 20,
    difficulty: 'normal',
    concept: '謎の「UFO（母船）」が画面上部を横切る。UFOは一定速度で移動しているが、ランダムなタイミングで「一時停止（速度0になる瞬間）」する——UFOが一時停止した瞬間にタップして撃つと高得点。動いている間に撃っても低得点しか入らない。5回一時停止撃墜でクリア。',
    objects: [
      { shape: 'rect', role: 'UFO母船（横移動・時々停止）', note: '停止時に光る' },
      { shape: 'triangle', role: '自機（下部）', note: '' },
    ],
    counters: [
      { id: 'hits', name: '一時停止撃墜数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'UFO一時停止の瞬間タップ5回',
    failTrigger: '移動中に撃つ3回で失敗',
  },
] as const;
