/**
 * ideas/arcade-2020q4.ts
 * Arcade Archives 2020年10〜12月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2020q4Ideas = [
  {
    id: 'arcade-130',
    title: 'べんべろべえ',
    brand: 'タイトー',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: '丸いキャラクターが壁と天井の間を自動的に跳ね回っている。浮かんでいる泡には「良い泡（金色）」と「悪い泡（黒色）」がある。キャラクターが跳ねる頂点の高さと泡の高さが一致した瞬間にタップして金色の泡だけを割れ。黒い泡を割るとダメージ。5個割ればクリア。',
    objects: [
      { shape: 'face', role: 'べんべろべえ（跳ね回る）', note: '' },
      { shape: 'balloon', role: '金色の泡（良い）', note: 'タップで割る' },
      { shape: 'balloon', role: '黒い泡（悪い）', note: 'タップ禁止' },
    ],
    counters: [
      { id: 'good', name: '良い泡を割った数', target: 5, note: '5個でクリア' },
    ],
    winTrigger: 'counter good >= 5',
    failTrigger: '黒い泡を割った3回で失敗',
  },
  {
    id: 'arcade-131',
    title: 'アラビアン',
    brand: 'サン電子',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: '魔法の絨毯が8の字を描いて飛んでいる。飛行経路上の特定ポイントに宝箱が出現する。絨毯がぴったり宝箱の真上を通過した瞬間にタップして収集。飛行速度が段々速くなるにつれ狙いを早める必要がある。5個収集でクリア。',
    objects: [
      { shape: 'rect', role: '魔法の絨毯（8の字飛行）', note: '' },
      { shape: 'coin', role: '宝箱（経路上に出現）', note: '真上通過でタップ' },
    ],
    counters: [
      { id: 'treasures', name: '宝箱収集数', target: 5, note: '5個でクリア' },
    ],
    winTrigger: 'counter treasures >= 5',
    failTrigger: '通り過ぎ3回で失敗',
  },
  {
    id: 'arcade-132',
    title: 'スーパーコブラ',
    brand: 'KONAMI',
    year: 1981,
    duration: 20,
    difficulty: 'hard',
    concept: 'ヘリコプターが洞窟内を飛行している。天井と床の高さが変化し、通れる高度範囲が刻々と変わる。同時に地上から対空ミサイルが飛んでくる。「通れる高度」かつ「ミサイルが来ない高度」の安全ゾーンを見つけてタップで高度調整。ゾーンを外れたら即撃墜。5区間通過でクリア。',
    objects: [
      { shape: 'triangle', role: 'ヘリコプター（水平飛行）', note: '' },
      { shape: 'rect', role: '洞窟天井・床（高さ変化）', note: '通れる高度を示す帯' },
      { shape: 'diamond', role: 'ミサイル（地上から飛来）', note: '' },
      { shape: 'button', role: '上昇ボタン', note: '' },
      { shape: 'button', role: '下降ボタン', note: '' },
    ],
    counters: [
      { id: 'sections', name: '安全通過区間数', target: 5, note: '5区間でクリア' },
    ],
    winTrigger: 'counter sections >= 5',
    failTrigger: '天井・床・ミサイルのいずれかに当たったら失敗',
  },
  {
    id: 'arcade-133',
    title: 'サッカー',
    brand: '任天堂',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: 'ペナルティキック対決。ゴールキーパーが直前の3本の動きを記録として表示（左・右・中）。パターンから次の飛びつき方向を読み、逆の隅にタップしてシュート。キーパーが読まれていない方向を選ぶと失点。3得点でクリア。',
    objects: [
      { shape: 'face', role: 'ゴールキーパー（ゴール前）', note: '飛びつき方向が直前3本記録で表示' },
      { shape: 'circle', role: 'ボール', note: '' },
      { shape: 'button', role: '左コーナーシュートボタン', note: '' },
      { shape: 'button', role: '右コーナーシュートボタン', note: '' },
    ],
    counters: [
      { id: 'goals', name: '得点数', target: 3, note: '3得点でクリア' },
    ],
    winTrigger: 'counter goals >= 3',
    failTrigger: '3回セーブされたら失敗',
  },
  {
    id: 'arcade-134',
    title: '64番街',
    brand: 'ジャレコ',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: '2人の主人公リックとアレンが敵を挟んでいる。リックが先に殴りスタンを取ると数字カウントダウンが始まる。カウントが「2」の瞬間にアレンをタップして同時投げを発動させよ。「1」まで待つと敵が回復し、「3」以上では投げが空振りになる。5回成功でクリア。',
    objects: [
      { shape: 'face', role: 'リック（左側）', note: '殴りでスタン付与' },
      { shape: 'face', role: 'アレン（右側）', note: 'タップで投げ発動' },
      { shape: 'face', role: '敵（中央・スタン中にカウントダウン表示）', note: '' },
    ],
    counters: [
      { id: 'throws', name: '同時投げ成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'カウント「2」の瞬間にタップ5回',
    failTrigger: 'カウント「1」または「3以上」でタップ3回で失敗',
  },
  {
    id: 'arcade-135',
    title: 'ぺったんピュー',
    brand: 'サン電子',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: '粘着ボールを壁に投げると張り付いた後、跳ね返る角度が点線で予告される。点線の先に敵がいる位置まで待ってからタップして剥がして発射。点線は壁の凹凸によって微妙にズレていくので、敵が点線上に重なった瞬間を見極めよ。5体撃退でクリア。',
    objects: [
      { shape: 'circle', role: '粘着ボール（壁に張り付き）', note: '' },
      { shape: 'diamond', role: '跳ね返り軌道（点線）', note: '敵が重なると光る' },
      { shape: 'face', role: '敵（移動）', note: '' },
      { shape: 'rect', role: '壁（凹凸あり）', note: '' },
    ],
    counters: [
      { id: 'hit', name: '撃退数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'counter hit >= 5',
    failTrigger: '軌道外れ3回で失敗',
  },
  {
    id: 'arcade-136',
    title: 'ゼロチーム',
    brand: 'セイブ開発',
    year: 1993,
    duration: 20,
    difficulty: 'normal',
    concept: '複数の敵が取り囲んでいる。今にも殴りかかろうとしている敵は全身が赤く光る。光っている敵だけをタップしてカウンターを決めよ。光っていない敵をタップすると無駄な行動消費で反撃を受ける。5回連続カウンター成功でクリア。',
    objects: [
      { shape: 'face', role: '敵×4（包囲中）', note: '攻撃前に赤く光る' },
      { shape: 'face', role: 'ゼロチームの戦士（中央）', note: '' },
    ],
    counters: [
      { id: 'counters', name: 'カウンター成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '赤く光っている敵のみタップ5回',
    failTrigger: '光っていない敵をタップ3回で失敗',
  },
  {
    id: 'arcade-137',
    title: 'グリーンベレー',
    brand: 'KONAMI',
    year: 1985,
    duration: 20,
    difficulty: 'hard',
    concept: '武装兵が遠距離から近づいてくる。銃の射程外（遠い距離）では撃てないが、接近しすぎると撃たれる。距離ゲージが「ナイフ間合い」ゾーンに入った瞬間——撃たれる前の0.4秒——にタップして一刀両断。早すぎると届かず、遅すぎると被弾。5人制圧でクリア。',
    objects: [
      { shape: 'face', role: '武装兵（右から近づく）', note: '' },
      { shape: 'rect', role: '距離ゲージ（ナイフ間合いゾーン付き）', note: '' },
      { shape: 'face', role: 'グリーンベレー（左端固定）', note: '' },
    ],
    counters: [
      { id: 'takedowns', name: '制圧数', target: 5, note: '5人でクリア' },
    ],
    winTrigger: 'ゲージがナイフ間合いゾーンでタップ5回',
    failTrigger: '被弾3回で失敗',
  },
  {
    id: 'arcade-138',
    title: 'フェアリーランドストーリー',
    brand: 'タイトー',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: '魔女プトレミーが魔法で敵をケーキに変える。ケーキになった敵は3秒で元に戻る——その前に端まで押して落とさなければならない。ケーキが足場のどちらの端に近いかを見て、近い方向をタップして押し出せ。判断が遅れると復活して反撃される。5体落下でクリア。',
    objects: [
      { shape: 'face', role: '敵ケーキ（プラットフォーム上・3秒でカウントダウン）', note: '' },
      { shape: 'rect', role: 'プラットフォーム（両端が崖）', note: '' },
      { shape: 'face', role: 'プトレミー（魔女）', note: '' },
      { shape: 'button', role: '左押しボタン', note: '' },
      { shape: 'button', role: '右押しボタン', note: '' },
    ],
    counters: [
      { id: 'fallen', name: '落下させた数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'counter fallen >= 5',
    failTrigger: '3秒以内に押せず復活3回で失敗',
  },
  {
    id: 'arcade-139',
    title: 'マーカム',
    brand: 'サン電子',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: '主人公が投げたブーメランが壁で跳ね返って戻ってくる。行きの軌道でも帰りの軌道でも敵に当たれば撃退できる。どちらの軌道で当てるかを選択し、敵とブーメランが重なるタイミングで画面の対応するエリアをタップ。5体撃退でクリア。',
    objects: [
      { shape: 'diamond', role: 'ブーメラン（往復軌道）', note: '行き軌道と帰り軌道を点線表示' },
      { shape: 'face', role: '主人公（左端）', note: '' },
      { shape: 'face', role: '敵（移動）', note: '' },
      { shape: 'rect', role: '壁（跳ね返り）', note: '' },
    ],
    counters: [
      { id: 'hit', name: '撃退数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'counter hit >= 5',
    failTrigger: '軌道外れ3回で失敗',
  },
  {
    id: 'arcade-140',
    title: 'VS.テニス',
    brand: '任天堂',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: 'サーブシーン。ボールを高く投げ上げると弧を描いて上昇→頂点→下降する。打球威力はボールが最も高い頂点でラケットを当てたときが最大。高さインジケーターが上昇し頂点で折り返す——頂点に達した瞬間にタップしてエースサーブ。3回エースでクリア。',
    objects: [
      { shape: 'circle', role: 'テニスボール（投げ上げ→頂点→下降）', note: '' },
      { shape: 'rect', role: '高さインジケーター（上昇→折り返し）', note: '頂点でマーカー光る' },
      { shape: 'face', role: 'テニスプレイヤー（下部）', note: '' },
    ],
    counters: [
      { id: 'aces', name: 'エースサーブ数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'ボールが頂点の瞬間タップ3回',
    failTrigger: '頂点外タップ3回で失敗',
  },
  {
    id: 'arcade-141',
    title: 'グラディウスIII -伝説から神話へ-',
    brand: 'KONAMI',
    year: 1989,
    duration: 25,
    difficulty: 'hard',
    concept: '巨大石像の頭部が同心円状の衝撃波リングを次々と放射してくる。各リングの円周上に1か所だけ隙間がある。自機をリングの隙間の位置まで動かしてからタップして突入——隙間は毎回異なる方向に出る。3リング連続通過でクリア。',
    objects: [
      { shape: 'face', role: '巨大石像の頭部（左端）', note: '' },
      { shape: 'circle', role: '衝撃波リング（拡大しながら迫る）', note: '円周1か所に隙間' },
      { shape: 'triangle', role: '自機（右側）', note: '' },
      { shape: 'button', role: '突入ボタン', note: '' },
    ],
    counters: [
      { id: 'passed', name: 'リング通過数', target: 3, note: '3リングでクリア' },
    ],
    winTrigger: '隙間に位置合わせしてタップ3回',
    failTrigger: 'リングに当たったら失敗',
  },
] as const;
