/**
 * ideas/arcade-2024q4.ts
 * Arcade Archives 2024年10〜12月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2024q4Ideas = [
  {
    id: 'arcade-328',
    title: 'ムーンシャトル',
    brand: 'ニチブツ',
    year: 1981,
    duration: 20,
    difficulty: 'normal',
    concept: '月面着陸シャトルが降下している。月面をスキャンすると「平坦ゾーン（着陸可能帯）」がシャトル真下に来る瞬間がある——平坦ゾーンが真下に揃った瞬間にタップして着陸脚を展開。ゾーンがズレた状態で着地すると機体が傾いて着陸失敗。3回安全着陸でクリア。',
    objects: [
      { shape: 'triangle', role: 'ムーンシャトル（降下中）', note: '' },
      { shape: 'rect', role: '月面（平坦ゾーンが移動）', note: '平坦ゾーンが真下で光る' },
    ],
    counters: [
      { id: 'landings', name: '安全着陸数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '平坦ゾーンが真下に来た瞬間タップ3回',
    failTrigger: 'ゾーンズレで着陸3回で失敗',
  },
  {
    id: 'arcade-329',
    title: 'スーパーバレー\'91',
    brand: 'ビデオシステム',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: 'フローターサーブは空中で横にブレながら落ちてくる。ボールの「横ブレが最大（山の頂点）」になった瞬間にタップしてレシーブの手を合わせると完璧なプラットフォームになる——ブレ最大より早くても遅くても弾き損なう。5回完璧レシーブでクリア。',
    objects: [
      { shape: 'circle', role: 'バレーボール（横ブレしながら落下）', note: 'ブレ最大時に光る' },
      { shape: 'face', role: 'レシーブ選手（中央）', note: '' },
    ],
    counters: [
      { id: 'receives', name: '完璧レシーブ数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '横ブレ最大の瞬間タップ5回',
    failTrigger: 'ブレ最大を外してタップ3回で失敗',
  },
  {
    id: 'arcade-330',
    title: 'バイオレンスファイト',
    brand: 'タイトー',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: '床に複数の武器が散らばっている。光って強調された「最強武器」が1つだけある——最強武器が体の正面1マス以内（拾える位置）に来た瞬間にタップして掴み取る。他の武器を拾っても威力が低い。最強武器が来る前に動くと普通武器を拾ってしまう。3回最強武器ヒットでクリア。',
    objects: [
      { shape: 'star', role: '最強武器（光って強調）', note: '拾える位置で輝く' },
      { shape: 'rect', role: '普通武器×複数（床に散らばる）', note: '' },
      { shape: 'face', role: '自キャラ（中央）', note: '' },
    ],
    counters: [
      { id: 'picks', name: '最強武器ピック数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '最強武器が拾える位置に来た瞬間タップ3回',
    failTrigger: '普通武器を3回拾うと失敗',
  },
  {
    id: 'arcade-331',
    title: 'メタモルフィックフォース',
    brand: 'KONAMI',
    year: 1993,
    duration: 20,
    difficulty: 'hard',
    concept: '変身エネルギーゲージが戦いながら充填される。ゲージが100%に達する瞬間——99%から100%へ切り替わるその刹那（0.2秒）にタップすると「ジャスト変身」が発動して完全形態に変身できる。100%を超えてからタップするとゲージが50%にリセットされる。3回ジャスト変身でクリア。',
    objects: [
      { shape: 'rect', role: '変身エネルギーゲージ（充填中）', note: '100%到達の瞬間に白く光る' },
      { shape: 'face', role: 'プレイヤーキャラ（中央）', note: '' },
    ],
    counters: [
      { id: 'transforms', name: 'ジャスト変身数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'ゲージ100%到達の0.2秒にタップ3回',
    failTrigger: 'ゲージ超過後タップ3回で失敗',
  },
  {
    id: 'arcade-332',
    title: '雷軋斗',
    brand: 'テクモ',
    year: 1992,
    duration: 20,
    difficulty: 'hard',
    concept: '超必殺技「雷斬」を発動するには雷エネルギーが左手から右手へ移行する瞬間が必要。エネルギーが左手（青い光）から右手（金の光）へ移行する「移行中」の0.3秒間にタップして解放——左手中も右手中も不完全で威力が半減する。3回完全「雷斬」でクリア。',
    objects: [
      { shape: 'face', role: '雷軋斗（中央）', note: '移行中に紫色に光る' },
      { shape: 'rect', role: '雷エネルギー表示（左→右に移動）', note: '' },
      { shape: 'face', role: '対戦相手（前方）', note: '' },
    ],
    counters: [
      { id: 'raizans', name: '完全雷斬数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'エネルギー移行中（0.3秒）にタップ3回',
    failTrigger: '左手中・右手中タップ3回で失敗',
  },
  {
    id: 'arcade-333',
    title: 'VS.カイの冒険',
    brand: 'ナムコ',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: 'カイが鐘を鳴らすと音波が広がる。最初の振動波形が「共鳴ピーク（最初の最大振幅）」に達した瞬間にタップすると別の鐘が共鳴連鎖して仕掛けが起動する——共鳴ピークを過ぎてからタップすると共鳴が起きず単発の音だけで終わる。3回共鳴連鎖でクリア。',
    objects: [
      { shape: 'circle', role: '鐘（振動音波を発する）', note: '共鳴ピーク時に金色に輝く' },
      { shape: 'face', role: 'カイ（中央）', note: '' },
      { shape: 'rect', role: '仕掛け（遠方）', note: '共鳴連鎖で起動する' },
    ],
    counters: [
      { id: 'resonances', name: '共鳴連鎖数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '音波共鳴ピークの瞬間タップ3回',
    failTrigger: 'ピーク過ぎてからタップ3回で失敗',
  },
  {
    id: 'arcade-334',
    title: 'コナミのピンポン',
    brand: 'KONAMI',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: 'ラリーを続けるとボールに「スピン量」が蓄積する。スピンゲージが「3回分以上（黄色ゾーン）」に達した状態でタップするとカーブサーブが炸裂して相手コートの角に決まる——2回分以下では変化量が足りず返球される。ラリーでスピンを3回以上稼いでからカーブサーブ3回でクリア。',
    objects: [
      { shape: 'circle', role: 'ピンポン球（ラリー中）', note: '' },
      { shape: 'rect', role: 'スピンゲージ（蓄積する）', note: '黄色ゾーンで3回分以上' },
      { shape: 'face', role: '選手（手前）', note: '' },
    ],
    counters: [
      { id: 'curves', name: 'カーブサーブ決め数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'スピン3回分以上蓄積後タップ3回',
    failTrigger: '2回分以下でタップ3回で失敗',
  },
  {
    id: 'arcade-335',
    title: 'ファイナルブロー',
    brand: 'タイトー',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: 'ラッシュ中、相手のガードに0.2秒ごとに異なる部位の隙間が出現する。隙間が「顎（アゴ）部分」に来た瞬間にタップしてアッパーカット——顎以外の隙間（腕・腹・胸）をアッパーで突いても効果が低い。顎への5回アッパーカットでクリア。',
    objects: [
      { shape: 'face', role: '相手ボクサー（ガード中）', note: '顎の隙間が光る' },
      { shape: 'rect', role: '隙間インジケーター（部位表示）', note: '' },
      { shape: 'face', role: '自キャラ（左）', note: '' },
    ],
    counters: [
      { id: 'uppers', name: '顎アッパーカット数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '顎に隙間が来た瞬間タップ5回',
    failTrigger: '顎以外の隙間でタップ3回で失敗',
  },
  {
    id: 'arcade-336',
    title: 'コットン',
    brand: 'サクセス',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: 'コットンが魔力を「ウィロウ（お菓子）」から補充する。ウィロウが画面を飛び回っているが、コットンの正面（魔法光弾の軌道直線上）に入った瞬間にタップして魔法光弾を発射すると命中吸収できる——直線上から外れると弾が外れてウィロウを逃してしまう。5回ウィロウ吸収でクリア。',
    objects: [
      { shape: 'star', role: 'ウィロウ・お菓子（飛び回る）', note: '軌道直線上で光る' },
      { shape: 'circle', role: '魔法光弾（前方へ飛ぶ）', note: '' },
      { shape: 'face', role: 'コットン（ほうき乗り・中央）', note: '' },
    ],
    counters: [
      { id: 'absorbs', name: 'ウィロウ吸収数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'ウィロウが軌道直線上に来た瞬間タップ5回',
    failTrigger: '直線外で発射3回で失敗',
  },
  {
    id: 'arcade-337',
    title: 'シティボンバー',
    brand: 'KONAMI',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '街の建物を上空から爆撃する。各建物の最上階に「構造弱点ポイント」が0.5秒おきに点灯する——弱点ポイントが点灯している間にタップして爆弾投下すると建物の基礎から崩壊する。弱点以外の場所を爆撃しても外壁にしかダメージが入らない。3回弱点爆撃でクリア。',
    objects: [
      { shape: 'rect', role: '建物（最上階に弱点ポイント）', note: '弱点点灯時に赤く光る' },
      { shape: 'bomb', role: '爆弾（上空から投下）', note: '' },
      { shape: 'triangle', role: '爆撃機（上空）', note: '' },
    ],
    counters: [
      { id: 'hits', name: '弱点爆撃数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '弱点ポイント点灯中タップ3回',
    failTrigger: '弱点消灯時に投下3回で失敗',
  },
  {
    id: 'arcade-338',
    title: 'バイパーフェイズ1',
    brand: 'セイブ開発',
    year: 1995,
    duration: 20,
    difficulty: 'hard',
    concept: 'ボスが「フェイズシフト（形態変化）」を行う最中に弱点が一時的に中央に移動する。変形アニメーションの50%完了時（変形の中間フレーム）だけ弱点が完全露出する——変形開始直後や完了後では装甲に守られている。変形50%の瞬間にタップしてクリティカルヒット。5回クリティカルでクリア。',
    objects: [
      { shape: 'star', role: 'ボスの弱点（変形中に移動）', note: '変形50%時に中央で光る' },
      { shape: 'rect', role: 'ボス機体（変形する）', note: '' },
      { shape: 'triangle', role: '自機（下部）', note: '' },
    ],
    counters: [
      { id: 'crits', name: 'クリティカルヒット数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'フェイズシフト変形50%の瞬間タップ5回',
    failTrigger: '露出外タップ3回で失敗',
  },
  {
    id: 'arcade-339',
    title: 'ウォリアーブレード',
    brand: 'タイトー',
    year: 1992,
    duration: 20,
    difficulty: 'normal',
    concept: '敵の鎧の接合部が回転している。接合部の金具が「縦向き（最弱方向）」になった瞬間に剣を突くと接合部が破壊できる——横向きでは剣が金具に弾かれる。接合部が縦向きになるのは1周回転中に一瞬だけ。3か所の接合部全破壊でクリア。',
    objects: [
      { shape: 'rect', role: '鎧の接合部（回転する）', note: '縦向きで光る' },
      { shape: 'face', role: '鎧を着た敵（前方）', note: '' },
      { shape: 'face', role: 'ウォリアーブレード戦士（中央）', note: '' },
    ],
    counters: [
      { id: 'breaks', name: '接合部破壊数', target: 3, note: '3か所でクリア' },
    ],
    winTrigger: '接合部が縦向きになった瞬間タップ3回',
    failTrigger: '横向き接合部にタップ3回で失敗',
  },
  {
    id: 'arcade-340',
    title: '超時空要塞マクロス',
    brand: 'バンプレスト',
    year: 1992,
    duration: 20,
    difficulty: 'hard',
    concept: 'マクロスキャノン発射には5か所のエネルギー中継ポイントが順次点灯して全点灯する必要がある。5か所が全て同時点灯する瞬間（0.4秒間）にタップしてキャノン発動——全5か所揃う前や全点灯後では威力が出ない。3回マクロスキャノン発射でクリア。',
    objects: [
      { shape: 'circle', role: '中継ポイント×5（順次点灯）', note: '全点灯時に白く輝く' },
      { shape: 'rect', role: 'マクロス艦（中央）', note: '' },
      { shape: 'face', role: '敵ゼントラーディ艦（前方）', note: '' },
    ],
    counters: [
      { id: 'cannons', name: 'マクロスキャノン発射数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '5か所全点灯の0.4秒以内にタップ3回',
    failTrigger: '全点灯前・後タップ3回で失敗',
  },
] as const;
