/**
 * ideas/arcade-2021q4.ts
 * Arcade Archives 2021年10〜12月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2021q4Ideas = [
  {
    id: 'arcade-177',
    title: '源平討魔伝',
    brand: 'ナムコ',
    year: 1986,
    duration: 20,
    difficulty: 'hard',
    concept: '義経が馬上で左右から迫る敵を斬る。まず近い方の敵を斬ってから、素早く逆方向に向いて遠い方を斬る——2体の距離差を読んで近い方をタップ→0.5秒後に遠い方をタップ。距離判断を間違えると遠い方を先に斬ろうとして近い方に刺されてしまう。5組撃破でクリア。',
    objects: [
      { shape: 'face', role: '源義経（馬上・中央）', note: '' },
      { shape: 'face', role: '左の敵（距離付き）', note: '' },
      { shape: 'face', role: '右の敵（距離付き）', note: '' },
    ],
    counters: [
      { id: 'pairs', name: '左右組撃破数', target: 5, note: '5組でクリア' },
    ],
    winTrigger: '近い方→遠い方の順でタップ5組',
    failTrigger: '遠い方を先にタップ3回で失敗',
  },
  {
    id: 'arcade-178',
    title: 'ラリーX',
    brand: 'ナムコ',
    year: 1980,
    duration: 20,
    difficulty: 'normal',
    concept: '赤い追手車が後ろから複数台迫っている。スモークスクリーンは一度に1秒しか持続しない。後方に2台以上の追手が密集している瞬間にタップしてスモークを撒けば両方を同時に足止めできる。1台だけの時にスモークすると燃料を無駄にする。3回複数足止めでクリア。',
    objects: [
      { shape: 'triangle', role: '自車（中央・前進）', note: '' },
      { shape: 'rect', role: '追手車×複数（後方から追尾）', note: '' },
      { shape: 'circle', role: 'スモーク（タップで散布）', note: '1秒持続' },
    ],
    counters: [
      { id: 'multi', name: '複数同時足止め数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '後方2台以上密集時にタップ3回',
    failTrigger: '1台のみ足止め3回で失敗',
  },
  {
    id: 'arcade-179',
    title: 'マッピー',
    brand: 'ナムコ',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: 'マッピーがトランポリンで上のフロアに弾んで上がる。各フロアにニャームコが待ち構えている。マッピーが着地する直前の0.5秒に、そのフロアのドアをタップして開くとマイクロウェーブが出てニャームコを一掃できる。着地後にタップすると遅すぎてニャームコに捕まる。5体一掃でクリア。',
    objects: [
      { shape: 'face', role: 'マッピー（トランポリンで上昇中）', note: '着地直前に光る' },
      { shape: 'face', role: 'ニャームコ（各フロア）', note: '' },
      { shape: 'rect', role: 'ドア（タップでマイクロウェーブ発動）', note: '' },
    ],
    counters: [
      { id: 'zapped', name: '一掃数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '着地直前にタップ5回',
    failTrigger: '着地後タップで捕まり3回で失敗',
  },
  {
    id: 'arcade-180',
    title: 'スカイキッド',
    brand: 'ナムコ',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: '複葉機の後ろからミサイルが迫っている。ループ回避の開始タイミングが重要——ミサイルが「臨界距離」に入った瞬間にタップしてループを始めると、ループの最下点でミサイルが通過し回避できる。早く始めるとループ中にミサイルが来てしまう。5回回避でクリア。',
    objects: [
      { shape: 'triangle', role: '複葉機（中央）', note: '' },
      { shape: 'diamond', role: 'ミサイル（後方から接近）', note: '' },
      { shape: 'rect', role: '距離インジケーター（臨界距離マーカー付き）', note: '' },
    ],
    counters: [
      { id: 'loops', name: 'ループ回避成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'インジケーターが臨界距離でタップ5回',
    failTrigger: '被弾3回で失敗',
  },
  {
    id: 'arcade-181',
    title: 'ブラックハート',
    brand: 'UPL',
    year: 1991,
    duration: 20,
    difficulty: 'hard',
    concept: 'ボスが発生させたブラックホールが弾を吸い込んでいる。ブラックホールの引力が「反転」する瞬間（0.5秒）だけ、通常弾が直進してコアに届く。反転タイミングはインジケーターの波形が谷を通過するときに一致する——波形が谷の瞬間にタップ。3回コア命中でクリア。',
    objects: [
      { shape: 'circle', role: 'ブラックホール（引力中）', note: '' },
      { shape: 'star', role: 'コア（ブラックホール中心）', note: '反転時のみ弾が届く' },
      { shape: 'rect', role: '引力反転インジケーター（波形）', note: '谷の瞬間が反転' },
    ],
    counters: [
      { id: 'hits', name: 'コア命中数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '波形が谷の瞬間タップ3回',
    failTrigger: '引力中タップ（弾が吸収）3回で失敗',
  },
  {
    id: 'arcade-182',
    title: 'リブルラブル',
    brand: 'ナムコ',
    year: 1983,
    duration: 25,
    difficulty: 'hard',
    concept: 'リブルとラブルが縄で繋がれている。縄で敵を囲んで旗に触れると得点になる。敵が複数いる中で、2体以上を縄の内側に取り込んだ状態で旗をタップ。1体だけ囲んでも得点は少なく、囲むのが0体だと縄が切れる。3回複数囲みでクリア。',
    objects: [
      { shape: 'face', role: 'リブル（左）', note: '' },
      { shape: 'face', role: 'ラブル（右）', note: '' },
      { shape: 'rect', role: '縄（2人の間）', note: '敵を囲む' },
      { shape: 'face', role: '敵×複数（フィールド内）', note: '縄の内側で光る' },
      { shape: 'star', role: '旗（タップで得点）', note: '' },
    ],
    counters: [
      { id: 'encircled', name: '複数囲み得点数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '縄内に2体以上いる状態で旗タップ3回',
    failTrigger: '縄が切れる（0体囲み）3回で失敗',
  },
  {
    id: 'arcade-183',
    title: 'レイメイズ',
    brand: 'タイトー',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '暗い迷路の中でキャラクターがたいまつの光だけで周囲を照らしている。敵の足音が方向インジケーターで示され、その方向にたいまつを向けると敵が照らされる。照らされた敵をタップして攻撃——暗闇のままタップしても当たらない。5体撃退でクリア。',
    objects: [
      { shape: 'face', role: '主人公（たいまつ持ち）', note: '' },
      { shape: 'circle', role: 'たいまつの光（向きを変えられる）', note: '' },
      { shape: 'diamond', role: '方向インジケーター（足音の方向）', note: '' },
      { shape: 'face', role: '敵（暗闇に潜む）', note: '照らされると赤く光る' },
    ],
    counters: [
      { id: 'defeated', name: '撃退数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '敵を照らした状態でタップ5回',
    failTrigger: '暗闇タップ3回で失敗',
  },
  {
    id: 'arcade-184',
    title: 'フォゾン',
    brand: 'ナムコ',
    year: 1983,
    duration: 25,
    difficulty: 'hard',
    concept: '画面上部に「目標分子」の形が表示される。原子（丸）が漂ってきており、それを中心核に結合させて目標形状を再現する。結合点は4方向あり、同じ色の原子を対応する位置にタップして収集。間違った色の原子を結合すると分子が不安定化。3分子完成でクリア。',
    objects: [
      { shape: 'circle', role: '漂う原子（色付き）', note: 'タップで中心核に結合' },
      { shape: 'circle', role: '中心核（結合状態を表示）', note: '' },
      { shape: 'rect', role: '目標分子図（上部）', note: '' },
    ],
    counters: [
      { id: 'molecules', name: '分子完成数', target: 3, note: '3個でクリア' },
    ],
    winTrigger: '目標形状と一致した分子を3個完成',
    failTrigger: '誤色結合で分子崩壊3回で失敗',
  },
  {
    id: 'arcade-185',
    title: 'ミズバク大冒険',
    brand: 'タイトー',
    year: 1990,
    duration: 20,
    difficulty: 'normal',
    concept: '水のキャラクター「ドロップ」が水の泡を床に向けて転がす。床は傾いており、転がった泡は傾斜の低い方へ流れていく。敵が坂の下側にいる時にタップして泡を転がすと勢いよく当たる。坂の上側の敵には泡が届かない——地形の傾きを読め。5体撃退でクリア。',
    objects: [
      { shape: 'balloon', role: '水の泡（転がる）', note: '傾斜方向に流れる' },
      { shape: 'face', role: 'ドロップ（中央）', note: '' },
      { shape: 'rect', role: '傾いた床（傾き方向表示）', note: '' },
      { shape: 'face', role: '敵（坂の上/下）', note: '' },
    ],
    counters: [
      { id: 'hit', name: '撃退数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '敵が坂の下側にいる時にタップ5回',
    failTrigger: '坂の上側の敵にタップ3回で失敗',
  },
  {
    id: 'arcade-186',
    title: 'ドラゴンバスター',
    brand: 'ナムコ',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: '剣士クロービスが盾を持っている。敵が正面・側面・背面を変えながら攻撃を仕掛ける。盾は常に正面にしか向かない——敵が側面や背面に回り込んだときはすぐに向きを変えなければならない。敵の攻撃方向に合わせた向きをタップ。5回ガード成功でクリア。',
    objects: [
      { shape: 'face', role: 'クロービス（中央）', note: '向きが変わる' },
      { shape: 'face', role: '敵（周囲を回りながら攻撃）', note: '' },
      { shape: 'button', role: '左向きボタン', note: '' },
      { shape: 'button', role: '右向きボタン', note: '' },
    ],
    counters: [
      { id: 'blocks', name: 'ガード成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '攻撃方向に向いた状態でタップ5回',
    failTrigger: '向きが合わずに被弾3回で失敗',
  },
  {
    id: 'arcade-187',
    title: '未来忍者',
    brand: 'ナムコ',
    year: 1988,
    duration: 20,
    difficulty: 'hard',
    concept: '未来忍者がレーザーを刀で弾き返す。レーザーを90度に反射させて、反射先に敵がいる位置でタップすれば反射弾で撃墜できる。反射先に何もいない場合はタップしても意味がない——反射軌道の先に敵がいる瞬間を見極めよ。3体反射弾撃墜でクリア。',
    objects: [
      { shape: 'face', role: '未来忍者（中央）', note: '' },
      { shape: 'rect', role: 'レーザー（飛来）', note: '' },
      { shape: 'diamond', role: '反射軌道（点線）', note: '敵と重なると光る' },
      { shape: 'face', role: '敵（反射先）', note: '' },
    ],
    counters: [
      { id: 'reflected', name: '反射弾撃墜数', target: 3, note: '3体でクリア' },
    ],
    winTrigger: '反射軌道上に敵がいる瞬間タップ3回',
    failTrigger: '反射先に敵がいない状態でタップ3回で失敗',
  },
  {
    id: 'arcade-188',
    title: 'XEXEX',
    brand: 'KONAMI',
    year: 1991,
    duration: 20,
    difficulty: 'hard',
    concept: '自機に生体触手が付いており、大型敵に射程内で巻き付かせることができる。触手が絡みついている間は敵の攻撃を盾として受けられる。大型敵が砲撃モーションを取った瞬間にタップして触手を巻き付け、その攻撃を防いでから離脱。3回ブロック成功でクリア。',
    objects: [
      { shape: 'triangle', role: '自機（右側）', note: '' },
      { shape: 'rect', role: '生体触手（射程表示）', note: 'タップで巻き付く' },
      { shape: 'face', role: '大型敵（左側・砲撃モーション）', note: '砲撃予備動作が光る' },
    ],
    counters: [
      { id: 'blocks', name: '触手ブロック数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '砲撃モーション開始時にタップ3回',
    failTrigger: '砲撃を直接被弾3回で失敗',
  },
] as const;
