/**
 * ideas/arcade-2025q3.ts
 * Arcade Archives 2025年7〜9月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2025q3Ideas = [
  {
    id: 'arcade-367',
    title: 'エアーコンバット22',
    brand: 'ナムコ',
    year: 1995,
    duration: 20,
    difficulty: 'hard',
    concept: '敵機がフレアを撒いて熱誘導ミサイルを撹乱する。フレアが散らばった後、熱源が「再収束（一か所に集まる瞬間）」する——熱源が再収束した0.4秒に追加ミサイルをタップして発射すると命中。熱源が拡散している間に撃つと外れる。3回再収束命中でクリア。',
    objects: [
      { shape: 'star', role: '熱源（拡散→再収束を繰り返す）', note: '再収束時に輝く' },
      { shape: 'triangle', role: '敵機（フレアを撒く）', note: '' },
      { shape: 'triangle', role: '自機（中央）', note: '' },
    ],
    counters: [
      { id: 'hits', name: '再収束命中数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '熱源再収束の0.4秒にタップ3回',
    failTrigger: '拡散中に発射3回で失敗',
  },
  {
    id: 'arcade-368',
    title: '超時空要塞マクロスII',
    brand: 'バンプレスト',
    year: 1993,
    duration: 20,
    difficulty: 'normal',
    concept: 'バルキリーのオーバーブーストで加速した後、機体の後方に炎の尾が伸びていく。炎の尾が最大長（発動1.2秒後）になった瞬間にタップして逆噴射ブレーキをかけると急速な速度変化で敵ミサイルをやり過ごせる——最大長前後では減速が不十分でミサイルに追いつかれる。5回回避でクリア。',
    objects: [
      { shape: 'triangle', role: 'バルキリー（加速中）', note: '' },
      { shape: 'rect', role: '炎の尾（伸びていく）', note: '最大長時に最大輝度' },
      { shape: 'circle', role: '敵ミサイル（追尾中）', note: '' },
    ],
    counters: [
      { id: 'evades', name: '回避数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '炎の尾が最大長になった瞬間タップ5回',
    failTrigger: '最大長前後にタップ3回で失敗',
  },
  {
    id: 'arcade-369',
    title: 'スーパーバスケットボール',
    brand: 'KONAMI',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: 'プレイヤーが跳び上がりリングに接近する。プレイヤーの手がリングの高さとぴったり一致した「ダンク可能高度（0.3秒間）」にタップしてボールを叩き込む——高度が低すぎると届かない、高すぎるとリングに当たって入らない。5回ダンクでクリア。',
    objects: [
      { shape: 'face', role: 'プレイヤー（ジャンプ中）', note: 'ダンク可能高度で光る' },
      { shape: 'circle', role: 'バスケットボール（手に持つ）', note: '' },
      { shape: 'circle', role: 'リング（ゴール）', note: '' },
    ],
    counters: [
      { id: 'dunks', name: 'ダンク数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'ダンク可能高度の瞬間タップ5回',
    failTrigger: '高度不足・超過でタップ3回で失敗',
  },
  {
    id: 'arcade-370',
    title: 'スティンガー',
    brand: 'セイブ開発',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: '地上の敵車両が橋の上を通過している。橋の中央（支柱のない一番もろい部分）を車両が通過した瞬間に爆弾を投下すると橋ごと落とせる——橋の端では構造が頑丈なので車は助かってしまう。3回橋ごと爆破でクリア。',
    objects: [
      { shape: 'rect', role: '橋（中央が弱い）', note: '' },
      { shape: 'rect', role: '敵車両（橋を渡る）', note: '中央通過時に光る' },
      { shape: 'triangle', role: '自機（上空）', note: '' },
    ],
    counters: [
      { id: 'bridge', name: '橋ごと爆破数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '車両が橋の中央を通過した瞬間タップ3回',
    failTrigger: '橋の端を通過中にタップ3回で失敗',
  },
  {
    id: 'arcade-371',
    title: 'THE運動会',
    brand: 'タイトー',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: '借り物競走のゴール前に複数の人が並んでいる。「借り物リスト」に合った人物（帽子をかぶった人、など）を見つけて手を取る——正解の人がこちらを向いて「OKサイン」を出した瞬間にタップして手を取る。OKサインを出す前に触ると拒否される。5回正解ピックアップでクリア。',
    objects: [
      { shape: 'face', role: '正解の人（OKサインを出す）', note: 'OKサイン時に光る' },
      { shape: 'face', role: '不正解の人×複数', note: '' },
      { shape: 'face', role: '走者（中央）', note: '' },
    ],
    counters: [
      { id: 'picks', name: '正解ピックアップ数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'OKサインが出た瞬間タップ5回',
    failTrigger: 'OKサイン前にタップ3回で失敗',
  },
  {
    id: 'arcade-372',
    title: 'ディー・デー',
    brand: 'ジャレコ',
    year: 1984,
    duration: 20,
    difficulty: 'hard',
    concept: '砂浜に並ぶ機銃座が絶え間なく弾を撃ってくる。機銃座が「装填中（再装填の瞬間）」だけ弾が出ない——装填中の0.4秒に入ったことを示す「装填ランプ消灯」の瞬間にタップして前進。撃っている間に前進すると被弾する。5回安全前進でクリア。',
    objects: [
      { shape: 'rect', role: '機銃座（撃ち続ける）', note: '装填中は銃口が暗くなる' },
      { shape: 'face', role: '兵士（前進待機）', note: '' },
    ],
    counters: [
      { id: 'advances', name: '安全前進数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '機銃座が装填中（暗い）の瞬間タップ5回',
    failTrigger: '発射中に前進3回で失敗',
  },
  {
    id: 'arcade-373',
    title: 'アクアジェット',
    brand: 'ナムコ',
    year: 1996,
    duration: 20,
    difficulty: 'normal',
    concept: '水上バイクが波に差し掛かり、波の傾斜が「最急角度（最大勾配）」に達した瞬間にタップして飛び上がりボタンを押すと最大高度のウェーブジャンプになる——最急角度前では高度が足りない、最急角度後は波が崩れて失速する。5回最大高度ジャンプでクリア。',
    objects: [
      { shape: 'triangle', role: '水上バイク（波に乗る）', note: '' },
      { shape: 'ellipse', role: '波（傾斜が変化）', note: '最急角度時に光る' },
    ],
    counters: [
      { id: 'jumps', name: '最大高度ジャンプ数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '波の最急角度の瞬間タップ5回',
    failTrigger: '最急角度前後にタップ3回で失敗',
  },
  {
    id: 'arcade-374',
    title: '航空騎兵物語',
    brand: 'SNK',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '山岳地帯の谷間を低空飛行するヘリコプター。谷の幅が変化しており、幅が「最大（最も広い瞬間）」に達した時にタップして急降下ロケット攻撃をすると地上目標に届く——幅が狭い時に急降下すると岩壁に当たる。3回急降下攻撃でクリア。',
    objects: [
      { shape: 'rect', role: '谷間（幅が変化）', note: '幅最大時に光る' },
      { shape: 'triangle', role: 'ヘリコプター（上空）', note: '' },
      { shape: 'rect', role: '地上目標（谷底）', note: '' },
    ],
    counters: [
      { id: 'attacks', name: '急降下攻撃数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '谷の幅が最大の瞬間タップ3回',
    failTrigger: '幅が狭い時タップ3回で失敗',
  },
  {
    id: 'arcade-375',
    title: 'スクランブル・エッグ',
    brand: 'テクノスジャパン',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: '卵キャリアを狙う複数の敵が全員「同じ方向を向く瞬間（0.5秒）」がある——全員が同じ方向を向いた瞬間にタップして反対方向に卵を転がすと全員の死角に入れる。向きがバラバラな時に動くと必ず誰かに見られる。5回死角突破でクリア。',
    objects: [
      { shape: 'face', role: '敵×複数（向きが変わる）', note: '全員同方向で光る' },
      { shape: 'ellipse', role: '卵（転がす）', note: '' },
      { shape: 'face', role: 'キャリア（中央）', note: '' },
    ],
    counters: [
      { id: 'escapes', name: '死角突破数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '全員同方向の瞬間タップ5回',
    failTrigger: '向きバラバラ時タップ3回で失敗',
  },
  {
    id: 'arcade-376',
    title: 'マッハブレイカーズ',
    brand: 'ナムコ',
    year: 1995,
    duration: 20,
    difficulty: 'hard',
    concept: '拳を打ち込む速度が上昇し続ける。速度が「マッハ1（音速）」を超えた瞬間——拳速メーターがマッハ1のラインを超えた刹那にタップしてブレイク発動。マッハ1未満では通常打撃、超えてから1秒以上経過すると摩擦熱で拳が傷む。3回マッハブレイクでクリア。',
    objects: [
      { shape: 'face', role: '自キャラ（打撃モーション）', note: '' },
      { shape: 'rect', role: '拳速メーター（上昇中）', note: 'マッハ1超えで光る' },
      { shape: 'face', role: '対戦相手（前方）', note: '' },
    ],
    counters: [
      { id: 'breakers', name: 'マッハブレイク数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '拳速マッハ1超えの瞬間タップ3回',
    failTrigger: 'マッハ1未満・1秒超過でタップ3回で失敗',
  },
  {
    id: 'arcade-377',
    title: 'ビデオハスラー',
    brand: 'KONAMI',
    year: 1981,
    duration: 20,
    difficulty: 'normal',
    concept: 'ビリヤードのキューが最大引き量まで引かれていく。ストロークゲージが「完全引き切り（最大後退点）」に達した瞬間にタップして打ち出すと最大威力の完璧なショットになる——引き切る前に打つと力不足、引き切った後に打つとフォームが崩れる。5回完璧ショットでクリア。',
    objects: [
      { shape: 'rect', role: 'キュー（引き量が変化）', note: '完全引き切りで光る' },
      { shape: 'circle', role: '手球（撞く前）', note: '' },
      { shape: 'rect', role: 'ストロークゲージ', note: '' },
    ],
    counters: [
      { id: 'shots', name: '完璧ショット数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'キュー完全引き切りの瞬間タップ5回',
    failTrigger: '引き切り前後にタップ3回で失敗',
  },
  {
    id: 'arcade-378',
    title: 'スチールワーカー',
    brand: 'タイトー',
    year: 1980,
    duration: 20,
    difficulty: 'normal',
    concept: '鉄骨の上を歩く作業員。鉄骨が左右に揺れており、「水平（揺れが完全に止まる瞬間）」になった0.3秒にタップして次の鉄骨に踏み出す——揺れている間は足を踏み出すと転落する。水平は一周の揺れの中で一瞬だけ訪れる。5回安全渡りでクリア。',
    objects: [
      { shape: 'rect', role: '鉄骨（左右に揺れる）', note: '水平時に光る' },
      { shape: 'face', role: '作業員（渡ろうとする）', note: '' },
    ],
    counters: [
      { id: 'crosses', name: '安全渡り数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '鉄骨が水平の瞬間タップ5回',
    failTrigger: '揺れている間にタップ3回で失敗',
  },
  {
    id: 'arcade-379',
    title: 'ダチョラー',
    brand: '日本物産',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: 'ダチョウに乗ってレースする。コース上の石が自分のレーンと隣レーンの境界線上を通過する瞬間——石が境界線上に来た瞬間（両レーンの中央）にタップしてレーン変更すると踏まずに済む。境界を過ぎてから変更すると自分のレーンに入ってきた石を踏む。5回障害物回避でクリア。',
    objects: [
      { shape: 'circle', role: '石・障害物（レーン上を動く）', note: '境界線上で光る' },
      { shape: 'face', role: 'ダチョウ騎手（自レーン）', note: '' },
      { shape: 'rect', role: 'レーン境界線', note: '' },
    ],
    counters: [
      { id: 'dodges', name: '障害物回避数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '石が境界線上にある瞬間タップ5回',
    failTrigger: '境界を過ぎてから変更3回で失敗',
  },
] as const;
