/**
 * ideas/arcade-2024q3.ts
 * Arcade Archives 2024年7〜9月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2024q3Ideas = [
  {
    id: 'arcade-315',
    title: '妖魔忍法帖',
    brand: 'ニチブツ',
    year: 1986,
    duration: 20,
    difficulty: 'hard',
    concept: '忍者が壁蹴り二段跳びで敵陣を突破する。1回目のタップで壁に張り付き、壁に完全密着した瞬間（ぴたりと止まった刹那）に2回目のタップで壁を蹴って飛び越える——2回のタップの間に0.3秒の間を置く必要がある。1回タップでは壁を越えられない。5回二段跳び突破でクリア。',
    objects: [
      { shape: 'rect', role: '壁（垂直）', note: '' },
      { shape: 'face', role: '忍者（走ってくる）', note: '壁密着時に光る' },
      { shape: 'face', role: '敵（壁の向こう）', note: '' },
    ],
    counters: [
      { id: 'jumps', name: '二段跳び突破数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '壁密着後0.3秒以内に2回目タップ×5回',
    failTrigger: '密着前に2回目タップ3回で失敗',
  },
  {
    id: 'arcade-316',
    title: 'ティンクルピット',
    brand: 'ナムコ',
    year: 1993,
    duration: 20,
    difficulty: 'normal',
    concept: '縄を横方向に投げて敵を縛り上げる。敵が縄の有効射程内（一直線上）を移動してくる——敵と縄の発射点が完全に一直線に並んだ瞬間にタップして縄を投げる。斜め方向や射程外には届かない。縛った敵はその場で穴に落とせる。5回縛りでクリア。',
    objects: [
      { shape: 'ellipse', role: '縄（横方向に飛ぶ）', note: '一直線時に光る' },
      { shape: 'face', role: '敵（一直線上を移動）', note: '' },
      { shape: 'face', role: 'ティンクル（中央）', note: '' },
    ],
    counters: [
      { id: 'binds', name: '縛り数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '敵が一直線に並んだ瞬間タップ5回',
    failTrigger: 'ズレた位置でタップ3回で失敗',
  },
  {
    id: 'arcade-317',
    title: 'ハットトリックヒーロー',
    brand: 'タイトー',
    year: 1990,
    duration: 20,
    difficulty: 'normal',
    concept: 'コーナーキックでボールが弧を描いて飛んでくる。ゴール前に味方3人とディフェンダー2人が混在している。最も高い位置に跳び上がった味方選手の頭頂（ジャンプ頂点）にボールが来た瞬間にタップしてヘディングシュート——頂点を外すとミスヘッドになる。3回ゴールでクリア。',
    objects: [
      { shape: 'circle', role: 'サッカーボール（弧を描いて飛ぶ）', note: '' },
      { shape: 'face', role: '味方選手×3（ジャンプする）', note: '頂点で光る' },
      { shape: 'face', role: 'ディフェンダー×2（邪魔する）', note: '' },
    ],
    counters: [
      { id: 'goals', name: 'ゴール数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '味方のジャンプ頂点にボールが来た瞬間タップ3回',
    failTrigger: 'タイミングズレのヘッド3回で失敗',
  },
  {
    id: 'arcade-318',
    title: 'VS.ワルキューレの冒険 時の鍵伝説',
    brand: 'ナムコ',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: '時の鍵が回転しながら「封印角度」に向かっている。鍵の面に刻まれた紋様が特定の「封印角度」（黄金色に輝く位置）に来た瞬間にタップして鍵を魔物に差し込む。封印角度を一瞬でも過ぎると次の回転まで待たなければならない。5回封印でクリア。',
    objects: [
      { shape: 'diamond', role: '時の鍵（回転する）', note: '封印角度で黄金色に輝く' },
      { shape: 'face', role: '魔物（前方）', note: '' },
      { shape: 'face', role: 'ワルキューレ（中央）', note: '' },
    ],
    counters: [
      { id: 'seals', name: '封印数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '鍵が封印角度に来た瞬間タップ5回',
    failTrigger: '封印角度を過ぎてからタップ3回で失敗',
  },
  {
    id: 'arcade-319',
    title: 'ハードパンチャー 血まみれの栄光',
    brand: 'KONAMI',
    year: 1988,
    duration: 20,
    difficulty: 'hard',
    concept: 'ボクサーは連続ヒットで「コンビネーション倍率」が積み上がる。倍率×3になった直後の0.3秒間（コンビネーション光が点灯中）にタップするとスーパーボディブロー発動——×3より前では通常攻撃、光が消えてからでは倍率がリセットされる。3回スーパーボディブローでクリア。',
    objects: [
      { shape: 'face', role: '対戦相手（ボクサー）', note: '' },
      { shape: 'rect', role: 'コンビネーション倍率表示', note: '×3時に光る' },
      { shape: 'face', role: '自キャラ（左）', note: '' },
    ],
    counters: [
      { id: 'supers', name: 'スーパーボディブロー数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '×3コンビネーション光点灯中タップ3回',
    failTrigger: '光消灯後タップ3回で失敗',
  },
  {
    id: 'arcade-320',
    title: 'でろ～んでろでろ',
    brand: 'テクモ',
    year: 1995,
    duration: 20,
    difficulty: 'normal',
    concept: 'スライムの粘度が時間で変化している。粘度ゲージが最大（最もねばねば）になった瞬間に敵をタップして絡みつくと、敵の動きを完全停止できる。粘度が低い時は敵がスライムをすり抜けてしまう。粘度ゲージ最大の瞬間だけを狙う。5回完全絡みつきでクリア。',
    objects: [
      { shape: 'ellipse', role: 'スライム（粘度が変化）', note: '粘度最大時に光る' },
      { shape: 'rect', role: '粘度ゲージ', note: '' },
      { shape: 'face', role: '敵（接近してくる）', note: '' },
    ],
    counters: [
      { id: 'sticks', name: '完全絡みつき数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '粘度ゲージ最大の瞬間タップ5回',
    failTrigger: '粘度不足時タップ3回で失敗',
  },
  {
    id: 'arcade-321',
    title: 'ナックルヘッズ',
    brand: 'ナムコ',
    year: 1993,
    duration: 20,
    difficulty: 'hard',
    concept: '相手キャラが攻撃を繰り出す直前に「予備動作」として一瞬足が浮く。足が浮いた瞬間（0.2秒）にタップしてカウンター姿勢をとると、相手の攻撃が当たった瞬間に自動カウンターヒットが炸裂する——予備動作前や動作後は通常被弾する。5回カウンターでクリア。',
    objects: [
      { shape: 'face', role: '相手キャラ（攻撃直前）', note: '足が浮く瞬間に光る' },
      { shape: 'face', role: '自キャラ（左側）', note: '' },
    ],
    counters: [
      { id: 'counters', name: 'カウンター数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '予備動作（足浮き）の瞬間タップ5回',
    failTrigger: '予備動作外でタップ3回で失敗',
  },
  {
    id: 'arcade-322',
    title: 'ニンジャキッズ',
    brand: 'タイトー',
    year: 1990,
    duration: 20,
    difficulty: 'normal',
    concept: '手裏剣ブーメランが前方に飛んで戻ってくる。ブーメランが元の位置に戻ってくる「キャッチポイント」にタップしてキャッチすると、ブーメランに魔力が宿って威力2倍で再発射できる——キャッチポイントを外すとブーメランが落下する。3回再キャッチ発射でクリア。',
    objects: [
      { shape: 'star', role: '手裏剣ブーメラン（往復する）', note: 'キャッチポイントで光る' },
      { shape: 'face', role: '忍者キッズ（中央）', note: '' },
      { shape: 'face', role: '敵（前方）', note: '' },
    ],
    counters: [
      { id: 'catches', name: '再キャッチ発射数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'キャッチポイントでタップ3回',
    failTrigger: 'ポイント外でタップ3回で失敗',
  },
  {
    id: 'arcade-323',
    title: 'ファイナライザー',
    brand: 'KONAMI',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: 'ファイナライザーのレーザーは発射後1秒で最大出力に達する。レーザーの輝度と太さが最大（最大出力の瞬間）になった時にタップして「収束照射」をロックオン確定すると全エネルギーが照準に集中する——最大出力前後では照準がブレる。5回収束照射でクリア。',
    objects: [
      { shape: 'rect', role: 'レーザー（輝度・太さが変化）', note: '最大出力時に白く輝く' },
      { shape: 'triangle', role: 'ファイナライザー自機（中央）', note: '' },
      { shape: 'face', role: '敵機（上部）', note: '' },
    ],
    counters: [
      { id: 'locks', name: '収束照射数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'レーザー最大出力の瞬間タップ5回',
    failTrigger: '出力不足・超過でタップ3回で失敗',
  },
  {
    id: 'arcade-324',
    title: 'リードアングル',
    brand: 'セイブ開発',
    year: 1988,
    duration: 20,
    difficulty: 'hard',
    concept: '走る敵を撃つには「先読み射撃」が必要。弾の軌跡を示す破線が敵の移動速度から計算した「予測交点」に重なった瞬間にタップして発射——破線と予測交点がズレた状態で撃つと必ず外れる。予測交点は敵の速度変化で移動するので常に判断が必要。5回予測射撃命中でクリア。',
    objects: [
      { shape: 'face', role: '走る敵（横移動）', note: '' },
      { shape: 'star', role: '予測交点（移動する）', note: '破線と重なると光る' },
      { shape: 'rect', role: '弾軌跡の破線', note: '' },
    ],
    counters: [
      { id: 'hits', name: '予測射撃命中数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '破線が予測交点に重なった瞬間タップ5回',
    failTrigger: 'ズレた状態で発射3回で失敗',
  },
  {
    id: 'arcade-325',
    title: 'VS.バトルシティー',
    brand: 'ナムコ',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: '相手タンクが自軍基地を目指して直進してくる。基地前に鉄壁ブロックが並んでいるが1か所だけ隙間がある——相手の砲身の向きと隙間の位置が一致した瞬間にタップして自機が隙間を塞ぐ。隙間が一致する前に動くと別の隙間を開けてしまう。3回阻止でクリア。',
    objects: [
      { shape: 'rect', role: '相手タンク（接近する）', note: '砲身向きが赤く光る' },
      { shape: 'rect', role: '鉄壁ブロック列（隙間あり）', note: '' },
      { shape: 'rect', role: '自タンク（移動可能）', note: '' },
    ],
    counters: [
      { id: 'blocks', name: '阻止数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '砲身と隙間が一致した瞬間タップ3回',
    failTrigger: '一致前にタップ3回で失敗',
  },
  {
    id: 'arcade-326',
    title: 'クライムシティ',
    brand: 'タイトー',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: '敵が投げてきたダイナマイトをキャッチして投げ返す。ダイナマイトの残り爆発時間が「0.5秒」になった瞬間にタップして敵陣へ投げ返す——1秒より早く投げると届く前に爆発、0.5秒より遅いと自分が被弾する。0.5秒の1フレームを正確にとらえる。5回投げ返しでクリア。',
    objects: [
      { shape: 'bomb', role: 'ダイナマイト（カウントダウン中）', note: '残り0.5秒で光る' },
      { shape: 'face', role: '刑事（中央）', note: '' },
      { shape: 'face', role: '敵（前方）', note: '' },
    ],
    counters: [
      { id: 'throws', name: '投げ返し数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '残り0.5秒の瞬間タップ5回',
    failTrigger: '早すぎ・遅すぎタップ3回で失敗',
  },
  {
    id: 'arcade-327',
    title: 'ブラストオフ',
    brand: 'ナムコ',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: '惑星間空間に重力場が漂っている。重力場の「引力最強点（中心）」を弾が通過すると弾が急加速して敵に向かう——弾を発射して、弾が引力最強点を通過した瞬間にタップして加速を起動。通過前後でタップしても加速しない。5回加速ヒットでクリア。',
    objects: [
      { shape: 'circle', role: '重力場（画面上に漂う）', note: '引力最強点が白く輝く' },
      { shape: 'triangle', role: 'ブラストオフ自機（中央）', note: '' },
      { shape: 'face', role: '敵機（上部）', note: '' },
    ],
    counters: [
      { id: 'hits', name: '加速ヒット数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '弾が引力最強点を通過した瞬間タップ5回',
    failTrigger: '通過前後にタップ3回で失敗',
  },
] as const;
