/**
 * ideas/arcade-2015.ts
 * Arcade Archives 2015年配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2015Ideas = [
  {
    id: 'arcade-019',
    title: '出世大相撲',
    brand: 'テクノスジャパン',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: '相手力士が踏み込んでくる。重心が前に移った（前のめりになった）瞬間だけ押し出し技が決まる。重心の後ろ側でタップすると逆に押し込まれる。3回押し出しでクリア。',
    objects: [
      { shape: 'face', role: '自分の力士（右側）', note: '' },
      { shape: 'face', role: '相手力士（左側）', note: '前のめり↔後ろ体重でアニメ変化' },
      { shape: 'button', role: '押し出しボタン', note: '' },
    ],
    counters: [
      { id: 'pushouts', name: '押し出し数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'counter pushouts >= 3',
    failTrigger: '逆に押し込まれた回数3回で失敗',
  },
  {
    id: 'arcade-020',
    title: 'グラディウス',
    brand: 'KONAMI',
    year: 1985,
    duration: 25,
    difficulty: 'normal',
    concept: '自機の前方をパワーアップカプセルが列をなして流れてくる。タップするたびにカーソルが1つ進む。「LASER」の位置で止めたい——欲しいアイテムにカーソルが合った瞬間に取得タップ。',
    objects: [
      { shape: 'rect', role: 'パワーアップゲージ（SPEED/MISSILE/DOUBLE/LASER/OPTION/?）', note: 'カーソルが移動' },
      { shape: 'button', role: 'セレクトボタン', note: 'タップでカーソル前進' },
      { shape: 'button', role: '取得ボタン', note: 'タップで確定' },
    ],
    counters: [
      { id: 'upgrades', name: '取得数', target: 3, note: 'LASERを3回取得でクリア' },
    ],
    winTrigger: 'LASER位置で取得タップ3回',
    failTrigger: '外れアイテム取得3回で失敗',
  },
  {
    id: 'arcade-021',
    title: 'クレイジー・クライマー2',
    brand: 'ニチブツ',
    year: 1988,
    duration: 25,
    difficulty: 'normal',
    concept: 'ビルの側面に看板や横断幕が突き出している。看板の端が手の届く位置に来た瞬間にタップして掴み、体を回してその上に乗り移る。看板3枚を渡り切ればクリア。',
    objects: [
      { shape: 'rect', role: '看板1（横移動）', note: '' },
      { shape: 'rect', role: '看板2（横移動）', note: '' },
      { shape: 'rect', role: '看板3（横移動）', note: '' },
      { shape: 'face', role: 'クライマー', note: '' },
    ],
    counters: [
      { id: 'boards', name: '渡った看板数', target: 3, note: '3枚でクリア' },
    ],
    winTrigger: 'counter boards >= 3',
    failTrigger: '看板の端を外してタップ3回で落下失敗',
  },
  {
    id: 'arcade-022',
    title: 'ぶたさん',
    brand: 'ジャレコ',
    year: 1987,
    duration: 20,
    difficulty: 'easy',
    concept: '子豚がゴールへ向かうが、途中に穴が3か所ある。穴の手前でタップすると豚が膨らんで浮き上がる。浮遊できるのは3秒間——穴を渡り切ったらタップを離して着地。タイミングを外すと落下。',
    objects: [
      { shape: 'ellipse', role: '子豚（右へ自動移動）', note: '膨らみ/縮みアニメ' },
      { shape: 'rect', role: '穴×3', note: '地面の欠け' },
    ],
    counters: [
      { id: 'holes', name: '渡った穴数', target: 3, note: '3か所渡りきりでクリア' },
    ],
    winTrigger: 'counter holes >= 3',
    failTrigger: '穴に落ちたら失敗',
  },
  {
    id: 'arcade-023',
    title: 'A-JAX',
    brand: 'KONAMI',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '戦闘機が空中モードと地上攻撃モードを3秒ごとに切り替わる。切り替え直後の0.5秒で対応する敵（空：飛行機、地上：戦車）が攻撃チャンスになる。切り替わった瞬間に敵をタップして撃墜。',
    objects: [
      { shape: 'triangle', role: '自機', note: '' },
      { shape: 'diamond', role: '飛行機敵（空中モード時に有効）', note: '' },
      { shape: 'rect', role: '戦車敵（地上モード時に有効）', note: '' },
    ],
    counters: [
      { id: 'kills', name: '撃墜数', target: 6, note: '6体（空3+地3）でクリア' },
    ],
    winTrigger: 'counter kills >= 6',
    failTrigger: 'モードが合わない敵をタップ3回で失敗',
  },
  {
    id: 'arcade-024',
    title: 'マグマックス',
    brand: 'ニチブツ',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: 'ロボットのパーツが3か所に散らばっている。上半身→下半身→武器装備の正しい順序でタップしないと合体できない。順番を間違えると全パーツが再散乱する。',
    objects: [
      { shape: 'rect', role: '上半身パーツ', note: '' },
      { shape: 'rect', role: '下半身パーツ', note: '' },
      { shape: 'star', role: '武器パーツ', note: '' },
    ],
    counters: [
      { id: 'parts', name: '正順収集数', target: 3, note: '順序通り3個でクリア' },
    ],
    winTrigger: '上半身→下半身→武器の順にタップ完了',
    failTrigger: '順番間違い3回で失敗',
  },
  {
    id: 'arcade-025',
    title: 'コスモポリスギャリバン',
    brand: 'ニチブツ',
    year: 1985,
    duration: 20,
    difficulty: 'hard',
    concept: 'ギャリバンが人間形態とアンドロイド形態の間で変身できる。敵のビームが飛んでくる発射エフェクトの0.5秒にタップして耐弾アンドロイド形態に切り替え、ビームを弾け。人間形態のまま被弾すると失敗。',
    objects: [
      { shape: 'face', role: 'ギャリバン（人間↔アンドロイド切替）', note: '' },
      { shape: 'circle', role: '敵兵（ビーム発射）', note: '' },
    ],
    counters: [
      { id: 'deflects', name: 'ビーム弾き数', target: 5, note: '5回弾くでクリア' },
    ],
    winTrigger: 'counter deflects >= 5',
    failTrigger: '人間形態で被弾で即失敗',
  },
  {
    id: 'arcade-026',
    title: 'いっき',
    brand: 'サン電子',
    year: 1985,
    duration: 20,
    difficulty: 'easy',
    concept: '年貢取りが画面右へ逃げながら銭袋を落としていく。銭袋が地面に落ちて消える前にタップして拾え。全5袋を制限時間内に回収してクリア。',
    objects: [
      { shape: 'circle', role: '銭袋×5（順番に落下）', note: '地面に着いて2秒で消える' },
      { shape: 'face', role: '農民（自キャラ）', note: '' },
    ],
    counters: [
      { id: 'bags', name: '回収数', target: 5, note: '5袋でクリア' },
    ],
    winTrigger: 'counter bags >= 5',
    failTrigger: '袋が3個消えたら失敗',
  },
  {
    id: 'arcade-027',
    title: '忍者くん 阿修羅ノ章',
    brand: 'UPL',
    year: 1987,
    duration: 20,
    difficulty: 'hard',
    concept: '4方向から同時に敵が迫る。4体の中で攻撃アニメが最も短い（最速で攻撃してくる）敵だけが先に危険になる。その敵の攻撃モーション開始直後にタップして先制撃破。',
    objects: [
      { shape: 'star', role: '上方の敵', note: '攻撃速度ランダム' },
      { shape: 'star', role: '下方の敵', note: '攻撃速度ランダム' },
      { shape: 'star', role: '左方の敵', note: '攻撃速度ランダム' },
      { shape: 'star', role: '右方の敵', note: '攻撃速度ランダム' },
    ],
    counters: [
      { id: 'preempts', name: '先制数', target: 3, note: '3回先制成功でクリア' },
    ],
    winTrigger: 'counter preempts >= 3',
    failTrigger: '攻撃を受けたら失敗',
  },
  {
    id: 'arcade-028',
    title: '上海III',
    brand: 'サンソフト',
    year: 1993,
    duration: 30,
    difficulty: 'normal',
    concept: '5段に積み重なった牌の中で取れるペアが3組ある。ゲーム開始後3秒間だけ正解の組み合わせがハイライトされる。記憶して正しいペアの片方をタップし、もう片方をタップして消去。3組全消しでクリア。',
    objects: [
      { shape: 'rect', role: '牌（複数）', note: 'ランダム配置、3秒だけ正解がハイライト' },
    ],
    counters: [
      { id: 'pairs', name: '消去ペア数', target: 3, note: '3ペアでクリア' },
    ],
    winTrigger: 'counter pairs >= 3',
    failTrigger: 'ペアにならない牌をタップ3回で失敗',
  },
  {
    id: 'arcade-029',
    title: '熱血高校ドッジボール部',
    brand: 'テクノスジャパン',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '相手チームの4番選手が大回転投法でボールを投げてくる。ボールの回転方向（左回り/右回り）を見て、同方向にタップするとキャッチ成功。逆方向タップはふっとばされる。3回キャッチでクリア。',
    objects: [
      { shape: 'circle', role: 'ドッジボール（回転表示）', note: '左回り/右回りがランダム' },
      { shape: 'face', role: '自チームキャプテン', note: '' },
      { shape: 'button', role: '左回りキャッチ', note: '' },
      { shape: 'button', role: '右回りキャッチ', note: '' },
    ],
    counters: [
      { id: 'catches', name: 'キャッチ数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'counter catches >= 3',
    failTrigger: '逆方向タップ3回で失敗',
  },
  {
    id: 'arcade-030',
    title: 'スターフォース',
    brand: 'テーカン',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: 'SPECIALフラッグが5×3の敵群の中に1枚だけ混ざっている。敵群が通過するとき、SPECIALだけをタップして撃ち抜け。通常の敵をタップするとボーナスが消滅する。',
    objects: [
      { shape: 'diamond', role: '通常敵×14', note: '' },
      { shape: 'star', role: 'SPECIALフラッグ×1', note: '敵群内にランダム配置' },
    ],
    counters: [
      { id: 'specials', name: 'SPECIAL取得数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'counter specials >= 3',
    failTrigger: '通常敵タップ3回でボーナス消滅→失敗',
  },
  {
    id: 'arcade-031',
    title: '影の伝説',
    brand: 'タイトー',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: '忍者が屋根を伝って走る。次の屋根へ飛び移るには、ジャンプ弧の頂点が次の屋根の端と重なった瞬間にタップして方向を切り替える。5棟の屋根を渡り切ればクリア。',
    objects: [
      { shape: 'triangle', role: '忍者（走行・ジャンプ）', note: '' },
      { shape: 'rect', role: '屋根×5', note: '高さが微妙に異なる' },
    ],
    counters: [
      { id: 'roofs', name: '渡った屋根数', target: 5, note: '5棟でクリア' },
    ],
    winTrigger: 'counter roofs >= 5',
    failTrigger: '頂点を外してタップで落下→失敗',
  },
  {
    id: 'arcade-032',
    title: '沙羅曼蛇',
    brand: 'KONAMI',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: '有機体の壁が左右から迫り通路を塞いでいく。壁面に6つの細胞がある。通路がちょうど機体1機分の幅になった0.5秒の瞬間に、通路の中心点をタップして通過。',
    objects: [
      { shape: 'ellipse', role: '有機細胞×6（左右から迫る）', note: '' },
      { shape: 'triangle', role: '自機', note: '' },
    ],
    counters: [
      { id: 'passages', name: '通過数', target: 3, note: '3回通過でクリア' },
    ],
    winTrigger: 'counter passages >= 3',
    failTrigger: '壁に触れたら失敗',
  },
  {
    id: 'arcade-033',
    title: 'レネゲード',
    brand: 'テクノスジャパン',
    year: 1986,
    duration: 20,
    difficulty: 'hard',
    concept: '敵に羽交い締めにされた。タップ連打でもがき続け、5秒以内に脱出しなければゲームオーバー。脱出成功直後の0.5秒に反撃タップを入れると追加ダメージ——連打の速さが脱出タイムを決める。',
    objects: [
      { shape: 'face', role: '自キャラ（拘束中）', note: '' },
      { shape: 'face', role: '敵（拘束している）', note: '' },
      { shape: 'button', role: '脱出連打ボタン', note: '' },
    ],
    counters: [
      { id: 'escapes', name: '脱出数', target: 3, note: '3回脱出でクリア' },
      { id: 'taps', name: '連打数', target: 8, note: '8回連打で拘束解除' },
    ],
    winTrigger: 'counter escapes >= 3',
    failTrigger: '5秒以内に連打8回未達で失敗',
  },
  {
    id: 'arcade-034',
    title: 'ツインビー',
    brand: 'KONAMI',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: '雲をタップすると星型ベルが飛び出し、ベルをさらにタップするたびに色が変わる（白→黄→緑→消滅）。白の瞬間（飛び出し直後）に回収タップすると最強パワーアップ。3個白で取ればクリア。',
    objects: [
      { shape: 'ellipse', role: '雲×3', note: 'タップするとベル出現' },
      { shape: 'star', role: 'ベル（白/黄/緑と変色）', note: '' },
      { shape: 'triangle', role: 'ツインビー', note: '' },
    ],
    counters: [
      { id: 'whiteBells', name: '白ベル取得数', target: 3, note: '3個でクリア' },
    ],
    winTrigger: 'counter whiteBells >= 3',
    failTrigger: '黄・緑で取得すると不正解カウント、3回で失敗',
  },
] as const;
