/**
 * ideas/arcade-2023q2.ts
 * Arcade Archives 2023年4〜6月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2023q2Ideas = [
  {
    id: 'arcade-251',
    title: 'レゾン',
    brand: 'アルュメ',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: '主人公がチェーン武器を振り回している。チェーンは体の周りを180度スイープする。敵が接近してくる方向を見極め、チェーンのスイープがその方向に到達した瞬間にタップして叩きつけ。スイープが通り過ぎてしまうと次のスイープまで待つ。5体撃退でクリア。',
    objects: [
      { shape: 'diamond', role: 'チェーン（180度スイープ）', note: '' },
      { shape: 'face', role: '主人公（中央）', note: '' },
      { shape: 'face', role: '敵（接近方向矢印付き）', note: 'チェーン到達時に光る' },
    ],
    counters: [
      { id: 'hit', name: '撃退数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'チェーンが敵方向に到達の瞬間タップ5回',
    failTrigger: 'スイープ外れタップ3回で失敗',
  },
  {
    id: 'arcade-252',
    title: 'ディグダグII',
    brand: 'ナムコ',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: '島の地面に亀裂を入れて地面ごとプーカやフライガーを海に沈める。亀裂4本で囲まれた区画を切り離せる。区画上に3体以上の敵が乗っているタイミングで最後の亀裂（4本目）を完成させてタップ——敵が移動して区画から出てしまう前に。3回3体以上同時沈没でクリア。',
    objects: [
      { shape: 'rect', role: '島の区画（亀裂で囲む）', note: '4本目完成で沈む' },
      { shape: 'face', role: 'プーカ×複数（区画を移動）', note: '3体以上で光る' },
      { shape: 'face', role: 'ディグダグ（亀裂を掘る）', note: '' },
    ],
    counters: [
      { id: 'sunk', name: '3体以上同時沈没数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '区画上3体以上の状態で4本目完成タップ3回',
    failTrigger: '区画上1〜2体で沈没3回で失敗',
  },
  {
    id: 'arcade-253',
    title: 'コズモギャング・ザ・ビデオ',
    brand: 'ナムコ',
    year: 1992,
    duration: 20,
    difficulty: 'hard',
    concept: 'コズモギャングのUFOがぞろぞろ飛んでいる。その中にリーダー（王冠付き）が1体混ざっており、0.5秒だけ中央に浮かび上がって見える。リーダーが浮かび上がった瞬間にタップして撃墜——普通の子分を撃っても効果が薄い。5回リーダー撃墜でクリア。',
    objects: [
      { shape: 'face', role: 'コズモギャング子分×複数（密集飛行）', note: '' },
      { shape: 'face', role: 'コズモギャングリーダー（王冠付き・0.5秒出現）', note: '' },
      { shape: 'triangle', role: '自機（下部）', note: '' },
    ],
    counters: [
      { id: 'leaders', name: 'リーダー撃墜数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'リーダー出現0.5秒以内にタップ5回',
    failTrigger: '子分を撃墜3回で失敗',
  },
  {
    id: 'arcade-254',
    title: "ギャラガ'88",
    brand: 'ナムコ',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: 'ワープ用のチップA・B・Cが画面を漂っている。A→B→Cの順に収集すると次元ワープが発動する。順番を間違えると最初からやり直し。3種のチップが入り混じっている中、正しい順番でタップして収集。3回ワープ完遂でクリア。',
    objects: [
      { shape: 'star', role: 'ワープチップA（赤）', note: '1番目に取る' },
      { shape: 'star', role: 'ワープチップB（青）', note: '2番目に取る' },
      { shape: 'star', role: 'ワープチップC（金）', note: '3番目に取る' },
      { shape: 'triangle', role: '自機（下部）', note: '' },
    ],
    counters: [
      { id: 'warps', name: 'ワープ完遂数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'A→B→Cの順序でタップ×3回',
    failTrigger: '順番ミスでリセット3回で失敗',
  },
  {
    id: 'arcade-255',
    title: 'ワイルドファング',
    brand: 'テクモ',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: '魔法戦士がスピンキックで敵の盾を破る。盾には亀裂（弱点方向）が入っており、スピンキックは亀裂の方向からしか通じない。亀裂の位置（上・右・下・左）を確認し、その方向から攻撃するボタンをタップ。5回盾破りでクリア。',
    objects: [
      { shape: 'rect', role: '敵の盾（亀裂方向付き）', note: '亀裂方向が矢印で示される' },
      { shape: 'face', role: '魔法戦士（中央）', note: '' },
      { shape: 'button', role: '上攻撃ボタン', note: '' },
      { shape: 'button', role: '右攻撃ボタン', note: '' },
      { shape: 'button', role: '下攻撃ボタン', note: '' },
      { shape: 'button', role: '左攻撃ボタン', note: '' },
    ],
    counters: [
      { id: 'breaks', name: '盾破り数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '亀裂方向と一致するボタンをタップ5回',
    failTrigger: '方向ミスタップ3回で失敗',
  },
  {
    id: 'arcade-256',
    title: 'マジンガーZ',
    brand: 'バンプレスト',
    year: 1994,
    duration: 20,
    difficulty: 'normal',
    concept: 'マジンガーZの両腕のロケットパンチゲージが独立して充填される。左右同時に満杯になった瞬間にタップしてダブルロケットパンチを発射。どちらかだけ満杯でも片腕しか出ない——両ゲージが同時に満杯になる一瞬を見逃さずタップ。3回ダブルで敵を撃破してクリア。',
    objects: [
      { shape: 'rect', role: '左腕充填ゲージ（独立充填）', note: '' },
      { shape: 'rect', role: '右腕充填ゲージ（独立充填）', note: '両方MAXで光る' },
      { shape: 'face', role: 'マジンガーZ（中央）', note: '' },
      { shape: 'face', role: 'ボス機械獣（右側）', note: '' },
    ],
    counters: [
      { id: 'double', name: 'ダブルロケットパンチ数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '両ゲージ同時MAX瞬間タップ3回',
    failTrigger: '片腕のみMAXでタップ3回で失敗',
  },
  {
    id: 'arcade-257',
    title: 'ローリングサンダー2',
    brand: 'ナムコ',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: 'エージェントが敵を倒すとその場に弾薬ケースが落ちる。ケースは1.5秒で消滅する——倒した直後にタップして素早く補給すれば弾切れを防げる。敵が連続で出現するため、補給のために立ち止まる瞬間を逃さずタップ。5回補給でクリア。',
    objects: [
      { shape: 'coin', role: '弾薬ケース（1.5秒で消滅）', note: '消えそうになると点滅' },
      { shape: 'face', role: 'エージェント（移動中）', note: '' },
      { shape: 'face', role: '敵（次々と出現）', note: '' },
    ],
    counters: [
      { id: 'resupply', name: '補給成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'ケース消滅前にタップ5回',
    failTrigger: 'ケースを消滅させた3回で失敗',
  },
  {
    id: 'arcade-258',
    title: 'テトリス ジ・アブソリュート ザ・グランドマスター2 PLUS',
    brand: 'アリカ',
    year: 2000,
    duration: 20,
    difficulty: 'hard',
    concept: '20Gモードでピースが瞬時に落下する。次の3ピースが予告表示される間に「どこに置くか」を3手先まで決めておく。3ピース全てを予告通りの位置に積んで横一列を完成させればトリプルクリア。1手でも予告と違う位置に置くとラインが崩れる。3回トリプルクリアでクリア。',
    objects: [
      { shape: 'rect', role: 'テトロミノ×3（予告表示）', note: '置き場所を事前計画' },
      { shape: 'rect', role: '積み上がりブロック', note: '' },
      { shape: 'button', role: '左移動ボタン', note: '' },
      { shape: 'button', role: '右移動ボタン', note: '' },
    ],
    counters: [
      { id: 'triples', name: 'トリプルクリア数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3ピース連続ライン完成×3回',
    failTrigger: 'ラインが崩れる3回で失敗',
  },
  {
    id: 'arcade-259',
    title: '超絶倫人ベラボーマン',
    brand: 'ナムコ',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: 'ベラボーマンのゴムのような腕が伸びていく。腕の長さゲージが表示され、敵のいる位置に「命中距離マーカー」が出る——ゲージが命中距離マーカーと一致した瞬間にタップして腕を飛ばす。短くても長くても空振り。5体命中でクリア。',
    objects: [
      { shape: 'rect', role: '腕の長さゲージ（伸長中）', note: '命中距離マーカー付き' },
      { shape: 'face', role: 'ベラボーマン（左端）', note: '' },
      { shape: 'face', role: '敵（各自異なる距離）', note: '' },
    ],
    counters: [
      { id: 'hit', name: '命中数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'ゲージが命中距離マーカーの瞬間タップ5回',
    failTrigger: 'ゲージズレタップ3回で失敗',
  },
  {
    id: 'arcade-260',
    title: 'メガブラスト',
    brand: 'タイトー',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: 'ヘリコプターが通常弾でザコ敵を倒すとメガブラストゲージが上昇する。ゲージMAXになった直後に装甲敵が登場する——装甲敵はメガブラストしか効かない。メガブラストゲージが満タンになった瞬間にタップして即発動。少しでも遅れると装甲敵が攻撃してくる。3体装甲敵撃破でクリア。',
    objects: [
      { shape: 'triangle', role: 'ヘリコプター（中央）', note: '' },
      { shape: 'rect', role: 'メガブラストゲージ（充填中）', note: '' },
      { shape: 'rect', role: '装甲敵（ゲージMAX後に出現）', note: '' },
    ],
    counters: [
      { id: 'armored', name: '装甲敵撃破数', target: 3, note: '3体でクリア' },
    ],
    winTrigger: 'ゲージMAX直後に装甲敵を3体撃破',
    failTrigger: '装甲敵の攻撃を3回受けて失敗',
  },
  {
    id: 'arcade-261',
    title: 'スプラッターハウス',
    brand: 'ナムコ',
    year: 1988,
    duration: 20,
    difficulty: 'hard',
    concept: 'テロールマスクの怒りゲージがリックが被弾するたびに上昇する。ゾンビが攻撃モーションを出した直後に被弾し（あえて受けて）ゲージを上げ、ゲージが「レイジゾーン」に入った瞬間にタップして渾身の反撃。普通の攻撃ではゾンビは倒れない。3体撃破でクリア。',
    objects: [
      { shape: 'face', role: 'テロールマスクのリック（左）', note: '' },
      { shape: 'rect', role: '怒りゲージ（被弾で上昇）', note: 'レイジゾーンで光る' },
      { shape: 'face', role: 'ゾンビ（攻撃モーション→被弾→スタン）', note: '' },
    ],
    counters: [
      { id: 'rage', name: 'レイジ反撃数', target: 3, note: '3体でクリア' },
    ],
    winTrigger: 'レイジゾーン中に反撃タップ3回',
    failTrigger: 'レイジゾーン外で反撃3回で失敗',
  },
  {
    id: 'arcade-262',
    title: 'COP 01',
    brand: 'ニチブツ',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: '警察ヘリのサーチライトが地面を移動している。犯人の車が他の一般車の間に混じっており、サーチライトの円が犯人車だけを完全に照らした（他の車がサーチライト内に入っていない）瞬間にタップしてロックオン。一般車も照らしているとロックオン失敗。5回ロックオンでクリア。',
    objects: [
      { shape: 'circle', role: 'サーチライト（地面を移動）', note: '' },
      { shape: 'rect', role: '犯人の車（一般車に混じって走る）', note: '単独照射時に光る' },
      { shape: 'rect', role: '一般車（複数）', note: '' },
    ],
    counters: [
      { id: 'locked', name: 'ロックオン成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '犯人車のみ照射の瞬間タップ5回',
    failTrigger: '一般車込みでロックオン3回で失敗',
  },
] as const;
