/**
 * ideas/arcade-2021q2.ts
 * Arcade Archives 2021年4〜6月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2021q2Ideas = [
  {
    id: 'arcade-152',
    title: 'サボテンボンバーズ',
    brand: 'NMK',
    year: 1992,
    duration: 20,
    difficulty: 'normal',
    concept: 'サボテン飛行機が水平移動しながら爆弾を投下する。地上の敵戦車も横移動している。飛行機の真下と戦車の位置が縦に一致した瞬間にタップして爆弾投下。飛行機と戦車の速度が異なるため、一致するタイミングを予測せよ。5台撃破でクリア。',
    objects: [
      { shape: 'triangle', role: 'サボテン飛行機（上部横移動）', note: '' },
      { shape: 'bomb', role: '爆弾（投下後に落下）', note: '' },
      { shape: 'rect', role: '敵戦車（地上横移動）', note: '' },
    ],
    counters: [
      { id: 'destroyed', name: '撃破数', target: 5, note: '5台でクリア' },
    ],
    winTrigger: 'counter destroyed >= 5',
    failTrigger: '爆弾が外れ3回で失敗',
  },
  {
    id: 'arcade-153',
    title: 'フリスキー・トム',
    brand: 'ニチブツ',
    year: 1981,
    duration: 20,
    difficulty: 'normal',
    concept: '建物の配管が各フロアで水漏れしている。トムがパイプを修理しようとすると猫が通路を横切る。猫が通路を通過し終えた直後にタップして修理開始。猫が通過中に修理を始めると捕まる。3本修理でクリア。',
    objects: [
      { shape: 'face', role: 'トム（配管工）', note: '' },
      { shape: 'rect', role: '漏水パイプ（光って示される）', note: '' },
      { shape: 'face', role: '猫（通路を横切る）', note: '通過中は赤、通過後は緑' },
    ],
    counters: [
      { id: 'fixed', name: '修理数', target: 3, note: '3本でクリア' },
    ],
    winTrigger: 'counter fixed >= 3',
    failTrigger: '猫の通過中に修理タップ3回で失敗',
  },
  {
    id: 'arcade-154',
    title: 'サンダークロスII',
    brand: 'KONAMI',
    year: 1991,
    duration: 25,
    difficulty: 'hard',
    concept: '2機の自機が上下に並んで飛んでいる。敵のシールドは左右両側から同時に撃たれた場合だけ貫通できる。シールドを持つ敵が2機の射線の間に来た瞬間にタップして両側から同時射撃。片側だけでは弾かれる。3機貫通でクリア。',
    objects: [
      { shape: 'triangle', role: '自機×2（上下に配置）', note: '' },
      { shape: 'rect', role: '敵シールド（左右両側射線に入ると光る）', note: '' },
      { shape: 'face', role: 'シールド持ち敵（中央付近）', note: '' },
    ],
    counters: [
      { id: 'pierced', name: '両側貫通数', target: 3, note: '3機でクリア' },
    ],
    winTrigger: '両射線同時ヒット3回',
    failTrigger: '片側だけヒット3回で失敗',
  },
  {
    id: 'arcade-155',
    title: 'ザ・ロードオブキング',
    brand: 'ジャレコ',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: '勇者が巨大な斧を縦に振り下ろす。斧のアーク（弧）が画面上を上から下へ通過する。敵の頭頂部がアークと同じ高さになった瞬間にタップして振り下ろせ。敵の高さが各自異なり、連続で異なるタイミングが求められる。5体撃破でクリア。',
    objects: [
      { shape: 'diamond', role: '斧（縦アーク、下向き）', note: '弧の高さが変化' },
      { shape: 'face', role: '勇者（中央）', note: '' },
      { shape: 'face', role: '敵（各自異なる高さ）', note: '' },
    ],
    counters: [
      { id: 'hits', name: '命中数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: 'counter hits >= 5',
    failTrigger: '空振り3回で失敗',
  },
  {
    id: 'arcade-156',
    title: 'ガズラー',
    brand: 'テーカン',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: 'ガズラーが迷路を自動的に移動している。廊下の交差点に着くたびに向いている方向が変わる。炎は向いている方向にしか噴射できない——敵が炎の射程内に入り、かつガズラーが敵の方を向いている瞬間にタップして噴射。方向が合っていないと外れる。5体焼却でクリア。',
    objects: [
      { shape: 'face', role: 'ガズラー（方向付き、迷路内移動）', note: '' },
      { shape: 'rect', role: '迷路通路', note: '' },
      { shape: 'face', role: '敵（迷路内）', note: '' },
      { shape: 'button', role: '炎噴射ボタン', note: '' },
    ],
    counters: [
      { id: 'burned', name: '焼却数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '方向一致+射程内でタップ5回',
    failTrigger: '方向外れ噴射3回で失敗',
  },
  {
    id: 'arcade-157',
    title: 'タスクフォースハリアー',
    brand: 'UPL',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: '敵の編隊がV字・W字・菱形などのフォーメーションで飛んでいる。自機の照準が編隊の中心に重なった瞬間だけ照準が金色に光る。金色になった瞬間にタップして一斉射撃すると全滅。中心がずれると一部しか当たらない。3編隊全滅でクリア。',
    objects: [
      { shape: 'triangle', role: '自機（下部）', note: '' },
      { shape: 'circle', role: '照準（中心一致で金色）', note: '' },
      { shape: 'face', role: '編隊敵×複数（フォーメーション飛行）', note: '' },
    ],
    counters: [
      { id: 'volleys', name: '全滅一斉射撃数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '照準金色の瞬間タップ3回',
    failTrigger: '照準ずれで一斉射撃3回で失敗',
  },
  {
    id: 'arcade-158',
    title: "タイムパイロット'84",
    brand: 'KONAMI',
    year: 1984,
    duration: 20,
    difficulty: 'hard',
    concept: '誘導ミサイルが真後ろから追いかけてくる。バレルロールで回避できるが、ロールのタイミングが悪いとロール中に被弾する。ミサイルとの距離インジケーターが「臨界ゾーン」に入った瞬間にタップしてロール。早すぎるとミサイルが再追尾、遅すぎると被弾。5回回避でクリア。',
    objects: [
      { shape: 'triangle', role: '自機（中央）', note: '' },
      { shape: 'diamond', role: '誘導ミサイル（真後ろから追尾）', note: '' },
      { shape: 'rect', role: '距離インジケーター（臨界ゾーン付き）', note: '' },
    ],
    counters: [
      { id: 'evades', name: '回避成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'インジケーターが臨界ゾーンでタップ5回',
    failTrigger: '被弾3回で失敗',
  },
  {
    id: 'arcade-159',
    title: 'はちゃめちゃファイター',
    brand: 'NMK',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: '騎士の剣が最後に倒した敵の属性を宿している。次の敵が出現すると弱点属性アイコンが表示される。剣が宿している属性と弱点が一致するときだけ攻撃が有効——一致中にタップして斬撃。属性が変わる前に素早く判断せよ。5体撃破でクリア。',
    objects: [
      { shape: 'diamond', role: '剣（宿し属性の色で表示）', note: '' },
      { shape: 'face', role: '騎士（左側）', note: '' },
      { shape: 'face', role: '敵（弱点属性アイコン付き）', note: '' },
    ],
    counters: [
      { id: 'slashed', name: '有効斬撃数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '属性一致中にタップ5回',
    failTrigger: '属性不一致タップ3回で失敗',
  },
  {
    id: 'arcade-160',
    title: 'パイレートピート',
    brand: 'タイトー',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: '海賊ピートが船のロープを登っている。敵が上から樽や岩を転がして投げてくる。転がる障害物の軌道が点線で予告される。点線が自分の位置を通過する直前にタップしてロープを持ち替えて横に避けよ。5個回避でクリア。',
    objects: [
      { shape: 'face', role: '海賊ピート（ロープ上）', note: '' },
      { shape: 'circle', role: '樽・岩（上から落下）', note: '' },
      { shape: 'diamond', role: '落下軌道予告（点線）', note: '' },
      { shape: 'rect', role: 'ロープ（左右に複数）', note: '' },
    ],
    counters: [
      { id: 'dodged', name: '回避数', target: 5, note: '5個でクリア' },
    ],
    winTrigger: 'counter dodged >= 5',
    failTrigger: '被弾3回で失敗',
  },
  {
    id: 'arcade-161',
    title: 'セクターゾーン',
    brand: 'ニチブツ',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: '未来バイクが高速で並走している。敵バイクと並列になった0.5秒間だけ体当たりが有効。並列ウィンドウはインジケーターに表示される——ゾーンに入った瞬間にタップして体当たり。ただし敵が急ブレーキ予告（フラッシュ）を出したときはタップ禁止。5回体当たりでクリア。',
    objects: [
      { shape: 'rect', role: '自バイク（横移動）', note: '' },
      { shape: 'rect', role: '敵バイク（並走・急ブレーキ予告あり）', note: '' },
      { shape: 'rect', role: '並列インジケーター（ゾーン表示）', note: '' },
    ],
    counters: [
      { id: 'rams', name: '体当たり成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '並列ゾーン内でタップ5回（急ブレーキ中以外）',
    failTrigger: '急ブレーキ中タップ3回で失敗',
  },
  {
    id: 'arcade-162',
    title: '武田信玄',
    brand: 'ジャレコ',
    year: 1988,
    duration: 20,
    difficulty: 'hard',
    concept: '一騎打ち。信玄と敵将の両方に「気力ゲージ」がある。激しい攻防で互いの気力が波打つ——相手の気力が最低点に落ちた瞬間だけ防御が崩れる。気力ゲージを見てタップし、低点の瞬間に渾身の一太刀。高い時に攻撃すると弾かれて逆に気力を失う。3回決定打でクリア。',
    objects: [
      { shape: 'face', role: '武田信玄（左側）', note: '' },
      { shape: 'face', role: '敵将（右側）', note: '' },
      { shape: 'rect', role: '敵気力ゲージ（波打つ）', note: '最低点でタップが有効' },
    ],
    counters: [
      { id: 'decisive', name: '決定打数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '敵気力最低点でタップ3回',
    failTrigger: '気力高い時に攻撃3回で失敗',
  },
] as const;
