/**
 * ideas/arcade-2025q1.ts
 * Arcade Archives 2025年1〜3月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2025q1Ideas = [
  {
    id: 'arcade-341',
    title: 'キャッスル・オブ・ドラゴン',
    brand: 'アテナ',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: '城の扉を塞ぐ複数の「留め金」が順番に外れていく。全ての留め金が外れた瞬間（全て赤く点灯した瞬間）にタップして体当たりすると扉を破れる——留め金が1つでも残っている間は弾かれてしまう。全留め金が外れるのは2秒に1回しかない。3回扉突破でクリア。',
    objects: [
      { shape: 'rect', role: '城の扉（留め金付き）', note: '全留め金外れで赤く光る' },
      { shape: 'circle', role: '留め金×複数（順番に外れる）', note: '' },
      { shape: 'face', role: '騎士（中央）', note: '' },
    ],
    counters: [
      { id: 'breaks', name: '扉突破数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '全留め金が外れた瞬間タップ3回',
    failTrigger: '留め金残りの状態でタップ3回で失敗',
  },
  {
    id: 'arcade-342',
    title: 'VS.ファミリーテニス',
    brand: 'ナムコ',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '相手の高いロブが山なりに飛んでくる。ボールが最高点（頂点）に達した瞬間にタップして強烈なスマッシュを叩き込む——頂点より早いと空振り、頂点より遅いと弱いボレーになって返される。頂点は0.3秒しか続かない。5回スマッシュ成功でクリア。',
    objects: [
      { shape: 'circle', role: 'テニスボール（山なり飛行）', note: '頂点で光る' },
      { shape: 'face', role: '自選手（中央）', note: '' },
      { shape: 'face', role: '相手選手（奥）', note: '' },
    ],
    counters: [
      { id: 'smashes', name: 'スマッシュ数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'ボール頂点の瞬間タップ5回',
    failTrigger: '頂点外タップ3回で失敗',
  },
  {
    id: 'arcade-343',
    title: 'エスケープキッズ',
    brand: 'KONAMI',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: '看守が見張り台の上で左右を交互に見ている。看守の視線が「右向き」に切り替わった瞬間だけ、左側の通路が死角になって子供が走り抜けられる——切り替わった瞬間にタップして子供を走らせる。左向きの間に走ると発見されてしまう。5回脱出でクリア。',
    objects: [
      { shape: 'face', role: '看守（左右を交互に見る）', note: '右向きに光る' },
      { shape: 'face', role: '子供たち（左通路待機）', note: '' },
      { shape: 'rect', role: '左通路（死角ゾーン）', note: '' },
    ],
    counters: [
      { id: 'escapes', name: '脱出数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '看守が右向きに切り替わった瞬間タップ5回',
    failTrigger: '左向き中タップ3回で失敗',
  },
  {
    id: 'arcade-344',
    title: 'ファイナルスターフォース',
    brand: 'テクモ',
    year: 1992,
    duration: 20,
    difficulty: 'hard',
    concept: '3機合体フォームの弱点コアは機体の中心にある。コアは装甲に守られているが、合体フォームが特定の姿勢角になった瞬間（コアが正面照準に入った瞬間）だけ無防備になって光る——光っている0.3秒以外では弾が装甲に弾かれる。3回コア撃破でクリア。',
    objects: [
      { shape: 'star', role: '弱点コア（装甲の中）', note: '正面一致の瞬間に光る' },
      { shape: 'rect', role: '合体フォーム（姿勢角が変わる）', note: '' },
      { shape: 'triangle', role: '自機（下部）', note: '' },
    ],
    counters: [
      { id: 'cores', name: 'コア撃破数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'コアが正面に来た瞬間タップ3回',
    failTrigger: '装甲外を撃って3回で失敗',
  },
  {
    id: 'arcade-345',
    title: 'サンダーフォックス',
    brand: 'タイトー',
    year: 1990,
    duration: 20,
    difficulty: 'normal',
    concept: 'ヘリコプターが上下に揺れながら飛行している。下部のロープの先端が地上のターゲットに最接近した瞬間（ロープ先端の最低点）にタップして降下——ロープが上昇している間は地上に届かない。最低点の0.3秒だけがタイミングの窓。5回降下でクリア。',
    objects: [
      { shape: 'rect', role: 'ヘリコプター（上下に揺れる）', note: '' },
      { shape: 'ellipse', role: 'ロープ（先端が上下する）', note: '最低点で光る' },
      { shape: 'star', role: 'ターゲットポイント（地上）', note: '' },
    ],
    counters: [
      { id: 'descents', name: '降下数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'ロープ先端最低点の瞬間タップ5回',
    failTrigger: 'ロープ上昇中タップ3回で失敗',
  },
  {
    id: 'arcade-346',
    title: 'メルヘンメイズ',
    brand: 'ナムコ',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '不思議な国の迷宮の床タイルが周期的に「落とし穴タイル」に変わる。タイルが変色し始める瞬間（安全色から危険色への変色が始まった刹那）にタップして飛び越えジャンプ——すでに変色した後を踏むと落ちる。変色前は踏んでも安全だが跳躍準備が間に合わない。5回飛び越えでクリア。',
    objects: [
      { shape: 'rect', role: '床タイル（変色する）', note: '変色開始の瞬間に点滅' },
      { shape: 'face', role: 'アリス（中央）', note: '' },
    ],
    counters: [
      { id: 'jumps', name: '飛び越え数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'タイル変色開始の瞬間タップ5回',
    failTrigger: '変色後に踏む3回で失敗',
  },
  {
    id: 'arcade-347',
    title: 'にゃんにゃんパニック',
    brand: 'KONAMI',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '爆弾の導火線が燃えていてカウントダウンが進む。残り時間が「0.4秒」になった瞬間にタップして爆弾を撤収——残り0.4秒より早く撤収すると次の場所へ届かない。0.4秒より遅いと自分が爆発に巻き込まれる。丁度0.4秒を正確に見極めて5回撤収成功でクリア。',
    objects: [
      { shape: 'bomb', role: '爆弾（導火線が燃える）', note: '残り0.4秒で光る' },
      { shape: 'face', role: '猫キャラ（中央）', note: '' },
    ],
    counters: [
      { id: 'pickups', name: '撤収成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '残り0.4秒の瞬間タップ5回',
    failTrigger: '早すぎ・遅すぎ3回で失敗',
  },
  {
    id: 'arcade-348',
    title: 'オセロ',
    brand: 'サクセス',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: 'オセロの対局で相手が手を打った直後、盤面上の「最多ひっくり返し手（最善手）」が0.5秒だけ光って表示される。その光っている間にタップして確定——光を見逃すと自動でランダムな手が打たれてしまう。5回最多ひっくり返し手確定でクリア。',
    objects: [
      { shape: 'rect', role: 'オセロ盤', note: '' },
      { shape: 'circle', role: '最善手マーカー（0.5秒光る）', note: '最多ひっくり返し位置' },
      { shape: 'circle', role: '石（白・黒）', note: '' },
    ],
    counters: [
      { id: 'best', name: '最善手確定数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '最善手マーカーが光っている間タップ5回',
    failTrigger: 'マーカー消灯後タップ3回で失敗',
  },
  {
    id: 'arcade-349',
    title: 'デッドコネクション',
    brand: 'タイトー',
    year: 1992,
    duration: 20,
    difficulty: 'normal',
    concept: 'マフィアが複数の路地から挟み撃ちに来る。各路地の敵が中央の「交差点」に集まった瞬間——3方向以上の敵が交差点に重なった瞬間にタップして全方位ショット発動。交差前後では敵が分散しているので1〜2人しか当たらない。3回全方位ショットでクリア。',
    objects: [
      { shape: 'face', role: 'マフィア×複数（各路地から）', note: '交差点集結時に光る' },
      { shape: 'star', role: '交差点（中央）', note: '' },
      { shape: 'face', role: '刑事（中央）', note: '' },
    ],
    counters: [
      { id: 'sweeps', name: '全方位ショット数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3方向以上が交差点集結の瞬間タップ3回',
    failTrigger: '分散状態でタップ3回で失敗',
  },
  {
    id: 'arcade-350',
    title: 'VS. バベルの塔',
    brand: 'ナムコ',
    year: 1986,
    duration: 20,
    difficulty: 'hard',
    concept: '押したブロックが壁に向かってスライドしていく。ブロックが壁にぶつかる「0.3秒前」にタップすると直角に方向を変えて別の穴を塞ぐことができる——ぶつかってから方向を変えようとすると手遅れ。0.3秒前のタイミングにタップして5回方向転換成功でクリア。',
    objects: [
      { shape: 'rect', role: 'ブロック（スライド中）', note: 'ぶつかる0.3秒前に点滅' },
      { shape: 'rect', role: '壁（ブロックが向かう先）', note: '' },
      { shape: 'rect', role: '穴（塞ぎたい場所）', note: '' },
    ],
    counters: [
      { id: 'redirects', name: '方向転換成功数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'ぶつかる0.3秒前にタップ5回',
    failTrigger: 'ぶつかった後タップ3回で失敗',
  },
  {
    id: 'arcade-351',
    title: 'ジュノファースト',
    brand: 'KONAMI',
    year: 1983,
    duration: 20,
    difficulty: 'hard',
    concept: 'ジュノファーストの機体は回転しながら飛行する。回転する砲口が「敵の方向（一直線上）」と一致した瞬間にタップして発射——回転中に正確な方向を狙い撃つ。砲口がズレた状態で撃つと弾が外れる。5回方向一致射撃でクリア。',
    objects: [
      { shape: 'triangle', role: 'ジュノファースト（回転飛行）', note: '砲口が敵方向に来た時に光る' },
      { shape: 'face', role: '敵機（前方）', note: '' },
    ],
    counters: [
      { id: 'hits', name: '方向一致射撃数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '砲口が敵方向に一致した瞬間タップ5回',
    failTrigger: '砲口ズレで発射3回で失敗',
  },
  {
    id: 'arcade-352',
    title: '戦球',
    brand: 'セイブ開発',
    year: 1995,
    duration: 20,
    difficulty: 'hard',
    concept: '相手の鉄球が飛んでくる。2つの鉄球が最接近（ぶつかる直前0.2秒）した瞬間にタップして自球を高速回転させると打ち返しスピンショットになる——タイミングが遅れると回転が間に合わず単純な弾き返しになる。5回スピンショットでクリア。',
    objects: [
      { shape: 'circle', role: '相手の鉄球（飛んでくる）', note: '最接近0.2秒前に光る' },
      { shape: 'circle', role: '自分の鉄球（待機）', note: '' },
    ],
    counters: [
      { id: 'spins', name: 'スピンショット数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '最接近0.2秒の瞬間タップ5回',
    failTrigger: 'タイミングズレで弾き返し3回で失敗',
  },
  {
    id: 'arcade-353',
    title: '陸海空 最前線',
    brand: 'タイトー',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: '陸・海・空の3部隊が同時に最前線に向けて進撃している。3部隊の先頭が横一列の同じ縦ライン上に揃った瞬間——3部隊が同時に一直線に並んだ瞬間にタップして一斉砲撃。1〜2部隊だけでは各個撃破されてしまう。3回一斉砲撃でクリア。',
    objects: [
      { shape: 'rect', role: '陸部隊（左から）', note: '' },
      { shape: 'triangle', role: '海部隊（下から）', note: '' },
      { shape: 'triangle', role: '空部隊（上から）', note: '3部隊揃いで光る' },
    ],
    counters: [
      { id: 'volleys', name: '一斉砲撃数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3部隊が縦ライン上に揃った瞬間タップ3回',
    failTrigger: '2部隊以下で砲撃3回で失敗',
  },
] as const;
