/**
 * ideas/arcade-2019a.ts
 * Arcade Archives 2019年配信タイトル（前半）— Swizzleゲームネタ帳
 */

export const arcade2019aIdeas = [
  {
    id: 'arcade-072',
    title: 'アイスクライマー',
    brand: '任天堂',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: '氷のブロックの厚さが1〜3段階で表示される。薄い氷は1タップ、普通は2タップ、厚い氷は3タップで割れる。余分にタップすると上から氷塊が落ちてきて失敗。ブロックの厚さを読んでぴったりの回数だけ叩け。5ブロック突破でクリア。',
    objects: [
      { shape: 'rect', role: '氷ブロック（厚さ1〜3で色が変わる）', note: '薄=水色、普通=青、厚=紺' },
      { shape: 'face', role: 'ポポ（下段固定）', note: '' },
      { shape: 'diamond', role: '氷塊（過剰タップで落下）', note: '' },
    ],
    counters: [
      { id: 'broken', name: '突破ブロック数', target: 5, note: '5ブロックでクリア' },
    ],
    winTrigger: 'counter broken >= 5',
    failTrigger: '氷塊に当たったら失敗',
  },
  {
    id: 'arcade-073',
    title: '怒 -IKARI-',
    brand: 'SNK',
    year: 1986,
    duration: 20,
    difficulty: 'hard',
    concept: 'ヘリコプターが一定速度で斜め移動している。ロケット弾には飛行時間がある——今いる場所ではなく、弾が届く先の位置を狙え。5つの射角候補が扇状に表示され、ヘリが到達する予測位置と重なる角度を1つ選んでタップ。3機撃墜でクリア。',
    objects: [
      { shape: 'triangle', role: 'ヘリコプター（斜め移動）', note: '' },
      { shape: 'diamond', role: 'ロケット弾候補×5（扇状）', note: '選択でハイライト' },
      { shape: 'circle', role: '予測着弾マーカー（正解位置）', note: '正解のみ光る' },
    ],
    counters: [
      { id: 'shot', name: '撃墜数', target: 3, note: '3機でクリア' },
    ],
    winTrigger: 'counter shot >= 3',
    failTrigger: '外れ選択3回で失敗',
  },
  {
    id: 'arcade-074',
    title: 'ドンキーコング3',
    brand: '任天堂',
    year: 1983,
    duration: 20,
    difficulty: 'hard',
    concept: 'スタンリーが殺虫剤を噴霧してDKを上に押し上げながら、同時に左右から虫が侵入してくる。虫はスタンリーと同じ高さに来たときだけタップで退治できる。DKへの噴霧は自動だが、虫の退治は手動タップ。虫を見逃すと花が食べられる。5匹退治でクリア。',
    objects: [
      { shape: 'face', role: 'スタンリー（上下に移動）', note: '' },
      { shape: 'face', role: 'ドンキーコング（上から降下）', note: '噴霧で自動的に押し返す' },
      { shape: 'face', role: '虫×複数（左右から侵入）', note: 'スタンリーと同じ高さでタップ可' },
      { shape: 'circle', role: '花（画面下部）', note: '虫に食べられたら失敗' },
    ],
    counters: [
      { id: 'bugs', name: '退治した虫の数', target: 5, note: '5匹でクリア' },
    ],
    winTrigger: 'counter bugs >= 5',
    failTrigger: '花が3つ食べられたら失敗',
  },
  {
    id: 'arcade-075',
    title: 'タイムパイロット',
    brand: 'KONAMI',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: '自機が8方向のいずれかを向いている。敵機が画面外から一定方向へ飛来する。敵の来る方向を矢印が示し、自機をその方向に向けた状態で0.5秒以内にタップして撃墜。方向が合っていないと弾が届かない。5機撃墜でクリア。',
    objects: [
      { shape: 'triangle', role: '自機（8方向に回転）', note: '' },
      { shape: 'triangle', role: '敵機（画面外から飛来）', note: '' },
      { shape: 'diamond', role: '方向矢印インジケーター', note: '敵の来る方向を示す' },
    ],
    counters: [
      { id: 'downed', name: '撃墜数', target: 5, note: '5機でクリア' },
    ],
    winTrigger: 'counter downed >= 5',
    failTrigger: '方向ミスタップ3回で失敗',
  },
  {
    id: 'arcade-076',
    title: 'サイコソルジャー',
    brand: 'SNK',
    year: 1987,
    duration: 20,
    difficulty: 'hard',
    concept: 'アテナの念力ゲージがゆっくり上昇する。75%で「PSYゾーン」、100%で「オーバーロード」。75%ゾーンに入った瞬間に指を離すと最大威力の念力攻撃が炸裂。100%に達すると精神崩壊で即失敗。3回成功でクリア。',
    objects: [
      { shape: 'rect', role: '念力ゲージ（上昇）', note: '75%でゾーン表示、100%で爆発' },
      { shape: 'face', role: 'アテナ（左端）', note: '' },
      { shape: 'face', role: '敵（右側）', note: '' },
    ],
    counters: [
      { id: 'psy', name: 'PSY攻撃成功数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: 'ゲージ75%ゾーンでリリース3回',
    failTrigger: 'ゲージ100%到達で即失敗',
  },
  {
    id: 'arcade-077',
    title: '忍者龍剣伝',
    brand: 'テクモ',
    year: 1988,
    duration: 20,
    difficulty: 'hard',
    concept: '壁が交互に左右に並んでいる。各壁には安全な足場とトゲのある足場が混在している。リュウが壁を蹴って反対の壁へ飛ぶ。着地点として候補が3か所表示され、トゲのない安全な足場だけをタップして上へ上へと登れ。トゲに触れたら即失敗。',
    objects: [
      { shape: 'face', role: 'リュウ・ハヤブサ（壁に張り付き）', note: '' },
      { shape: 'rect', role: '壁（左右交互）', note: '' },
      { shape: 'star', role: 'トゲ（危険な足場）', note: '' },
      { shape: 'rect', role: '安全足場（3候補）', note: 'タップで着地' },
    ],
    counters: [
      { id: 'jumps', name: '壁ジャンプ成功数', target: 6, note: '6回でクリア' },
    ],
    winTrigger: 'counter jumps >= 6',
    failTrigger: 'トゲに着地で即失敗',
  },
  {
    id: 'arcade-078',
    title: 'イメージファイト',
    brand: 'アイレム',
    year: 1988,
    duration: 25,
    difficulty: 'hard',
    concept: '自機の4つの装備スロットが空になっている。画面上部に「目標配置図」が表示され、前後左右のどこにポッドを付けるかが指定される。落下してくるポッドを目標図通りの位置にドラッグして配置。4スロット全て合致したら発進。',
    objects: [
      { shape: 'triangle', role: '自機（中央）', note: '4スロット表示' },
      { shape: 'circle', role: 'ポッド×4（落下）', note: 'ドラッグで配置' },
      { shape: 'rect', role: '目標配置図（上部表示）', note: '正解パターン' },
    ],
    counters: [
      { id: 'launches', name: '発進成功数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '4スロット全て目標図通りに配置して3回発進',
    failTrigger: '誤配置のまま30秒経過で失敗',
  },
  {
    id: 'arcade-079',
    title: 'アルペンスキー',
    brand: 'データイースト',
    year: 1981,
    duration: 20,
    difficulty: 'normal',
    concept: 'スキーヤーがコースを滑り降りる。旗門が2色で表示される——青旗は左側を通過、赤旗は右側を通過。旗門が迫ってくる中、正しい方向をタップして通過せよ。5門連続正解でクリア。色を読み間違えたら失敗。',
    objects: [
      { shape: 'triangle', role: 'スキーヤー（下向き移動）', note: '' },
      { shape: 'diamond', role: '旗門（青または赤）', note: '青=左、赤=右' },
      { shape: 'button', role: '左ボタン', note: '' },
      { shape: 'button', role: '右ボタン', note: '' },
    ],
    counters: [
      { id: 'gates', name: '通過門数', target: 5, note: '5門連続でクリア' },
    ],
    winTrigger: 'counter gates >= 5',
    failTrigger: '色を間違えた通過3回で失敗',
  },
  {
    id: 'arcade-080',
    title: 'プーヤン',
    brand: 'KONAMI',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: 'オオカミがロープを伝って降りてくる。矢は放物線を描いて飛ぶ。オオカミではなく、ロープそのものを切るのが目的。矢の弧軌道がロープと交差する瞬間にタップして射ち、ロープを切断してオオカミを落とせ。5匹撃退でクリア。',
    objects: [
      { shape: 'face', role: 'オオカミ（ロープを伝って降下）', note: '' },
      { shape: 'rect', role: 'ロープ（縦線）', note: '矢が当たると切断' },
      { shape: 'diamond', role: '矢（放物線軌道）', note: '' },
      { shape: 'button', role: '射撃ボタン', note: '' },
    ],
    counters: [
      { id: 'cut', name: 'ロープ切断数', target: 5, note: '5本でクリア' },
    ],
    winTrigger: 'counter cut >= 5',
    failTrigger: 'オオカミが地面に到達3回で失敗',
  },
  {
    id: 'arcade-081',
    title: 'ワイルドウエスタン',
    brand: 'データイースト',
    year: 1982,
    duration: 20,
    difficulty: 'hard',
    concept: '列車に乗り込もうとする無法者が、乗り込む直前に一瞬だけ前傾姿勢になる。その0.5秒の隙にだけ弾が当たる。立ち姿勢や移動中は当たらない。前傾のタイミングを見極めてタップ。3人倒すとクリア。',
    objects: [
      { shape: 'face', role: '無法者（歩行→前傾→乗り込み）', note: '前傾中は赤くハイライト' },
      { shape: 'rect', role: '列車（右端）', note: '' },
      { shape: 'button', role: '射撃ボタン', note: '' },
    ],
    counters: [
      { id: 'stopped', name: '阻止数', target: 3, note: '3人でクリア' },
    ],
    winTrigger: 'counter stopped >= 3',
    failTrigger: '立ち姿勢でのタップ3回で失敗',
  },
  {
    id: 'arcade-082',
    title: 'クルクルランド',
    brand: '任天堂',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: 'グルピーが渦巻き状の水流に沿って自動的に回っている。ポールに近づいたときにタップしてポールをつかみ、つかんだ勢いで方向を変えて次のポールへ向かう。タイミングが合わないとポールをつかみ損ねて溺れる。5本のポールを渡り切ればクリア。',
    objects: [
      { shape: 'face', role: 'グルピー（渦巻き水流上を移動）', note: '' },
      { shape: 'circle', role: 'ポール×5（固定）', note: 'タップでつかむ' },
      { shape: 'circle', role: '水流（渦巻き）', note: '' },
    ],
    counters: [
      { id: 'poles', name: 'つかんだポール数', target: 5, note: '5本でクリア' },
    ],
    winTrigger: 'counter poles >= 5',
    failTrigger: 'つかみ損ね3回で失敗',
  },
  {
    id: 'arcade-083',
    title: '最後の忍道',
    brand: 'アイレム',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '崖の壁面に手がかりが点在している。安定した手がかりは静止しているが、不安定な手がかりはわずかに揺れている。上へ登るために3つの候補から選ぶ。揺れていない安定した手がかりだけをタップして登れ。揺れている手がかりを掴むと滑落する。',
    objects: [
      { shape: 'rect', role: '安定した手がかり（静止）', note: '' },
      { shape: 'rect', role: '不安定な手がかり（微振動）', note: '揺れアニメ' },
      { shape: 'face', role: '忍者（壁に張り付き）', note: '' },
    ],
    counters: [
      { id: 'climbed', name: '登頂数', target: 5, note: '5段でクリア' },
    ],
    winTrigger: 'counter climbed >= 5',
    failTrigger: '不安定な手がかりを掴む3回で失敗',
  },
  {
    id: 'arcade-084',
    title: 'ロードファイター',
    brand: 'KONAMI',
    year: 1984,
    duration: 20,
    difficulty: 'hard',
    concept: 'レースカーが3レーン道路を走っている。燃料缶が2つ先のレーンに出現する——今いるレーンから2回の車線変更で到達できる経路を一瞬で計算してタップ。計算が合っていれば缶を取得。5缶取得でクリア。1回の変更では届かないルートも含まれる。',
    objects: [
      { shape: 'triangle', role: '自車（3レーンを走行）', note: '' },
      { shape: 'coin', role: '燃料缶（2先のレーンに出現）', note: '' },
      { shape: 'rect', role: 'レーン×3', note: '' },
    ],
    counters: [
      { id: 'fuel', name: '燃料缶取得数', target: 5, note: '5缶でクリア' },
    ],
    winTrigger: 'counter fuel >= 5',
    failTrigger: '燃料缶を3回見逃したら失敗',
  },
  {
    id: 'arcade-085',
    title: '怒号層圏',
    brand: 'SNK',
    year: 1987,
    duration: 20,
    difficulty: 'hard',
    concept: '2人の兵士が暗闇の中を移動している。サーチライトが定期的に走査する。サーチライトが2人の上を通過する直前に両方を建物の影に隠さなければならない。2人同時に影に入った状態で0.5秒以内にタップして息を潜めよ。3回やり過ごせばクリア。',
    objects: [
      { shape: 'face', role: '兵士×2（移動中）', note: '' },
      { shape: 'rect', role: '建物の影（安全ゾーン）', note: '' },
      { shape: 'rect', role: 'サーチライト（走査）', note: '当たったら失敗' },
    ],
    counters: [
      { id: 'hidden', name: '潜伏成功数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '2人とも影の中でタップ3回',
    failTrigger: 'サーチライトが兵士に当たったら失敗',
  },
] as const;
