/**
 * ideas/arcade-2022q2.ts
 * Arcade Archives 2022年4〜6月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2022q2Ideas = [
  {
    id: 'arcade-202',
    title: 'パックランド',
    brand: 'ナムコ',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: 'パックマンが横スクロールの世界を走っている。トランポリンで高く跳ねた頂点から、高台の上にあるパワーエサへ向かって降りる——頂点の高さと高台の高さが一致した瞬間にタップして水平移動に切り替えて着地。高さが合わないと降りそびれる。5回正確着地でクリア。',
    objects: [
      { shape: 'face', role: 'パックマン（トランポリンで高く跳ねる）', note: '頂点で光る' },
      { shape: 'star', role: 'パワーエサ（高台の上）', note: '' },
      { shape: 'rect', role: 'トランポリン', note: '' },
      { shape: 'rect', role: '高台（様々な高さ）', note: '' },
    ],
    counters: [
      { id: 'lands', name: '高台着地数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '頂点高さ=高台高さの瞬間タップ5回',
    failTrigger: '高さズレ着地3回で失敗',
  },
  {
    id: 'arcade-203',
    title: 'ワルキューレの伝説',
    brand: 'ナムコ',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: 'ワルキューレが呪文を唱えるにはルーンの欠片を3つ集める必要がある。欠片が3種類（A・B・C）それぞれのシンボルを周期的に切り替えながら浮遊している。必要な3種のシンボルが各欠片に揃った瞬間にタップして全て収集。バラバラのシンボル時に取ると呪文が不完全になる。3呪文でクリア。',
    objects: [
      { shape: 'star', role: 'ルーン欠片×3（シンボル切り替え）', note: 'A・B・C周期表示' },
      { shape: 'face', role: 'ワルキューレ（下部）', note: '' },
      { shape: 'rect', role: '必要シンボル表示', note: '3種全揃いで光る' },
    ],
    counters: [
      { id: 'spells', name: '完全呪文数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3種全シンボルが揃った瞬間タップ3回',
    failTrigger: '不完全な状態での収集3回で失敗',
  },
  {
    id: 'arcade-204',
    title: 'ギャプラス',
    brand: 'ナムコ',
    year: 1984,
    duration: 20,
    difficulty: 'normal',
    concept: '敵機が自機の真上に来た瞬間だけ牽引ビームが届く。牽引ビームで捕獲すると敵機が自機の仲間になり火力が上がる。しかし捕獲した敵機が被弾すると逃げてしまう。「真上にいる瞬間」を見極めてタップ。タイミングが外れると牽引失敗。3機捕獲でクリア。',
    objects: [
      { shape: 'triangle', role: '自機（下部）', note: '' },
      { shape: 'face', role: '敵機（上部を横移動）', note: '真上で光る' },
      { shape: 'rect', role: '牽引ビーム（真上にのみ有効）', note: '' },
    ],
    counters: [
      { id: 'captured', name: '捕獲数', target: 3, note: '3機でクリア' },
    ],
    winTrigger: '敵機が真上の瞬間タップ3回',
    failTrigger: '真上以外でビーム3回で失敗',
  },
  {
    id: 'arcade-205',
    title: '妖怪道中記',
    brand: 'ナムコ',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '太郎が石つぶてを放物線で投げる。鬼が床の穴の下に隠れている——直射では当たらないが、石を高く放り投げて真上から落とすとちょうど穴に入って命中する。石の弧の頂点が穴の真上に来る放物線になったときにタップ。5体撃退でクリア。',
    objects: [
      { shape: 'face', role: '太郎（左端）', note: '' },
      { shape: 'circle', role: '石つぶて（放物線）', note: '' },
      { shape: 'diamond', role: '弧の軌道（穴の真上で光る）', note: '' },
      { shape: 'face', role: '鬼（穴の下）', note: '' },
    ],
    counters: [
      { id: 'hit', name: '穴落とし命中数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '石の頂点が穴の真上の瞬間タップ5回',
    failTrigger: '軌道外れ3回で失敗',
  },
  {
    id: 'arcade-206',
    title: 'ファイティングホーク',
    brand: 'タイトー',
    year: 1988,
    duration: 20,
    difficulty: 'hard',
    concept: 'ボスが弾幕を撃ってくる。弾幕の中には必ず1本の「安全な通路」がある。弾が出揃うまで0.7秒——弾幕が完全に展開した直後の0.5秒以内に通路の位置（上・中・下）をタップして突入。先に動くと途中の弾に当たる。3回の通路突入でクリア。',
    objects: [
      { shape: 'triangle', role: 'ファイティングホーク（中央）', note: '' },
      { shape: 'diamond', role: '弾幕（展開中）', note: '安全通路1本だけ空き' },
      { shape: 'button', role: '上方向ボタン', note: '' },
      { shape: 'button', role: '中方向ボタン', note: '' },
      { shape: 'button', role: '下方向ボタン', note: '' },
    ],
    counters: [
      { id: 'passages', name: '安全通路突入数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '弾幕展開完了後0.5秒以内に正しい通路タップ3回',
    failTrigger: '展開前に動いて被弾3回で失敗',
  },
  {
    id: 'arcade-207',
    title: 'プロテニス ワールドコート',
    brand: 'ナムコ',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '相手のサーブを読んでリターンエースを決める。サーバーの体の回転方向が打球方向を教えてくれる——左回転は右コートへ、右回転は左コートへ飛ぶ。回転を読んで逆コートにポジショニングし、ボールが来る前にタップして構えを取れ。3本のリターンエースでクリア。',
    objects: [
      { shape: 'face', role: '相手サーバー（回転方向表示）', note: '左回転=右へ、右回転=左へ' },
      { shape: 'circle', role: 'テニスボール（サーブ）', note: '' },
      { shape: 'button', role: '左コートポジションボタン', note: '' },
      { shape: 'button', role: '右コートポジションボタン', note: '' },
    ],
    counters: [
      { id: 'aces', name: 'リターンエース数', target: 3, note: '3本でクリア' },
    ],
    winTrigger: '回転方向と逆コートをタップ3回',
    failTrigger: '方向ミスリターン3回で失敗',
  },
  {
    id: 'arcade-208',
    title: 'トリオ・ザ・パンチ',
    brand: 'データイースト',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: '3つのランダムアイコンがスロットのように高速回転する。3つ全てが同じアイコンで揃った瞬間にタップしてコンボ攻撃を発動——違うアイコンの時にタップすると逆にデメリットが発生する。揃う瞬間を見逃さず5回連続コンボ発動でクリア。',
    objects: [
      { shape: 'rect', role: 'アイコンスロット×3（高速回転）', note: '揃うと光る' },
      { shape: 'button', role: 'コンボ発動ボタン', note: '' },
    ],
    counters: [
      { id: 'combos', name: 'コンボ発動数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '3つ全て揃いの瞬間タップ5回',
    failTrigger: '不一致でタップ3回で失敗',
  },
  {
    id: 'arcade-209',
    title: 'フリップル',
    brand: 'タイトー',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: '縦に積み上がったブロックが1個ずつ順番に「自分のブロックの色」に変わりながら降りてくる。持っているブロックと積み上がりの最上段が同じ色になった瞬間にタップして投げつけると消滅する。色が変わる前の一瞬しかチャンスはない。5回消滅でクリア。',
    objects: [
      { shape: 'rect', role: '積み上がりブロック（最上段が色変化）', note: '' },
      { shape: 'rect', role: '手持ちブロック（色表示）', note: 'タップで投げる' },
    ],
    counters: [
      { id: 'cleared', name: '消滅数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '手持ちと最上段が同色の瞬間タップ5回',
    failTrigger: '色違い投擲3回で失敗',
  },
  {
    id: 'arcade-210',
    title: 'ドルアーガの塔',
    brand: 'ナムコ',
    year: 1984,
    duration: 25,
    difficulty: 'hard',
    concept: 'ギルが各フロアでスライムと戦っている。スライムは3×3のグリッドを動き回る。ギルが斜め隣ではなく「隣接正方向」（上下左右）に来た瞬間だけ剣が当たる。斜め接触では当たらない——正方向に隣接した瞬間をタップして攻撃。5体撃破でクリア。',
    objects: [
      { shape: 'face', role: 'ギル（グリッド上）', note: '' },
      { shape: 'face', role: 'スライム（グリッド上・移動）', note: '正方向隣接時に光る' },
      { shape: 'rect', role: '3×3グリッド', note: '' },
    ],
    counters: [
      { id: 'hits', name: '撃破数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '正方向隣接の瞬間タップ5回',
    failTrigger: '斜め隣接タップ3回で失敗',
  },
  {
    id: 'arcade-211',
    title: 'モトス',
    brand: 'ナムコ',
    year: 1985,
    duration: 20,
    difficulty: 'normal',
    concept: '六角形のプラットフォーム上でモトスが敵ビークルを体当たりで端から突き落とす。突き落とすには端に対して正面（法線方向）から体当たりしないと効かない——斜め方向に押すと敵が端ではなく別の方向にずれる。敵と端が一直線に並んだ瞬間にタップ。5体落下でクリア。',
    objects: [
      { shape: 'circle', role: 'モトス（中央）', note: '' },
      { shape: 'rect', role: '敵ビークル（移動）', note: '端と一直線時に光る' },
      { shape: 'ellipse', role: '六角形プラットフォーム（端が崖）', note: '' },
    ],
    counters: [
      { id: 'fallen', name: '落下させた数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '敵と端が一直線の瞬間タップ5回',
    failTrigger: 'ズレ体当たりで端に逃げられ3回で失敗',
  },
  {
    id: 'arcade-212',
    title: 'スペースシーカー',
    brand: 'タイトー',
    year: 1981,
    duration: 20,
    difficulty: 'normal',
    concept: '宇宙空間を漂う隕石が盾として使える。敵の射撃ラインが飛んでくるとき、隕石の陰に隠れると弾が相殺される。隕石は自動で流れているので、敵弾が来る軌道上に隕石が重なった瞬間にタップして後ろに回り込め。5弾相殺でクリア。',
    objects: [
      { shape: 'triangle', role: '自機（中央）', note: '' },
      { shape: 'circle', role: '隕石（流れている）', note: '弾が重なると光る' },
      { shape: 'diamond', role: '敵弾（飛来）', note: '' },
    ],
    counters: [
      { id: 'blocked', name: '弾相殺数', target: 5, note: '5弾でクリア' },
    ],
    winTrigger: '隕石と敵弾が重なる瞬間タップ5回',
    failTrigger: '隕石なしで被弾3回で失敗',
  },
  {
    id: 'arcade-213',
    title: 'サンダーセプター',
    brand: 'ナムコ',
    year: 1986,
    duration: 20,
    difficulty: 'hard',
    concept: 'サンダーセプターが3Dトンネルを飛行している。トンネル壁面を電撃が走り、3本の電撃が同時に船体の左・右・上から包み込む「トリプル放電」の瞬間に吸収してサンダーキャノンが最大充填される。3方向同時包囲の瞬間にタップして吸収。3回最大充填でクリア。',
    objects: [
      { shape: 'triangle', role: 'サンダーセプター（中央）', note: '' },
      { shape: 'rect', role: 'トンネル壁（電撃が走る）', note: '3方向同時で光る' },
      { shape: 'rect', role: 'サンダーキャノン充填ゲージ', note: '3方向吸収でMAX' },
    ],
    counters: [
      { id: 'charged', name: '最大充填数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3方向同時電撃の瞬間タップ3回',
    failTrigger: '2方向以下での吸収3回で失敗',
  },
] as const;
