/**
 * ideas/arcade-2024q1.ts
 * Arcade Archives 2024年1〜3月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2024q1Ideas = [
  {
    id: 'arcade-289',
    title: 'マイティガイ',
    brand: 'ニチブツ',
    year: 1986,
    duration: 20,
    difficulty: 'normal',
    concept: '障害物の列が前方に迫っている。列には一か所だけ「通過隙間」があり、0.6秒おきにランダムで左・中・右に移動する。隙間が中央（自機の直進ライン）に来た瞬間にタップして突進。隙間が左右にずれている時にタップすると激突する。5回突破でクリア。',
    objects: [
      { shape: 'rect', role: '障害物の列（横に並ぶ）', note: '隙間が左・中・右で移動' },
      { shape: 'triangle', role: 'マイティガイ自機（下部）', note: '' },
    ],
    counters: [
      { id: 'breaks', name: '突破数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '隙間が中央の瞬間タップ5回',
    failTrigger: '隙間がズレた状態でタップ3回で失敗',
  },
  {
    id: 'arcade-290',
    title: 'コズモギャング・ザ・パズル',
    brand: 'ナムコ',
    year: 1992,
    duration: 20,
    difficulty: 'normal',
    concept: 'コズモギャングたちが正方形の4頂点フォーメーションを組もうとしている。1体だけが点滅しながら位置を微調整しており、4体が完全な正方形を形成する瞬間（4か所の光が同時に揃う）にタップして捕獲。ズレた状態では1体しか捕まらない。3回完全捕獲でクリア。',
    objects: [
      { shape: 'face', role: 'コズモギャング×4（頂点に配置）', note: '全員揃った瞬間に光る' },
      { shape: 'rect', role: '捕獲エリア（中央）', note: '' },
    ],
    counters: [
      { id: 'captures', name: '完全捕獲数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '4体正方形フォーメーション完成の瞬間タップ3回',
    failTrigger: 'ズレた状態でタップ3回で失敗',
  },
  {
    id: 'arcade-291',
    title: 'SUPER魂斗羅 エイリアンの逆襲',
    brand: 'KONAMI',
    year: 1988,
    duration: 20,
    difficulty: 'hard',
    concept: 'ボスの巨大コアは装甲の左右にスライドし続けており、装甲の中央に来た瞬間だけ完全に露出して撃てる。コアが端にいる時は装甲バリアが弾を弾く。コアが中央に来た瞬間にタップ——0.4秒だけのウィンドウを逃さずに5回撃破でクリア。',
    objects: [
      { shape: 'circle', role: 'コア（左右スライド）', note: '中央到達時に光る' },
      { shape: 'rect', role: '装甲（左右を覆う）', note: '' },
      { shape: 'face', role: '自機（下部）', note: '' },
    ],
    counters: [
      { id: 'hits', name: 'コア撃破数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'コア中央の瞬間タップ5回',
    failTrigger: '装甲側にタップ3回で失敗',
  },
  {
    id: 'arcade-292',
    title: 'レインボーアイランド',
    brand: 'タイトー',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: '虹の橋を前方に伸ばしてモンスターの真上に架ける。虹は発射後1秒で消え、消えた破片がそのまま落下してモンスターに当たる。モンスターの真上（破片の落下エリア）に虹の先端が届いた瞬間にタップして消去——伸ばし続けると破片がモンスターを越えてしまう。3回撃墜でクリア。',
    objects: [
      { shape: 'rect', role: '虹の橋（前方に伸びる）', note: '先端が敵の真上で光る' },
      { shape: 'face', role: 'モンスター（前方）', note: '' },
      { shape: 'face', role: 'バビー（中央）', note: '' },
    ],
    counters: [
      { id: 'hits', name: '撃墜数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '先端がモンスター真上に達した瞬間タップ3回',
    failTrigger: '先端が通り越してからタップ3回で失敗',
  },
  {
    id: 'arcade-293',
    title: 'シルクワーム',
    brand: 'テクモ',
    year: 1988,
    duration: 20,
    difficulty: 'hard',
    concept: '地上に2種類の機雷が混在している。タイマー型は点滅が次第に速くなり、最速（臨界点）になった瞬間にタップして爆破。センサー型は近づくと光り始め、光が消える一瞬（センサーオフ）にタップして無力化。2種を見分けて各5個処理でクリア。',
    objects: [
      { shape: 'circle', role: 'タイマー型機雷（点滅速度上昇）', note: '最速時に赤く光る' },
      { shape: 'diamond', role: 'センサー型機雷（接近で光る）', note: '消える瞬間に白くなる' },
      { shape: 'rect', role: 'ヘリコプター（上部）', note: '' },
    ],
    counters: [
      { id: 'cleared', name: '機雷処理数', target: 5, note: '5個でクリア' },
    ],
    winTrigger: '各機雷の正しいタイミングでタップ5回',
    failTrigger: 'タイミングを外して3回で失敗',
  },
  {
    id: 'arcade-294',
    title: 'フェイスオフ',
    brand: 'ナムコ',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: 'アイスホッケーのフェイスオフ。審判がパックを真上から落とす——パックが氷面に接触した瞬間（最低点）にタップしてスティックを叩きつける。氷面到達前に振ると空振り、到達後では相手に先取りされる。5回フェイスオフ制覇でクリア。',
    objects: [
      { shape: 'circle', role: 'パック（落下中）', note: '氷面到達時に光る' },
      { shape: 'face', role: '自選手（左）', note: '' },
      { shape: 'face', role: '相手選手（右）', note: '' },
    ],
    counters: [
      { id: 'wins', name: 'フェイスオフ勝利数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'パック氷面接触の瞬間タップ5回',
    failTrigger: '早打ちor遅打ち3回で失敗',
  },
  {
    id: 'arcade-295',
    title: 'マスター オブ ウエポン',
    brand: 'タイトー',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: '敵フォーメーションの中心に「コア」が隠れている。コア周囲の敵数が増えると密集度メーターが上がり、最大値に達した瞬間（全周を敵が囲んだ瞬間）にコアへの貫通弾を発射するとまとめて爆破できる。密集不足では貫通が届かない。3回コア爆破でクリア。',
    objects: [
      { shape: 'star', role: 'コア（中心・隠れている）', note: '周囲が最大密集で露出' },
      { shape: 'face', role: '敵機×複数（コア周囲）', note: '密集ピーク時に光る' },
      { shape: 'triangle', role: '自機（下部）', note: '' },
    ],
    counters: [
      { id: 'cores', name: 'コア爆破数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '密集ピーク時タップ3回',
    failTrigger: '密集不足で発射3回で失敗',
  },
  {
    id: 'arcade-296',
    title: 'ジャングラー',
    brand: 'KONAMI',
    year: 1981,
    duration: 20,
    difficulty: 'normal',
    concept: 'ジャングラーのつるが左右に大きく振れている。右端・左端・中央の3か所に敵が配置されている。つるが敵の真上を通過した瞬間にタップして飛び移り、敵を足で蹴落とす。通過の前後ではつるが届かない。5回蹴落としでクリア。',
    objects: [
      { shape: 'ellipse', role: 'つる（左右に振れる）', note: '敵の真上通過時に光る' },
      { shape: 'face', role: '敵×3（左・中・右）', note: '' },
      { shape: 'face', role: 'ジャングラー（つるにぶら下がる）', note: '' },
    ],
    counters: [
      { id: 'kicks', name: '蹴落とし数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'つるが敵の真上を通過した瞬間タップ5回',
    failTrigger: '位置がズレた状態でタップ3回で失敗',
  },
  {
    id: 'arcade-297',
    title: 'ウォーオブエアロ',
    brand: 'アルュメ',
    year: 1993,
    duration: 20,
    difficulty: 'normal',
    concept: '敵大型機の下部に4基のエンジンが並んでいる。エンジンは順番に一つずつ点灯していき、4基が同時に全点灯する瞬間（約0.5秒）だけ機体中枢への爆撃が有効になる。1〜3基点灯では装甲が耐える。全エンジン同時点灯の瞬間にタップして3機撃墜でクリア。',
    objects: [
      { shape: 'rect', role: '敵大型機（上部）', note: '' },
      { shape: 'circle', role: 'エンジン×4（下部に並ぶ）', note: '全点灯時に白く光る' },
      { shape: 'triangle', role: '自機（下部）', note: '' },
    ],
    counters: [
      { id: 'downs', name: '撃墜数', target: 3, note: '3機でクリア' },
    ],
    winTrigger: '4基全エンジン点灯の瞬間タップ3回',
    failTrigger: '3基以下でタップ3回で失敗',
  },
  {
    id: 'arcade-298',
    title: 'タンクバタリアン',
    brand: 'ナムコ',
    year: 1980,
    duration: 20,
    difficulty: 'normal',
    concept: '複数の経路から迫ってくる敵タンクが1か所の「収束ポイント」に集まる瞬間がある。収束ポイントに3台以上が重なった瞬間に砲撃するとまとめて撃破できる。2台以下の時に撃っても1〜2台しか当たらない。3回3台以上同時撃破でクリア。',
    objects: [
      { shape: 'rect', role: '敵タンク×複数（各経路から）', note: '収束時に光る' },
      { shape: 'star', role: '収束ポイント（地図上）', note: '' },
      { shape: 'rect', role: '自タンク（下部）', note: '' },
    ],
    counters: [
      { id: 'sweeps', name: '3台以上同時撃破数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '収束ポイントに3台以上の瞬間タップ3回',
    failTrigger: '2台以下で撃破3回で失敗',
  },
  {
    id: 'arcade-299',
    title: 'マウサー',
    brand: 'UPL',
    year: 1983,
    duration: 20,
    difficulty: 'normal',
    concept: 'マウサーは縦方向と横方向の弾を同時に発射できる十字射撃が使える。敵が十字路の角から斜めに移動してくる——縦弾と横弾の交差点（十字路の中心）に敵が来た瞬間にタップして発射。縦か横どちらかにズレている時は弾が外れる。5回十字射撃命中でクリア。',
    objects: [
      { shape: 'face', role: '敵（十字路を斜め移動）', note: '交差点通過時に光る' },
      { shape: 'star', role: '十字路の中心（交差点）', note: '' },
      { shape: 'triangle', role: 'マウサー自機（中央）', note: '' },
    ],
    counters: [
      { id: 'hits', name: '十字射撃命中数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '交差点通過の瞬間タップ5回',
    failTrigger: 'ズレた状態でタップ3回で失敗',
  },
  {
    id: 'arcade-300',
    title: 'サプライズアタック',
    brand: 'KONAMI',
    year: 1990,
    duration: 20,
    difficulty: 'normal',
    concept: '敵の検問所の扉が定期的に開閉する。扉が開いている時間のうち、中央3分の1の時間帯だけが「ノーアラームゾーン」（警備センサーの死角）。ノーアラームゾーンの間にタップして侵入——扉が開き始めや閉まり始めの端では警報が鳴る。5回無音侵入でクリア。',
    objects: [
      { shape: 'rect', role: '扉（開閉する）', note: 'ノーアラームゾーンが緑色' },
      { shape: 'face', role: 'ビル（自キャラ）', note: '' },
    ],
    counters: [
      { id: 'entries', name: '無音侵入数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: 'ノーアラームゾーン中タップ5回',
    failTrigger: 'ゾーン外侵入3回で失敗',
  },
  {
    id: 'arcade-301',
    title: 'ヴォルフィード',
    brand: 'タイトー',
    year: 1989,
    duration: 20,
    difficulty: 'hard',
    concept: 'フィールドにライン引きで区域を切り取る。敵が3体以上、まさに自機が引いた「囲いライン」の内側に収まった瞬間にタップしてライン確定——内側の敵全員を一気に消去できる。3体未満の時に確定しても消す意味が薄い。3回3体以上囲い込みでクリア。',
    objects: [
      { shape: 'rect', role: '囲いライン（自機が引く）', note: '3体以上が内側で光る' },
      { shape: 'face', role: '敵×複数（フィールド内）', note: '' },
      { shape: 'triangle', role: 'ヴォルフィード自機', note: '' },
    ],
    counters: [
      { id: 'sweeps', name: '3体以上囲い込み数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '3体以上が内側に入った瞬間タップ3回',
    failTrigger: '2体以下で確定3回で失敗',
  },
] as const;
