/**
 * ideas/arcade-2023q3.ts
 * Arcade Archives 2023年7〜9月配信タイトル — Swizzleゲームネタ帳
 */

export const arcade2023q3Ideas = [
  {
    id: 'arcade-263',
    title: 'ポールポジション',
    brand: 'ナムコ',
    year: 1982,
    duration: 20,
    difficulty: 'normal',
    concept: '予選タイム計測。各コーナーに「アペックス（最速ライン）」マーカーが設置されており、そこを通過すると最短ラインで回れる。コーナーが近づくにつれてアペックスマーカーが画面に見えてくる——ちょうどマーカーの上を通過した瞬間にタップしてステアリングを固定。5コーナーでクリア。',
    objects: [
      { shape: 'triangle', role: 'レーシングカー（前進）', note: '' },
      { shape: 'diamond', role: 'アペックスマーカー（コーナーの最速点）', note: '通過時に光る' },
      { shape: 'rect', role: 'コース', note: '' },
    ],
    counters: [
      { id: 'apex', name: 'アペックス通過数', target: 5, note: '5コーナーでクリア' },
    ],
    winTrigger: 'マーカー通過の瞬間タップ5回',
    failTrigger: 'マーカーを外したコーナー3回で失敗',
  },
  {
    id: 'arcade-264',
    title: '雷牙',
    brand: 'テクモ',
    year: 1991,
    duration: 20,
    difficulty: 'hard',
    concept: '雷牙が鬼神に向かう。光源（松明・月光）・雷牙・鬼神の3点が一直線に並んだときだけ、光が鬼神を貫いて退治できる。3点のうち光源と鬼神は動く——雷牙が適切な位置に来て3点が一直線になった瞬間にタップして光を放て。5体退治でクリア。',
    objects: [
      { shape: 'circle', role: '光源（松明/月・移動）', note: '' },
      { shape: 'face', role: '雷牙（移動可能）', note: '3点一直線で光る' },
      { shape: 'face', role: '鬼神（移動）', note: '' },
    ],
    counters: [
      { id: 'purged', name: '退治数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '3点一直線の瞬間タップ5回',
    failTrigger: '一直線でない状態でタップ3回で失敗',
  },
  {
    id: 'arcade-265',
    title: 'キング&バルーン',
    brand: 'ナムコ',
    year: 1980,
    duration: 20,
    difficulty: 'normal',
    concept: 'エイリアンバルーンが真下に向かって降下し、王様を拉致しようとする。王様は左右にふらふら歩いており、バルーンが王様の真上に来る瞬間にタップして撃墜——王様が動いているため、バルーンと王様が縦に一致した瞬間を捉えよ。5機撃墜でクリア。',
    objects: [
      { shape: 'balloon', role: 'エイリアンバルーン（降下）', note: '' },
      { shape: 'face', role: '王様（下部・左右移動）', note: '真下にバルーンが来ると光る' },
      { shape: 'triangle', role: '自機砲台（下部）', note: '' },
    ],
    counters: [
      { id: 'shot', name: '撃墜数', target: 5, note: '5機でクリア' },
    ],
    winTrigger: 'バルーンと王様が縦一致の瞬間タップ5回',
    failTrigger: '王様が拉致された3回で失敗',
  },
  {
    id: 'arcade-266',
    title: 'ルナーク',
    brand: 'タイトー',
    year: 1990,
    duration: 20,
    difficulty: 'normal',
    concept: '密猟者がフィールド上に仕掛けワナや崖縁の近くにいる。レンジャーが密猟者を近くの「自然の危険物（崖・落石・水流）」の直前まで追い詰め、密猟者が危険物に背を向けた瞬間にタップして突き飛ばせ。前を向いたまま突くと避けられる。5人制圧でクリア。',
    objects: [
      { shape: 'face', role: '密猟者（危険物方向へ逃げる）', note: '背を向けた時に光る' },
      { shape: 'rect', role: '自然の危険物（崖・落石）', note: '' },
      { shape: 'face', role: 'レンジャー（追跡）', note: '' },
    ],
    counters: [
      { id: 'stopped', name: '制圧数', target: 5, note: '5人でクリア' },
    ],
    winTrigger: '密猟者が危険物に背を向けた瞬間タップ5回',
    failTrigger: '前を向いたまま突き飛ばし3回で失敗',
  },
  {
    id: 'arcade-267',
    title: '爆突機銃艇',
    brand: 'ナムコ',
    year: 1988,
    duration: 20,
    difficulty: 'normal',
    concept: '機銃艇が海上と空中の2種類の敵に対応する。魚雷は水中目標に、機銃は空中目標に有効。画面に「空中と水中の敵が同じ縦位置」に来た瞬間、魚雷と機銃を同時発射すれば2体同時撃破できる。どちらか片方だけでは効かない方の敵が残る。3回同時撃破でクリア。',
    objects: [
      { shape: 'triangle', role: '空中敵（上半分）', note: '' },
      { shape: 'rect', role: '水中敵（下半分）', note: '' },
      { shape: 'rect', role: '機銃艇（中央）', note: '' },
      { shape: 'button', role: '同時発射ボタン', note: '' },
    ],
    counters: [
      { id: 'doubles', name: '同時撃破数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '空中と水中が縦一致の瞬間タップ3回',
    failTrigger: '片方しかいない状態で同時発射3回で失敗',
  },
  {
    id: 'arcade-268',
    title: 'マッドシャーク',
    brand: 'アルュメ',
    year: 1993,
    duration: 20,
    difficulty: 'normal',
    concept: 'ヘリコプターが目標にロックオンするには、目標が1秒間直線飛行を続ける必要がある。敵機は不規則に旋回しながら飛んでおり、まれに1秒の直線フライトを見せる。直線フライトが完了してロックオンが確定した瞬間にタップして発射。旋回中に発射しても外れる。5機撃墜でクリア。',
    objects: [
      { shape: 'triangle', role: '敵機（旋回→直線を繰り返す）', note: '直線1秒でロックオン' },
      { shape: 'circle', role: 'ロックオンインジケーター（確定で光る）', note: '' },
      { shape: 'triangle', role: 'マッドシャーク（下部）', note: '' },
    ],
    counters: [
      { id: 'locked', name: 'ロックオン撃墜数', target: 5, note: '5機でクリア' },
    ],
    winTrigger: 'ロックオン確定の瞬間タップ5回',
    failTrigger: '旋回中タップ3回で失敗',
  },
  {
    id: 'arcade-269',
    title: '魔獣の王国',
    brand: 'KONAMI',
    year: 1987,
    duration: 20,
    difficulty: 'normal',
    concept: 'ダンジョンの通路に複数の扉があり、持っている「鍵の紋章」と一致する扉だけが開く。扉にはA〜Dの紋章が表示されており、持っている鍵の紋章と合う扉の前でタップして開ける。紋章が合わない扉をタップすると罠が発動する。5枚開扉でクリア。',
    objects: [
      { shape: 'rect', role: '扉×4（各自紋章付き）', note: '' },
      { shape: 'star', role: '所持鍵（紋章表示）', note: '' },
      { shape: 'face', role: '勇者（移動）', note: '' },
    ],
    counters: [
      { id: 'opened', name: '正しい開扉数', target: 5, note: '5枚でクリア' },
    ],
    winTrigger: '鍵紋章と扉紋章一致でタップ5回',
    failTrigger: '紋章不一致タップ3回で失敗',
  },
  {
    id: 'arcade-270',
    title: 'ボスコニアン',
    brand: 'ナムコ',
    year: 1981,
    duration: 20,
    difficulty: 'hard',
    concept: '宇宙要塞の周囲に6門の砲台が配置され、要塞自体がゆっくり回転している。砲台と砲台の間の隙間が自機の射線と重なったときだけ中枢コアへの貫通弾が届く——要塞の回転で隙間が射線上に来た瞬間にタップして発射。3回コア命中でクリア。',
    objects: [
      { shape: 'circle', role: '宇宙要塞（6門の砲台付き・回転）', note: '隙間が射線上で光る' },
      { shape: 'star', role: '中枢コア（要塞中心）', note: '' },
      { shape: 'triangle', role: '自機（左端）', note: '' },
    ],
    counters: [
      { id: 'core', name: 'コア命中数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '隙間が射線と重なった瞬間タップ3回',
    failTrigger: '砲台に弾が当たって跳ね返り3回で失敗',
  },
  {
    id: 'arcade-271',
    title: 'カダッシュ',
    brand: 'タイトー',
    year: 1989,
    duration: 20,
    difficulty: 'normal',
    concept: '4種の戦士（ファイター・メイジ・プリーステス・アマゾン）が順番に出撃する。各敵は「短距離弱点」「中距離弱点」「遠距離弱点」のいずれかを持つ。敵が出現するたびに弱点距離アイコンが1秒表示される——対応する戦士のボタンをタップして迎撃。5体正解でクリア。',
    objects: [
      { shape: 'face', role: '敵（弱点距離アイコン付き）', note: '1秒表示' },
      { shape: 'button', role: 'ファイターボタン（短距離）', note: '' },
      { shape: 'button', role: 'メイジボタン（遠距離）', note: '' },
      { shape: 'button', role: 'プリーステスボタン（中距離）', note: '' },
      { shape: 'button', role: 'アマゾンボタン（短〜中距離）', note: '' },
    ],
    counters: [
      { id: 'correct', name: '正戦士迎撃数', target: 5, note: '5体でクリア' },
    ],
    winTrigger: '弱点距離に合う戦士をタップ5回',
    failTrigger: '戦士ミス3回で失敗',
  },
  {
    id: 'arcade-272',
    title: 'ジンジンジップ',
    brand: 'アルュメ',
    year: 1992,
    duration: 20,
    difficulty: 'normal',
    concept: '小さなキャラクターが素早く飛び出してくる的を叩く。的は0.5秒だけ現れてすぐ引っ込む。複数の的が同時に飛び出してくる中で、最も「中央に近い的」だけをタップ——端の的はミスカウントされる。5回中央タップでクリア。',
    objects: [
      { shape: 'face', role: '的×複数（0.5秒だけ出現）', note: '中央の的が光る' },
      { shape: 'button', role: 'タップ', note: '' },
    ],
    counters: [
      { id: 'center', name: '中央的タップ数', target: 5, note: '5回でクリア' },
    ],
    winTrigger: '中央の的が出た瞬間タップ5回',
    failTrigger: '端の的をタップ3回で失敗',
  },
  {
    id: 'arcade-273',
    title: 'マンハッタン24分署',
    brand: 'KONAMI',
    year: 1986,
    duration: 20,
    difficulty: 'hard',
    concept: '犯人が人質を盾にしながら逃走車に向かっている。犯人と人質の距離が一定以上離れた瞬間だけ安全に制圧できる。人質が犯人から離れてよろめいた0.5秒の隙にタップして飛び蹴りを決める。人質が近い状態でタップすると人質が巻き込まれる。5人制圧でクリア。',
    objects: [
      { shape: 'face', role: '犯人（逃走中）', note: '' },
      { shape: 'face', role: '人質（犯人の横）', note: 'よろめき時に距離が広がる' },
      { shape: 'rect', role: '距離インジケーター', note: '安全距離で光る' },
      { shape: 'face', role: '警官（左端）', note: '' },
    ],
    counters: [
      { id: 'tackled', name: '制圧数', target: 5, note: '5人でクリア' },
    ],
    winTrigger: '人質が安全距離に離れた瞬間タップ5回',
    failTrigger: '人質が近い状態でタップ3回で失敗',
  },
  {
    id: 'arcade-274',
    title: 'ストライクガンナー S.T.G',
    brand: 'アテナ',
    year: 1991,
    duration: 20,
    difficulty: 'normal',
    concept: '戦闘機のレーダーが敵を1体ずつ順番にロックする。4体ロック後にタップすると4体同時にミサイルが飛んでいく。4体ロックが完成した瞬間にタップ——3体以下でタップすると残り体へのミサイルが足りなくなる。3回4体同時撃墜でクリア。',
    objects: [
      { shape: 'triangle', role: '自機（中央）', note: '' },
      { shape: 'face', role: '敵×複数（飛行）', note: 'ロック済みに印' },
      { shape: 'rect', role: 'ロックカウンター（1〜4）', note: '4で光る' },
    ],
    counters: [
      { id: 'salvos', name: '4体同時撃墜数', target: 3, note: '3回でクリア' },
    ],
    winTrigger: '4体ロック完成の瞬間タップ3回',
    failTrigger: '3体以下でタップ3回で失敗',
  },
  {
    id: 'arcade-275',
    title: 'ファイネストアワー',
    brand: 'ナムコ',
    year: 1989,
    duration: 20,
    difficulty: 'hard',
    concept: 'P-51ムスタングが零戦と空中戦をしている。零戦は急旋回などの機動を行った後に必ず0.5秒の「姿勢回復モーション」を見せる。回復モーション中だけ機銃が当たる——機動の最終フレームを確認してからタップ。機動中や通常飛行中のタップは外れる。3機撃墜でクリア。',
    objects: [
      { shape: 'triangle', role: '零戦（急旋回→姿勢回復）', note: '回復モーション中に光る' },
      { shape: 'triangle', role: 'ムスタング（中央）', note: '' },
      { shape: 'button', role: '機銃ボタン', note: '' },
    ],
    counters: [
      { id: 'shot', name: '撃墜数', target: 3, note: '3機でクリア' },
    ],
    winTrigger: '姿勢回復モーション中にタップ3回',
    failTrigger: '機動中または通常飛行中タップ3回で失敗',
  },
] as const;
